// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gtfs-realtime.proto

package sen.khyber.subway.client.proto;

/**
 * <pre>
 * An alert, indicating some sort of incident in the public transit network.
 * </pre>
 *
 * Protobuf type {@code transit_realtime.Alert}
 */
public  final class Alert extends
    com.google.protobuf.GeneratedMessageV3.ExtendableMessage<
      Alert> implements
    // @@protoc_insertion_point(message_implements:transit_realtime.Alert)
    AlertOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Alert.newBuilder() to construct.
  private Alert(com.google.protobuf.GeneratedMessageV3.ExtendableBuilder<sen.khyber.subway.client.proto.Alert, ?> builder) {
    super(builder);
  }
  private Alert() {
    activePeriod_ = java.util.Collections.emptyList();
    informedEntity_ = java.util.Collections.emptyList();
    cause_ = 1;
    effect_ = 8;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Alert(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              activePeriod_ = new java.util.ArrayList<sen.khyber.subway.client.proto.TimeRange>();
              mutable_bitField0_ |= 0x00000001;
            }
            activePeriod_.add(
                input.readMessage(sen.khyber.subway.client.proto.TimeRange.PARSER, extensionRegistry));
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              informedEntity_ = new java.util.ArrayList<sen.khyber.subway.client.proto.EntitySelector>();
              mutable_bitField0_ |= 0x00000002;
            }
            informedEntity_.add(
                input.readMessage(sen.khyber.subway.client.proto.EntitySelector.PARSER, extensionRegistry));
            break;
          }
          case 48: {
            int rawValue = input.readEnum();
            sen.khyber.subway.client.proto.Alert.Cause value = sen.khyber.subway.client.proto.Alert.Cause.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(6, rawValue);
            } else {
              bitField0_ |= 0x00000001;
              cause_ = rawValue;
            }
            break;
          }
          case 56: {
            int rawValue = input.readEnum();
            sen.khyber.subway.client.proto.Alert.Effect value = sen.khyber.subway.client.proto.Alert.Effect.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(7, rawValue);
            } else {
              bitField0_ |= 0x00000002;
              effect_ = rawValue;
            }
            break;
          }
          case 66: {
            sen.khyber.subway.client.proto.TranslatedString.Builder subBuilder = null;
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
              subBuilder = url_.toBuilder();
            }
            url_ = input.readMessage(sen.khyber.subway.client.proto.TranslatedString.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(url_);
              url_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000004;
            break;
          }
          case 82: {
            sen.khyber.subway.client.proto.TranslatedString.Builder subBuilder = null;
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
              subBuilder = headerText_.toBuilder();
            }
            headerText_ = input.readMessage(sen.khyber.subway.client.proto.TranslatedString.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(headerText_);
              headerText_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000008;
            break;
          }
          case 90: {
            sen.khyber.subway.client.proto.TranslatedString.Builder subBuilder = null;
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
              subBuilder = descriptionText_.toBuilder();
            }
            descriptionText_ = input.readMessage(sen.khyber.subway.client.proto.TranslatedString.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(descriptionText_);
              descriptionText_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000010;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        activePeriod_ = java.util.Collections.unmodifiableList(activePeriod_);
      }
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        informedEntity_ = java.util.Collections.unmodifiableList(informedEntity_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sen.khyber.subway.client.proto.GtfsRealtime.internal_static_transit_realtime_Alert_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sen.khyber.subway.client.proto.GtfsRealtime.internal_static_transit_realtime_Alert_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sen.khyber.subway.client.proto.Alert.class, sen.khyber.subway.client.proto.Alert.Builder.class);
  }

  /**
   * <pre>
   * Cause of this alert.
   * </pre>
   *
   * Protobuf enum {@code transit_realtime.Alert.Cause}
   */
  public enum Cause
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_CAUSE = 1;</code>
     */
    UNKNOWN_CAUSE(1),
    /**
     * <pre>
     * Not machine-representable.
     * </pre>
     *
     * <code>OTHER_CAUSE = 2;</code>
     */
    OTHER_CAUSE(2),
    /**
     * <code>TECHNICAL_PROBLEM = 3;</code>
     */
    TECHNICAL_PROBLEM(3),
    /**
     * <pre>
     * Public transit agency employees stopped working.
     * </pre>
     *
     * <code>STRIKE = 4;</code>
     */
    STRIKE(4),
    /**
     * <pre>
     * People are blocking the streets.
     * </pre>
     *
     * <code>DEMONSTRATION = 5;</code>
     */
    DEMONSTRATION(5),
    /**
     * <code>ACCIDENT = 6;</code>
     */
    ACCIDENT(6),
    /**
     * <code>HOLIDAY = 7;</code>
     */
    HOLIDAY(7),
    /**
     * <code>WEATHER = 8;</code>
     */
    WEATHER(8),
    /**
     * <code>MAINTENANCE = 9;</code>
     */
    MAINTENANCE(9),
    /**
     * <code>CONSTRUCTION = 10;</code>
     */
    CONSTRUCTION(10),
    /**
     * <code>POLICE_ACTIVITY = 11;</code>
     */
    POLICE_ACTIVITY(11),
    /**
     * <code>MEDICAL_EMERGENCY = 12;</code>
     */
    MEDICAL_EMERGENCY(12),
    ;

    /**
     * <code>UNKNOWN_CAUSE = 1;</code>
     */
    public static final int UNKNOWN_CAUSE_VALUE = 1;
    /**
     * <pre>
     * Not machine-representable.
     * </pre>
     *
     * <code>OTHER_CAUSE = 2;</code>
     */
    public static final int OTHER_CAUSE_VALUE = 2;
    /**
     * <code>TECHNICAL_PROBLEM = 3;</code>
     */
    public static final int TECHNICAL_PROBLEM_VALUE = 3;
    /**
     * <pre>
     * Public transit agency employees stopped working.
     * </pre>
     *
     * <code>STRIKE = 4;</code>
     */
    public static final int STRIKE_VALUE = 4;
    /**
     * <pre>
     * People are blocking the streets.
     * </pre>
     *
     * <code>DEMONSTRATION = 5;</code>
     */
    public static final int DEMONSTRATION_VALUE = 5;
    /**
     * <code>ACCIDENT = 6;</code>
     */
    public static final int ACCIDENT_VALUE = 6;
    /**
     * <code>HOLIDAY = 7;</code>
     */
    public static final int HOLIDAY_VALUE = 7;
    /**
     * <code>WEATHER = 8;</code>
     */
    public static final int WEATHER_VALUE = 8;
    /**
     * <code>MAINTENANCE = 9;</code>
     */
    public static final int MAINTENANCE_VALUE = 9;
    /**
     * <code>CONSTRUCTION = 10;</code>
     */
    public static final int CONSTRUCTION_VALUE = 10;
    /**
     * <code>POLICE_ACTIVITY = 11;</code>
     */
    public static final int POLICE_ACTIVITY_VALUE = 11;
    /**
     * <code>MEDICAL_EMERGENCY = 12;</code>
     */
    public static final int MEDICAL_EMERGENCY_VALUE = 12;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Cause valueOf(int value) {
      return forNumber(value);
    }

    public static Cause forNumber(int value) {
      switch (value) {
        case 1: return UNKNOWN_CAUSE;
        case 2: return OTHER_CAUSE;
        case 3: return TECHNICAL_PROBLEM;
        case 4: return STRIKE;
        case 5: return DEMONSTRATION;
        case 6: return ACCIDENT;
        case 7: return HOLIDAY;
        case 8: return WEATHER;
        case 9: return MAINTENANCE;
        case 10: return CONSTRUCTION;
        case 11: return POLICE_ACTIVITY;
        case 12: return MEDICAL_EMERGENCY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Cause>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Cause> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Cause>() {
            public Cause findValueByNumber(int number) {
              return Cause.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return sen.khyber.subway.client.proto.Alert.getDescriptor().getEnumTypes().get(0);
    }

    private static final Cause[] VALUES = values();

    public static Cause valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Cause(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:transit_realtime.Alert.Cause)
  }

  /**
   * <pre>
   * What is the effect of this problem on the affected entity.
   * </pre>
   *
   * Protobuf enum {@code transit_realtime.Alert.Effect}
   */
  public enum Effect
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NO_SERVICE = 1;</code>
     */
    NO_SERVICE(1),
    /**
     * <code>REDUCED_SERVICE = 2;</code>
     */
    REDUCED_SERVICE(2),
    /**
     * <pre>
     * We don't care about INsignificant delays: they are hard to detect, have
     * little impact on the user, and would clutter the results as they are too
     * frequent.
     * </pre>
     *
     * <code>SIGNIFICANT_DELAYS = 3;</code>
     */
    SIGNIFICANT_DELAYS(3),
    /**
     * <code>DETOUR = 4;</code>
     */
    DETOUR(4),
    /**
     * <code>ADDITIONAL_SERVICE = 5;</code>
     */
    ADDITIONAL_SERVICE(5),
    /**
     * <code>MODIFIED_SERVICE = 6;</code>
     */
    MODIFIED_SERVICE(6),
    /**
     * <code>OTHER_EFFECT = 7;</code>
     */
    OTHER_EFFECT(7),
    /**
     * <code>UNKNOWN_EFFECT = 8;</code>
     */
    UNKNOWN_EFFECT(8),
    /**
     * <code>STOP_MOVED = 9;</code>
     */
    STOP_MOVED(9),
    ;

    /**
     * <code>NO_SERVICE = 1;</code>
     */
    public static final int NO_SERVICE_VALUE = 1;
    /**
     * <code>REDUCED_SERVICE = 2;</code>
     */
    public static final int REDUCED_SERVICE_VALUE = 2;
    /**
     * <pre>
     * We don't care about INsignificant delays: they are hard to detect, have
     * little impact on the user, and would clutter the results as they are too
     * frequent.
     * </pre>
     *
     * <code>SIGNIFICANT_DELAYS = 3;</code>
     */
    public static final int SIGNIFICANT_DELAYS_VALUE = 3;
    /**
     * <code>DETOUR = 4;</code>
     */
    public static final int DETOUR_VALUE = 4;
    /**
     * <code>ADDITIONAL_SERVICE = 5;</code>
     */
    public static final int ADDITIONAL_SERVICE_VALUE = 5;
    /**
     * <code>MODIFIED_SERVICE = 6;</code>
     */
    public static final int MODIFIED_SERVICE_VALUE = 6;
    /**
     * <code>OTHER_EFFECT = 7;</code>
     */
    public static final int OTHER_EFFECT_VALUE = 7;
    /**
     * <code>UNKNOWN_EFFECT = 8;</code>
     */
    public static final int UNKNOWN_EFFECT_VALUE = 8;
    /**
     * <code>STOP_MOVED = 9;</code>
     */
    public static final int STOP_MOVED_VALUE = 9;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Effect valueOf(int value) {
      return forNumber(value);
    }

    public static Effect forNumber(int value) {
      switch (value) {
        case 1: return NO_SERVICE;
        case 2: return REDUCED_SERVICE;
        case 3: return SIGNIFICANT_DELAYS;
        case 4: return DETOUR;
        case 5: return ADDITIONAL_SERVICE;
        case 6: return MODIFIED_SERVICE;
        case 7: return OTHER_EFFECT;
        case 8: return UNKNOWN_EFFECT;
        case 9: return STOP_MOVED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Effect>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Effect> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Effect>() {
            public Effect findValueByNumber(int number) {
              return Effect.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return sen.khyber.subway.client.proto.Alert.getDescriptor().getEnumTypes().get(1);
    }

    private static final Effect[] VALUES = values();

    public static Effect valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Effect(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:transit_realtime.Alert.Effect)
  }

  private int bitField0_;
  public static final int ACTIVE_PERIOD_FIELD_NUMBER = 1;
  private java.util.List<sen.khyber.subway.client.proto.TimeRange> activePeriod_;
  /**
   * <pre>
   * Time when the alert should be shown to the user. If missing, the
   * alert will be shown as long as it appears in the feed.
   * If multiple ranges are given, the alert will be shown during all of them.
   * </pre>
   *
   * <code>repeated .transit_realtime.TimeRange active_period = 1;</code>
   */
  public java.util.List<sen.khyber.subway.client.proto.TimeRange> getActivePeriodList() {
    return activePeriod_;
  }
  /**
   * <pre>
   * Time when the alert should be shown to the user. If missing, the
   * alert will be shown as long as it appears in the feed.
   * If multiple ranges are given, the alert will be shown during all of them.
   * </pre>
   *
   * <code>repeated .transit_realtime.TimeRange active_period = 1;</code>
   */
  public java.util.List<? extends sen.khyber.subway.client.proto.TimeRangeOrBuilder> 
      getActivePeriodOrBuilderList() {
    return activePeriod_;
  }
  /**
   * <pre>
   * Time when the alert should be shown to the user. If missing, the
   * alert will be shown as long as it appears in the feed.
   * If multiple ranges are given, the alert will be shown during all of them.
   * </pre>
   *
   * <code>repeated .transit_realtime.TimeRange active_period = 1;</code>
   */
  public int getActivePeriodCount() {
    return activePeriod_.size();
  }
  /**
   * <pre>
   * Time when the alert should be shown to the user. If missing, the
   * alert will be shown as long as it appears in the feed.
   * If multiple ranges are given, the alert will be shown during all of them.
   * </pre>
   *
   * <code>repeated .transit_realtime.TimeRange active_period = 1;</code>
   */
  public sen.khyber.subway.client.proto.TimeRange getActivePeriod(int index) {
    return activePeriod_.get(index);
  }
  /**
   * <pre>
   * Time when the alert should be shown to the user. If missing, the
   * alert will be shown as long as it appears in the feed.
   * If multiple ranges are given, the alert will be shown during all of them.
   * </pre>
   *
   * <code>repeated .transit_realtime.TimeRange active_period = 1;</code>
   */
  public sen.khyber.subway.client.proto.TimeRangeOrBuilder getActivePeriodOrBuilder(
      int index) {
    return activePeriod_.get(index);
  }

  public static final int INFORMED_ENTITY_FIELD_NUMBER = 5;
  private java.util.List<sen.khyber.subway.client.proto.EntitySelector> informedEntity_;
  /**
   * <pre>
   * Entities whose users we should notify of this alert.
   * </pre>
   *
   * <code>repeated .transit_realtime.EntitySelector informed_entity = 5;</code>
   */
  public java.util.List<sen.khyber.subway.client.proto.EntitySelector> getInformedEntityList() {
    return informedEntity_;
  }
  /**
   * <pre>
   * Entities whose users we should notify of this alert.
   * </pre>
   *
   * <code>repeated .transit_realtime.EntitySelector informed_entity = 5;</code>
   */
  public java.util.List<? extends sen.khyber.subway.client.proto.EntitySelectorOrBuilder> 
      getInformedEntityOrBuilderList() {
    return informedEntity_;
  }
  /**
   * <pre>
   * Entities whose users we should notify of this alert.
   * </pre>
   *
   * <code>repeated .transit_realtime.EntitySelector informed_entity = 5;</code>
   */
  public int getInformedEntityCount() {
    return informedEntity_.size();
  }
  /**
   * <pre>
   * Entities whose users we should notify of this alert.
   * </pre>
   *
   * <code>repeated .transit_realtime.EntitySelector informed_entity = 5;</code>
   */
  public sen.khyber.subway.client.proto.EntitySelector getInformedEntity(int index) {
    return informedEntity_.get(index);
  }
  /**
   * <pre>
   * Entities whose users we should notify of this alert.
   * </pre>
   *
   * <code>repeated .transit_realtime.EntitySelector informed_entity = 5;</code>
   */
  public sen.khyber.subway.client.proto.EntitySelectorOrBuilder getInformedEntityOrBuilder(
      int index) {
    return informedEntity_.get(index);
  }

  public static final int CAUSE_FIELD_NUMBER = 6;
  private int cause_;
  /**
   * <code>optional .transit_realtime.Alert.Cause cause = 6 [default = UNKNOWN_CAUSE];</code>
   */
  public boolean hasCause() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional .transit_realtime.Alert.Cause cause = 6 [default = UNKNOWN_CAUSE];</code>
   */
  public sen.khyber.subway.client.proto.Alert.Cause getCause() {
    sen.khyber.subway.client.proto.Alert.Cause result = sen.khyber.subway.client.proto.Alert.Cause.valueOf(cause_);
    return result == null ? sen.khyber.subway.client.proto.Alert.Cause.UNKNOWN_CAUSE : result;
  }

  public static final int EFFECT_FIELD_NUMBER = 7;
  private int effect_;
  /**
   * <code>optional .transit_realtime.Alert.Effect effect = 7 [default = UNKNOWN_EFFECT];</code>
   */
  public boolean hasEffect() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional .transit_realtime.Alert.Effect effect = 7 [default = UNKNOWN_EFFECT];</code>
   */
  public sen.khyber.subway.client.proto.Alert.Effect getEffect() {
    sen.khyber.subway.client.proto.Alert.Effect result = sen.khyber.subway.client.proto.Alert.Effect.valueOf(effect_);
    return result == null ? sen.khyber.subway.client.proto.Alert.Effect.UNKNOWN_EFFECT : result;
  }

  public static final int URL_FIELD_NUMBER = 8;
  private sen.khyber.subway.client.proto.TranslatedString url_;
  /**
   * <pre>
   * The URL which provides additional information about the alert.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString url = 8;</code>
   */
  public boolean hasUrl() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <pre>
   * The URL which provides additional information about the alert.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString url = 8;</code>
   */
  public sen.khyber.subway.client.proto.TranslatedString getUrl() {
    return url_ == null ? sen.khyber.subway.client.proto.TranslatedString.getDefaultInstance() : url_;
  }
  /**
   * <pre>
   * The URL which provides additional information about the alert.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString url = 8;</code>
   */
  public sen.khyber.subway.client.proto.TranslatedStringOrBuilder getUrlOrBuilder() {
    return url_ == null ? sen.khyber.subway.client.proto.TranslatedString.getDefaultInstance() : url_;
  }

  public static final int HEADER_TEXT_FIELD_NUMBER = 10;
  private sen.khyber.subway.client.proto.TranslatedString headerText_;
  /**
   * <pre>
   * Alert header. Contains a short summary of the alert text as plain-text.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString header_text = 10;</code>
   */
  public boolean hasHeaderText() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <pre>
   * Alert header. Contains a short summary of the alert text as plain-text.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString header_text = 10;</code>
   */
  public sen.khyber.subway.client.proto.TranslatedString getHeaderText() {
    return headerText_ == null ? sen.khyber.subway.client.proto.TranslatedString.getDefaultInstance() : headerText_;
  }
  /**
   * <pre>
   * Alert header. Contains a short summary of the alert text as plain-text.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString header_text = 10;</code>
   */
  public sen.khyber.subway.client.proto.TranslatedStringOrBuilder getHeaderTextOrBuilder() {
    return headerText_ == null ? sen.khyber.subway.client.proto.TranslatedString.getDefaultInstance() : headerText_;
  }

  public static final int DESCRIPTION_TEXT_FIELD_NUMBER = 11;
  private sen.khyber.subway.client.proto.TranslatedString descriptionText_;
  /**
   * <pre>
   * Full description for the alert as plain-text. The information in the
   * description should add to the information of the header.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString description_text = 11;</code>
   */
  public boolean hasDescriptionText() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <pre>
   * Full description for the alert as plain-text. The information in the
   * description should add to the information of the header.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString description_text = 11;</code>
   */
  public sen.khyber.subway.client.proto.TranslatedString getDescriptionText() {
    return descriptionText_ == null ? sen.khyber.subway.client.proto.TranslatedString.getDefaultInstance() : descriptionText_;
  }
  /**
   * <pre>
   * Full description for the alert as plain-text. The information in the
   * description should add to the information of the header.
   * </pre>
   *
   * <code>optional .transit_realtime.TranslatedString description_text = 11;</code>
   */
  public sen.khyber.subway.client.proto.TranslatedStringOrBuilder getDescriptionTextOrBuilder() {
    return descriptionText_ == null ? sen.khyber.subway.client.proto.TranslatedString.getDefaultInstance() : descriptionText_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    for (int i = 0; i < getInformedEntityCount(); i++) {
      if (!getInformedEntity(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    if (hasUrl()) {
      if (!getUrl().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    if (hasHeaderText()) {
      if (!getHeaderText().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    if (hasDescriptionText()) {
      if (!getDescriptionText().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    if (!extensionsAreInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .ExtendableMessage<sen.khyber.subway.client.proto.Alert>.ExtensionWriter
        extensionWriter = newExtensionWriter();
    for (int i = 0; i < activePeriod_.size(); i++) {
      output.writeMessage(1, activePeriod_.get(i));
    }
    for (int i = 0; i < informedEntity_.size(); i++) {
      output.writeMessage(5, informedEntity_.get(i));
    }
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeEnum(6, cause_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeEnum(7, effect_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeMessage(8, getUrl());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeMessage(10, getHeaderText());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeMessage(11, getDescriptionText());
    }
    extensionWriter.writeUntil(2000, output);
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < activePeriod_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, activePeriod_.get(i));
    }
    for (int i = 0; i < informedEntity_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, informedEntity_.get(i));
    }
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, cause_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, effect_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getUrl());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getHeaderText());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, getDescriptionText());
    }
    size += extensionsSerializedSize();
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sen.khyber.subway.client.proto.Alert)) {
      return super.equals(obj);
    }
    sen.khyber.subway.client.proto.Alert other = (sen.khyber.subway.client.proto.Alert) obj;

    boolean result = true;
    result = result && getActivePeriodList()
        .equals(other.getActivePeriodList());
    result = result && getInformedEntityList()
        .equals(other.getInformedEntityList());
    result = result && (hasCause() == other.hasCause());
    if (hasCause()) {
      result = result && cause_ == other.cause_;
    }
    result = result && (hasEffect() == other.hasEffect());
    if (hasEffect()) {
      result = result && effect_ == other.effect_;
    }
    result = result && (hasUrl() == other.hasUrl());
    if (hasUrl()) {
      result = result && getUrl()
          .equals(other.getUrl());
    }
    result = result && (hasHeaderText() == other.hasHeaderText());
    if (hasHeaderText()) {
      result = result && getHeaderText()
          .equals(other.getHeaderText());
    }
    result = result && (hasDescriptionText() == other.hasDescriptionText());
    if (hasDescriptionText()) {
      result = result && getDescriptionText()
          .equals(other.getDescriptionText());
    }
    result = result && unknownFields.equals(other.unknownFields);
    result = result &&
        getExtensionFields().equals(other.getExtensionFields());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getActivePeriodCount() > 0) {
      hash = (37 * hash) + ACTIVE_PERIOD_FIELD_NUMBER;
      hash = (53 * hash) + getActivePeriodList().hashCode();
    }
    if (getInformedEntityCount() > 0) {
      hash = (37 * hash) + INFORMED_ENTITY_FIELD_NUMBER;
      hash = (53 * hash) + getInformedEntityList().hashCode();
    }
    if (hasCause()) {
      hash = (37 * hash) + CAUSE_FIELD_NUMBER;
      hash = (53 * hash) + cause_;
    }
    if (hasEffect()) {
      hash = (37 * hash) + EFFECT_FIELD_NUMBER;
      hash = (53 * hash) + effect_;
    }
    if (hasUrl()) {
      hash = (37 * hash) + URL_FIELD_NUMBER;
      hash = (53 * hash) + getUrl().hashCode();
    }
    if (hasHeaderText()) {
      hash = (37 * hash) + HEADER_TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getHeaderText().hashCode();
    }
    if (hasDescriptionText()) {
      hash = (37 * hash) + DESCRIPTION_TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getDescriptionText().hashCode();
    }
    hash = hashFields(hash, getExtensionFields());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sen.khyber.subway.client.proto.Alert parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sen.khyber.subway.client.proto.Alert parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sen.khyber.subway.client.proto.Alert parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sen.khyber.subway.client.proto.Alert parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sen.khyber.subway.client.proto.Alert parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sen.khyber.subway.client.proto.Alert parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sen.khyber.subway.client.proto.Alert parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sen.khyber.subway.client.proto.Alert parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static sen.khyber.subway.client.proto.Alert parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static sen.khyber.subway.client.proto.Alert parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sen.khyber.subway.client.proto.Alert parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sen.khyber.subway.client.proto.Alert parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sen.khyber.subway.client.proto.Alert prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * An alert, indicating some sort of incident in the public transit network.
   * </pre>
   *
   * Protobuf type {@code transit_realtime.Alert}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.ExtendableBuilder<
        sen.khyber.subway.client.proto.Alert, Builder> implements
      // @@protoc_insertion_point(builder_implements:transit_realtime.Alert)
      sen.khyber.subway.client.proto.AlertOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sen.khyber.subway.client.proto.GtfsRealtime.internal_static_transit_realtime_Alert_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sen.khyber.subway.client.proto.GtfsRealtime.internal_static_transit_realtime_Alert_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sen.khyber.subway.client.proto.Alert.class, sen.khyber.subway.client.proto.Alert.Builder.class);
    }

    // Construct using sen.khyber.subway.client.proto.Alert.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getActivePeriodFieldBuilder();
        getInformedEntityFieldBuilder();
        getUrlFieldBuilder();
        getHeaderTextFieldBuilder();
        getDescriptionTextFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (activePeriodBuilder_ == null) {
        activePeriod_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        activePeriodBuilder_.clear();
      }
      if (informedEntityBuilder_ == null) {
        informedEntity_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        informedEntityBuilder_.clear();
      }
      cause_ = 1;
      bitField0_ = (bitField0_ & ~0x00000004);
      effect_ = 8;
      bitField0_ = (bitField0_ & ~0x00000008);
      if (urlBuilder_ == null) {
        url_ = null;
      } else {
        urlBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      if (headerTextBuilder_ == null) {
        headerText_ = null;
      } else {
        headerTextBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      if (descriptionTextBuilder_ == null) {
        descriptionText_ = null;
      } else {
        descriptionTextBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sen.khyber.subway.client.proto.GtfsRealtime.internal_static_transit_realtime_Alert_descriptor;
    }

    public sen.khyber.subway.client.proto.Alert getDefaultInstanceForType() {
      return sen.khyber.subway.client.proto.Alert.getDefaultInstance();
    }

    public sen.khyber.subway.client.proto.Alert build() {
      sen.khyber.subway.client.proto.Alert result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public sen.khyber.subway.client.proto.Alert buildPartial() {
      sen.khyber.subway.client.proto.Alert result = new sen.khyber.subway.client.proto.Alert(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (activePeriodBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          activePeriod_ = java.util.Collections.unmodifiableList(activePeriod_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.activePeriod_ = activePeriod_;
      } else {
        result.activePeriod_ = activePeriodBuilder_.build();
      }
      if (informedEntityBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          informedEntity_ = java.util.Collections.unmodifiableList(informedEntity_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.informedEntity_ = informedEntity_;
      } else {
        result.informedEntity_ = informedEntityBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000001;
      }
      result.cause_ = cause_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000002;
      }
      result.effect_ = effect_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000004;
      }
      if (urlBuilder_ == null) {
        result.url_ = url_;
      } else {
        result.url_ = urlBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000008;
      }
      if (headerTextBuilder_ == null) {
        result.headerText_ = headerText_;
      } else {
        result.headerText_ = headerTextBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
        to_bitField0_ |= 0x00000010;
      }
      if (descriptionTextBuilder_ == null) {
        result.descriptionText_ = descriptionText_;
      } else {
        result.descriptionText_ = descriptionTextBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public <Type> Builder setExtension(
        com.google.protobuf.GeneratedMessage.GeneratedExtension<
            sen.khyber.subway.client.proto.Alert, Type> extension,
        Type value) {
      return (Builder) super.setExtension(extension, value);
    }
    public <Type> Builder setExtension(
        com.google.protobuf.GeneratedMessage.GeneratedExtension<
            sen.khyber.subway.client.proto.Alert, java.util.List<Type>> extension,
        int index, Type value) {
      return (Builder) super.setExtension(extension, index, value);
    }
    public <Type> Builder addExtension(
        com.google.protobuf.GeneratedMessage.GeneratedExtension<
            sen.khyber.subway.client.proto.Alert, java.util.List<Type>> extension,
        Type value) {
      return (Builder) super.addExtension(extension, value);
    }
    public <Type> Builder clearExtension(
        com.google.protobuf.GeneratedMessage.GeneratedExtension<
            sen.khyber.subway.client.proto.Alert, ?> extension) {
      return (Builder) super.clearExtension(extension);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sen.khyber.subway.client.proto.Alert) {
        return mergeFrom((sen.khyber.subway.client.proto.Alert)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sen.khyber.subway.client.proto.Alert other) {
      if (other == sen.khyber.subway.client.proto.Alert.getDefaultInstance()) return this;
      if (activePeriodBuilder_ == null) {
        if (!other.activePeriod_.isEmpty()) {
          if (activePeriod_.isEmpty()) {
            activePeriod_ = other.activePeriod_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureActivePeriodIsMutable();
            activePeriod_.addAll(other.activePeriod_);
          }
          onChanged();
        }
      } else {
        if (!other.activePeriod_.isEmpty()) {
          if (activePeriodBuilder_.isEmpty()) {
            activePeriodBuilder_.dispose();
            activePeriodBuilder_ = null;
            activePeriod_ = other.activePeriod_;
            bitField0_ = (bitField0_ & ~0x00000001);
            activePeriodBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getActivePeriodFieldBuilder() : null;
          } else {
            activePeriodBuilder_.addAllMessages(other.activePeriod_);
          }
        }
      }
      if (informedEntityBuilder_ == null) {
        if (!other.informedEntity_.isEmpty()) {
          if (informedEntity_.isEmpty()) {
            informedEntity_ = other.informedEntity_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureInformedEntityIsMutable();
            informedEntity_.addAll(other.informedEntity_);
          }
          onChanged();
        }
      } else {
        if (!other.informedEntity_.isEmpty()) {
          if (informedEntityBuilder_.isEmpty()) {
            informedEntityBuilder_.dispose();
            informedEntityBuilder_ = null;
            informedEntity_ = other.informedEntity_;
            bitField0_ = (bitField0_ & ~0x00000002);
            informedEntityBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getInformedEntityFieldBuilder() : null;
          } else {
            informedEntityBuilder_.addAllMessages(other.informedEntity_);
          }
        }
      }
      if (other.hasCause()) {
        setCause(other.getCause());
      }
      if (other.hasEffect()) {
        setEffect(other.getEffect());
      }
      if (other.hasUrl()) {
        mergeUrl(other.getUrl());
      }
      if (other.hasHeaderText()) {
        mergeHeaderText(other.getHeaderText());
      }
      if (other.hasDescriptionText()) {
        mergeDescriptionText(other.getDescriptionText());
      }
      this.mergeExtensionFields(other);
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      for (int i = 0; i < getInformedEntityCount(); i++) {
        if (!getInformedEntity(i).isInitialized()) {
          return false;
        }
      }
      if (hasUrl()) {
        if (!getUrl().isInitialized()) {
          return false;
        }
      }
      if (hasHeaderText()) {
        if (!getHeaderText().isInitialized()) {
          return false;
        }
      }
      if (hasDescriptionText()) {
        if (!getDescriptionText().isInitialized()) {
          return false;
        }
      }
      if (!extensionsAreInitialized()) {
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      sen.khyber.subway.client.proto.Alert parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (sen.khyber.subway.client.proto.Alert) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<sen.khyber.subway.client.proto.TimeRange> activePeriod_ =
      java.util.Collections.emptyList();
    private void ensureActivePeriodIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        activePeriod_ = new java.util.ArrayList<sen.khyber.subway.client.proto.TimeRange>(activePeriod_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        sen.khyber.subway.client.proto.TimeRange, sen.khyber.subway.client.proto.TimeRange.Builder, sen.khyber.subway.client.proto.TimeRangeOrBuilder> activePeriodBuilder_;

    /**
     * <pre>
     * Time when the alert should be shown to the user. If missing, the
     * alert will be shown as long as it appears in the feed.
     * If multiple ranges are given, the alert will be shown during all of them.
     * </pre>
     *
     * <code>repeated .transit_realtime.TimeRange active_period = 1;</code>
     */
    public java.util.List<sen.khyber.subway.client.proto.TimeRange> getActivePeriodList() {
      if (activePeriodBuilder_ == null) {
        return java.util.Collections.unmodifiableList(activePeriod_);
      } else {
        return activePeriodBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Time when the alert should be shown to the user. If missing, the
     * alert will be shown as long as it appears in the feed.
     * If multiple ranges are given, the alert will be shown during all of them.
     * </pre>
     *
     * <code>repeated .transit_realtime.TimeRange active_period = 1;</code>
     */
    public int getActivePeriodCount() {
      if (activePeriodBuilder_ == null) {
        return activePeriod_.size();
      } else {
        return activePeriodBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Time when the alert should be shown to the user. If missing, the
     * alert will be shown as long as it appears in the feed.
     * If multiple ranges are given, the alert will be shown during all of them.
     * </pre>
     *
     * <code>repeated .transit_realtime.TimeRange active_period = 1;</code>
     */
    public sen.khyber.subway.client.proto.TimeRange getActivePeriod(int index) {
      if (activePeriodBuilder_ == null) {
        return activePeriod_.get(index);
      } else {
        return activePeriodBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Time when the alert should be shown to the user. If missing, the
     * alert will be shown as long as it appears in the feed.
     * If multiple ranges are given, the alert will be shown during all of them.
     * </pre>
     *
     * <code>repeated .transit_realtime.TimeRange active_period = 1;</code>
     */
    public Builder setActivePeriod(
        int index, sen.khyber.subway.client.proto.TimeRange value) {
      if (activePeriodBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureActivePeriodIsMutable();
        activePeriod_.set(index, value);
        onChanged();
      } else {
        activePeriodBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Time when the alert should be shown to the user. If missing, the
     * alert will be shown as long as it appears in the feed.
     * If multiple ranges are given, the alert will be shown during all of them.
     * </pre>
     *
     * <code>repeated .transit_realtime.TimeRange active_period = 1;</code>
     */
    public Builder setActivePeriod(
        int index, sen.khyber.subway.client.proto.TimeRange.Builder builderForValue) {
      if (activePeriodBuilder_ == null) {
        ensureActivePeriodIsMutable();
        activePeriod_.set(index, builderForValue.build());
        onChanged();
      } else {
        activePeriodBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Time when the alert should be shown to the user. If missing, the
     * alert will be shown as long as it appears in the feed.
     * If multiple ranges are given, the alert will be shown during all of them.
     * </pre>
     *
     * <code>repeated .transit_realtime.TimeRange active_period = 1;</code>
     */
    public Builder addActivePeriod(sen.khyber.subway.client.proto.TimeRange value) {
      if (activePeriodBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureActivePeriodIsMutable();
        activePeriod_.add(value);
        onChanged();
      } else {
        activePeriodBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Time when the alert should be shown to the user. If missing, the
     * alert will be shown as long as it appears in the feed.
     * If multiple ranges are given, the alert will be shown during all of them.
     * </pre>
     *
     * <code>repeated .transit_realtime.TimeRange active_period = 1;</code>
     */
    public Builder addActivePeriod(
        int index, sen.khyber.subway.client.proto.TimeRange value) {
      if (activePeriodBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureActivePeriodIsMutable();
        activePeriod_.add(index, value);
        onChanged();
      } else {
        activePeriodBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Time when the alert should be shown to the user. If missing, the
     * alert will be shown as long as it appears in the feed.
     * If multiple ranges are given, the alert will be shown during all of them.
     * </pre>
     *
     * <code>repeated .transit_realtime.TimeRange active_period = 1;</code>
     */
    public Builder addActivePeriod(
        sen.khyber.subway.client.proto.TimeRange.Builder builderForValue) {
      if (activePeriodBuilder_ == null) {
        ensureActivePeriodIsMutable();
        activePeriod_.add(builderForValue.build());
        onChanged();
      } else {
        activePeriodBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Time when the alert should be shown to the user. If missing, the
     * alert will be shown as long as it appears in the feed.
     * If multiple ranges are given, the alert will be shown during all of them.
     * </pre>
     *
     * <code>repeated .transit_realtime.TimeRange active_period = 1;</code>
     */
    public Builder addActivePeriod(
        int index, sen.khyber.subway.client.proto.TimeRange.Builder builderForValue) {
      if (activePeriodBuilder_ == null) {
        ensureActivePeriodIsMutable();
        activePeriod_.add(index, builderForValue.build());
        onChanged();
      } else {
        activePeriodBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Time when the alert should be shown to the user. If missing, the
     * alert will be shown as long as it appears in the feed.
     * If multiple ranges are given, the alert will be shown during all of them.
     * </pre>
     *
     * <code>repeated .transit_realtime.TimeRange active_period = 1;</code>
     */
    public Builder addAllActivePeriod(
        java.lang.Iterable<? extends sen.khyber.subway.client.proto.TimeRange> values) {
      if (activePeriodBuilder_ == null) {
        ensureActivePeriodIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, activePeriod_);
        onChanged();
      } else {
        activePeriodBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Time when the alert should be shown to the user. If missing, the
     * alert will be shown as long as it appears in the feed.
     * If multiple ranges are given, the alert will be shown during all of them.
     * </pre>
     *
     * <code>repeated .transit_realtime.TimeRange active_period = 1;</code>
     */
    public Builder clearActivePeriod() {
      if (activePeriodBuilder_ == null) {
        activePeriod_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        activePeriodBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Time when the alert should be shown to the user. If missing, the
     * alert will be shown as long as it appears in the feed.
     * If multiple ranges are given, the alert will be shown during all of them.
     * </pre>
     *
     * <code>repeated .transit_realtime.TimeRange active_period = 1;</code>
     */
    public Builder removeActivePeriod(int index) {
      if (activePeriodBuilder_ == null) {
        ensureActivePeriodIsMutable();
        activePeriod_.remove(index);
        onChanged();
      } else {
        activePeriodBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Time when the alert should be shown to the user. If missing, the
     * alert will be shown as long as it appears in the feed.
     * If multiple ranges are given, the alert will be shown during all of them.
     * </pre>
     *
     * <code>repeated .transit_realtime.TimeRange active_period = 1;</code>
     */
    public sen.khyber.subway.client.proto.TimeRange.Builder getActivePeriodBuilder(
        int index) {
      return getActivePeriodFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Time when the alert should be shown to the user. If missing, the
     * alert will be shown as long as it appears in the feed.
     * If multiple ranges are given, the alert will be shown during all of them.
     * </pre>
     *
     * <code>repeated .transit_realtime.TimeRange active_period = 1;</code>
     */
    public sen.khyber.subway.client.proto.TimeRangeOrBuilder getActivePeriodOrBuilder(
        int index) {
      if (activePeriodBuilder_ == null) {
        return activePeriod_.get(index);  } else {
        return activePeriodBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Time when the alert should be shown to the user. If missing, the
     * alert will be shown as long as it appears in the feed.
     * If multiple ranges are given, the alert will be shown during all of them.
     * </pre>
     *
     * <code>repeated .transit_realtime.TimeRange active_period = 1;</code>
     */
    public java.util.List<? extends sen.khyber.subway.client.proto.TimeRangeOrBuilder> 
         getActivePeriodOrBuilderList() {
      if (activePeriodBuilder_ != null) {
        return activePeriodBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(activePeriod_);
      }
    }
    /**
     * <pre>
     * Time when the alert should be shown to the user. If missing, the
     * alert will be shown as long as it appears in the feed.
     * If multiple ranges are given, the alert will be shown during all of them.
     * </pre>
     *
     * <code>repeated .transit_realtime.TimeRange active_period = 1;</code>
     */
    public sen.khyber.subway.client.proto.TimeRange.Builder addActivePeriodBuilder() {
      return getActivePeriodFieldBuilder().addBuilder(
          sen.khyber.subway.client.proto.TimeRange.getDefaultInstance());
    }
    /**
     * <pre>
     * Time when the alert should be shown to the user. If missing, the
     * alert will be shown as long as it appears in the feed.
     * If multiple ranges are given, the alert will be shown during all of them.
     * </pre>
     *
     * <code>repeated .transit_realtime.TimeRange active_period = 1;</code>
     */
    public sen.khyber.subway.client.proto.TimeRange.Builder addActivePeriodBuilder(
        int index) {
      return getActivePeriodFieldBuilder().addBuilder(
          index, sen.khyber.subway.client.proto.TimeRange.getDefaultInstance());
    }
    /**
     * <pre>
     * Time when the alert should be shown to the user. If missing, the
     * alert will be shown as long as it appears in the feed.
     * If multiple ranges are given, the alert will be shown during all of them.
     * </pre>
     *
     * <code>repeated .transit_realtime.TimeRange active_period = 1;</code>
     */
    public java.util.List<sen.khyber.subway.client.proto.TimeRange.Builder> 
         getActivePeriodBuilderList() {
      return getActivePeriodFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        sen.khyber.subway.client.proto.TimeRange, sen.khyber.subway.client.proto.TimeRange.Builder, sen.khyber.subway.client.proto.TimeRangeOrBuilder> 
        getActivePeriodFieldBuilder() {
      if (activePeriodBuilder_ == null) {
        activePeriodBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            sen.khyber.subway.client.proto.TimeRange, sen.khyber.subway.client.proto.TimeRange.Builder, sen.khyber.subway.client.proto.TimeRangeOrBuilder>(
                activePeriod_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        activePeriod_ = null;
      }
      return activePeriodBuilder_;
    }

    private java.util.List<sen.khyber.subway.client.proto.EntitySelector> informedEntity_ =
      java.util.Collections.emptyList();
    private void ensureInformedEntityIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        informedEntity_ = new java.util.ArrayList<sen.khyber.subway.client.proto.EntitySelector>(informedEntity_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        sen.khyber.subway.client.proto.EntitySelector, sen.khyber.subway.client.proto.EntitySelector.Builder, sen.khyber.subway.client.proto.EntitySelectorOrBuilder> informedEntityBuilder_;

    /**
     * <pre>
     * Entities whose users we should notify of this alert.
     * </pre>
     *
     * <code>repeated .transit_realtime.EntitySelector informed_entity = 5;</code>
     */
    public java.util.List<sen.khyber.subway.client.proto.EntitySelector> getInformedEntityList() {
      if (informedEntityBuilder_ == null) {
        return java.util.Collections.unmodifiableList(informedEntity_);
      } else {
        return informedEntityBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Entities whose users we should notify of this alert.
     * </pre>
     *
     * <code>repeated .transit_realtime.EntitySelector informed_entity = 5;</code>
     */
    public int getInformedEntityCount() {
      if (informedEntityBuilder_ == null) {
        return informedEntity_.size();
      } else {
        return informedEntityBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Entities whose users we should notify of this alert.
     * </pre>
     *
     * <code>repeated .transit_realtime.EntitySelector informed_entity = 5;</code>
     */
    public sen.khyber.subway.client.proto.EntitySelector getInformedEntity(int index) {
      if (informedEntityBuilder_ == null) {
        return informedEntity_.get(index);
      } else {
        return informedEntityBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Entities whose users we should notify of this alert.
     * </pre>
     *
     * <code>repeated .transit_realtime.EntitySelector informed_entity = 5;</code>
     */
    public Builder setInformedEntity(
        int index, sen.khyber.subway.client.proto.EntitySelector value) {
      if (informedEntityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInformedEntityIsMutable();
        informedEntity_.set(index, value);
        onChanged();
      } else {
        informedEntityBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Entities whose users we should notify of this alert.
     * </pre>
     *
     * <code>repeated .transit_realtime.EntitySelector informed_entity = 5;</code>
     */
    public Builder setInformedEntity(
        int index, sen.khyber.subway.client.proto.EntitySelector.Builder builderForValue) {
      if (informedEntityBuilder_ == null) {
        ensureInformedEntityIsMutable();
        informedEntity_.set(index, builderForValue.build());
        onChanged();
      } else {
        informedEntityBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Entities whose users we should notify of this alert.
     * </pre>
     *
     * <code>repeated .transit_realtime.EntitySelector informed_entity = 5;</code>
     */
    public Builder addInformedEntity(sen.khyber.subway.client.proto.EntitySelector value) {
      if (informedEntityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInformedEntityIsMutable();
        informedEntity_.add(value);
        onChanged();
      } else {
        informedEntityBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Entities whose users we should notify of this alert.
     * </pre>
     *
     * <code>repeated .transit_realtime.EntitySelector informed_entity = 5;</code>
     */
    public Builder addInformedEntity(
        int index, sen.khyber.subway.client.proto.EntitySelector value) {
      if (informedEntityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInformedEntityIsMutable();
        informedEntity_.add(index, value);
        onChanged();
      } else {
        informedEntityBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Entities whose users we should notify of this alert.
     * </pre>
     *
     * <code>repeated .transit_realtime.EntitySelector informed_entity = 5;</code>
     */
    public Builder addInformedEntity(
        sen.khyber.subway.client.proto.EntitySelector.Builder builderForValue) {
      if (informedEntityBuilder_ == null) {
        ensureInformedEntityIsMutable();
        informedEntity_.add(builderForValue.build());
        onChanged();
      } else {
        informedEntityBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Entities whose users we should notify of this alert.
     * </pre>
     *
     * <code>repeated .transit_realtime.EntitySelector informed_entity = 5;</code>
     */
    public Builder addInformedEntity(
        int index, sen.khyber.subway.client.proto.EntitySelector.Builder builderForValue) {
      if (informedEntityBuilder_ == null) {
        ensureInformedEntityIsMutable();
        informedEntity_.add(index, builderForValue.build());
        onChanged();
      } else {
        informedEntityBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Entities whose users we should notify of this alert.
     * </pre>
     *
     * <code>repeated .transit_realtime.EntitySelector informed_entity = 5;</code>
     */
    public Builder addAllInformedEntity(
        java.lang.Iterable<? extends sen.khyber.subway.client.proto.EntitySelector> values) {
      if (informedEntityBuilder_ == null) {
        ensureInformedEntityIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, informedEntity_);
        onChanged();
      } else {
        informedEntityBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Entities whose users we should notify of this alert.
     * </pre>
     *
     * <code>repeated .transit_realtime.EntitySelector informed_entity = 5;</code>
     */
    public Builder clearInformedEntity() {
      if (informedEntityBuilder_ == null) {
        informedEntity_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        informedEntityBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Entities whose users we should notify of this alert.
     * </pre>
     *
     * <code>repeated .transit_realtime.EntitySelector informed_entity = 5;</code>
     */
    public Builder removeInformedEntity(int index) {
      if (informedEntityBuilder_ == null) {
        ensureInformedEntityIsMutable();
        informedEntity_.remove(index);
        onChanged();
      } else {
        informedEntityBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Entities whose users we should notify of this alert.
     * </pre>
     *
     * <code>repeated .transit_realtime.EntitySelector informed_entity = 5;</code>
     */
    public sen.khyber.subway.client.proto.EntitySelector.Builder getInformedEntityBuilder(
        int index) {
      return getInformedEntityFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Entities whose users we should notify of this alert.
     * </pre>
     *
     * <code>repeated .transit_realtime.EntitySelector informed_entity = 5;</code>
     */
    public sen.khyber.subway.client.proto.EntitySelectorOrBuilder getInformedEntityOrBuilder(
        int index) {
      if (informedEntityBuilder_ == null) {
        return informedEntity_.get(index);  } else {
        return informedEntityBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Entities whose users we should notify of this alert.
     * </pre>
     *
     * <code>repeated .transit_realtime.EntitySelector informed_entity = 5;</code>
     */
    public java.util.List<? extends sen.khyber.subway.client.proto.EntitySelectorOrBuilder> 
         getInformedEntityOrBuilderList() {
      if (informedEntityBuilder_ != null) {
        return informedEntityBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(informedEntity_);
      }
    }
    /**
     * <pre>
     * Entities whose users we should notify of this alert.
     * </pre>
     *
     * <code>repeated .transit_realtime.EntitySelector informed_entity = 5;</code>
     */
    public sen.khyber.subway.client.proto.EntitySelector.Builder addInformedEntityBuilder() {
      return getInformedEntityFieldBuilder().addBuilder(
          sen.khyber.subway.client.proto.EntitySelector.getDefaultInstance());
    }
    /**
     * <pre>
     * Entities whose users we should notify of this alert.
     * </pre>
     *
     * <code>repeated .transit_realtime.EntitySelector informed_entity = 5;</code>
     */
    public sen.khyber.subway.client.proto.EntitySelector.Builder addInformedEntityBuilder(
        int index) {
      return getInformedEntityFieldBuilder().addBuilder(
          index, sen.khyber.subway.client.proto.EntitySelector.getDefaultInstance());
    }
    /**
     * <pre>
     * Entities whose users we should notify of this alert.
     * </pre>
     *
     * <code>repeated .transit_realtime.EntitySelector informed_entity = 5;</code>
     */
    public java.util.List<sen.khyber.subway.client.proto.EntitySelector.Builder> 
         getInformedEntityBuilderList() {
      return getInformedEntityFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        sen.khyber.subway.client.proto.EntitySelector, sen.khyber.subway.client.proto.EntitySelector.Builder, sen.khyber.subway.client.proto.EntitySelectorOrBuilder> 
        getInformedEntityFieldBuilder() {
      if (informedEntityBuilder_ == null) {
        informedEntityBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            sen.khyber.subway.client.proto.EntitySelector, sen.khyber.subway.client.proto.EntitySelector.Builder, sen.khyber.subway.client.proto.EntitySelectorOrBuilder>(
                informedEntity_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        informedEntity_ = null;
      }
      return informedEntityBuilder_;
    }

    private int cause_ = 1;
    /**
     * <code>optional .transit_realtime.Alert.Cause cause = 6 [default = UNKNOWN_CAUSE];</code>
     */
    public boolean hasCause() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .transit_realtime.Alert.Cause cause = 6 [default = UNKNOWN_CAUSE];</code>
     */
    public sen.khyber.subway.client.proto.Alert.Cause getCause() {
      sen.khyber.subway.client.proto.Alert.Cause result = sen.khyber.subway.client.proto.Alert.Cause.valueOf(cause_);
      return result == null ? sen.khyber.subway.client.proto.Alert.Cause.UNKNOWN_CAUSE : result;
    }
    /**
     * <code>optional .transit_realtime.Alert.Cause cause = 6 [default = UNKNOWN_CAUSE];</code>
     */
    public Builder setCause(sen.khyber.subway.client.proto.Alert.Cause value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      cause_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .transit_realtime.Alert.Cause cause = 6 [default = UNKNOWN_CAUSE];</code>
     */
    public Builder clearCause() {
      bitField0_ = (bitField0_ & ~0x00000004);
      cause_ = 1;
      onChanged();
      return this;
    }

    private int effect_ = 8;
    /**
     * <code>optional .transit_realtime.Alert.Effect effect = 7 [default = UNKNOWN_EFFECT];</code>
     */
    public boolean hasEffect() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .transit_realtime.Alert.Effect effect = 7 [default = UNKNOWN_EFFECT];</code>
     */
    public sen.khyber.subway.client.proto.Alert.Effect getEffect() {
      sen.khyber.subway.client.proto.Alert.Effect result = sen.khyber.subway.client.proto.Alert.Effect.valueOf(effect_);
      return result == null ? sen.khyber.subway.client.proto.Alert.Effect.UNKNOWN_EFFECT : result;
    }
    /**
     * <code>optional .transit_realtime.Alert.Effect effect = 7 [default = UNKNOWN_EFFECT];</code>
     */
    public Builder setEffect(sen.khyber.subway.client.proto.Alert.Effect value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      effect_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .transit_realtime.Alert.Effect effect = 7 [default = UNKNOWN_EFFECT];</code>
     */
    public Builder clearEffect() {
      bitField0_ = (bitField0_ & ~0x00000008);
      effect_ = 8;
      onChanged();
      return this;
    }

    private sen.khyber.subway.client.proto.TranslatedString url_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        sen.khyber.subway.client.proto.TranslatedString, sen.khyber.subway.client.proto.TranslatedString.Builder, sen.khyber.subway.client.proto.TranslatedStringOrBuilder> urlBuilder_;
    /**
     * <pre>
     * The URL which provides additional information about the alert.
     * </pre>
     *
     * <code>optional .transit_realtime.TranslatedString url = 8;</code>
     */
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     * The URL which provides additional information about the alert.
     * </pre>
     *
     * <code>optional .transit_realtime.TranslatedString url = 8;</code>
     */
    public sen.khyber.subway.client.proto.TranslatedString getUrl() {
      if (urlBuilder_ == null) {
        return url_ == null ? sen.khyber.subway.client.proto.TranslatedString.getDefaultInstance() : url_;
      } else {
        return urlBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The URL which provides additional information about the alert.
     * </pre>
     *
     * <code>optional .transit_realtime.TranslatedString url = 8;</code>
     */
    public Builder setUrl(sen.khyber.subway.client.proto.TranslatedString value) {
      if (urlBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        url_ = value;
        onChanged();
      } else {
        urlBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <pre>
     * The URL which provides additional information about the alert.
     * </pre>
     *
     * <code>optional .transit_realtime.TranslatedString url = 8;</code>
     */
    public Builder setUrl(
        sen.khyber.subway.client.proto.TranslatedString.Builder builderForValue) {
      if (urlBuilder_ == null) {
        url_ = builderForValue.build();
        onChanged();
      } else {
        urlBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <pre>
     * The URL which provides additional information about the alert.
     * </pre>
     *
     * <code>optional .transit_realtime.TranslatedString url = 8;</code>
     */
    public Builder mergeUrl(sen.khyber.subway.client.proto.TranslatedString value) {
      if (urlBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010) &&
            url_ != null &&
            url_ != sen.khyber.subway.client.proto.TranslatedString.getDefaultInstance()) {
          url_ =
            sen.khyber.subway.client.proto.TranslatedString.newBuilder(url_).mergeFrom(value).buildPartial();
        } else {
          url_ = value;
        }
        onChanged();
      } else {
        urlBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <pre>
     * The URL which provides additional information about the alert.
     * </pre>
     *
     * <code>optional .transit_realtime.TranslatedString url = 8;</code>
     */
    public Builder clearUrl() {
      if (urlBuilder_ == null) {
        url_ = null;
        onChanged();
      } else {
        urlBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }
    /**
     * <pre>
     * The URL which provides additional information about the alert.
     * </pre>
     *
     * <code>optional .transit_realtime.TranslatedString url = 8;</code>
     */
    public sen.khyber.subway.client.proto.TranslatedString.Builder getUrlBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getUrlFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The URL which provides additional information about the alert.
     * </pre>
     *
     * <code>optional .transit_realtime.TranslatedString url = 8;</code>
     */
    public sen.khyber.subway.client.proto.TranslatedStringOrBuilder getUrlOrBuilder() {
      if (urlBuilder_ != null) {
        return urlBuilder_.getMessageOrBuilder();
      } else {
        return url_ == null ?
            sen.khyber.subway.client.proto.TranslatedString.getDefaultInstance() : url_;
      }
    }
    /**
     * <pre>
     * The URL which provides additional information about the alert.
     * </pre>
     *
     * <code>optional .transit_realtime.TranslatedString url = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        sen.khyber.subway.client.proto.TranslatedString, sen.khyber.subway.client.proto.TranslatedString.Builder, sen.khyber.subway.client.proto.TranslatedStringOrBuilder> 
        getUrlFieldBuilder() {
      if (urlBuilder_ == null) {
        urlBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            sen.khyber.subway.client.proto.TranslatedString, sen.khyber.subway.client.proto.TranslatedString.Builder, sen.khyber.subway.client.proto.TranslatedStringOrBuilder>(
                getUrl(),
                getParentForChildren(),
                isClean());
        url_ = null;
      }
      return urlBuilder_;
    }

    private sen.khyber.subway.client.proto.TranslatedString headerText_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        sen.khyber.subway.client.proto.TranslatedString, sen.khyber.subway.client.proto.TranslatedString.Builder, sen.khyber.subway.client.proto.TranslatedStringOrBuilder> headerTextBuilder_;
    /**
     * <pre>
     * Alert header. Contains a short summary of the alert text as plain-text.
     * </pre>
     *
     * <code>optional .transit_realtime.TranslatedString header_text = 10;</code>
     */
    public boolean hasHeaderText() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <pre>
     * Alert header. Contains a short summary of the alert text as plain-text.
     * </pre>
     *
     * <code>optional .transit_realtime.TranslatedString header_text = 10;</code>
     */
    public sen.khyber.subway.client.proto.TranslatedString getHeaderText() {
      if (headerTextBuilder_ == null) {
        return headerText_ == null ? sen.khyber.subway.client.proto.TranslatedString.getDefaultInstance() : headerText_;
      } else {
        return headerTextBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Alert header. Contains a short summary of the alert text as plain-text.
     * </pre>
     *
     * <code>optional .transit_realtime.TranslatedString header_text = 10;</code>
     */
    public Builder setHeaderText(sen.khyber.subway.client.proto.TranslatedString value) {
      if (headerTextBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        headerText_ = value;
        onChanged();
      } else {
        headerTextBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <pre>
     * Alert header. Contains a short summary of the alert text as plain-text.
     * </pre>
     *
     * <code>optional .transit_realtime.TranslatedString header_text = 10;</code>
     */
    public Builder setHeaderText(
        sen.khyber.subway.client.proto.TranslatedString.Builder builderForValue) {
      if (headerTextBuilder_ == null) {
        headerText_ = builderForValue.build();
        onChanged();
      } else {
        headerTextBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <pre>
     * Alert header. Contains a short summary of the alert text as plain-text.
     * </pre>
     *
     * <code>optional .transit_realtime.TranslatedString header_text = 10;</code>
     */
    public Builder mergeHeaderText(sen.khyber.subway.client.proto.TranslatedString value) {
      if (headerTextBuilder_ == null) {
        if (((bitField0_ & 0x00000020) == 0x00000020) &&
            headerText_ != null &&
            headerText_ != sen.khyber.subway.client.proto.TranslatedString.getDefaultInstance()) {
          headerText_ =
            sen.khyber.subway.client.proto.TranslatedString.newBuilder(headerText_).mergeFrom(value).buildPartial();
        } else {
          headerText_ = value;
        }
        onChanged();
      } else {
        headerTextBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <pre>
     * Alert header. Contains a short summary of the alert text as plain-text.
     * </pre>
     *
     * <code>optional .transit_realtime.TranslatedString header_text = 10;</code>
     */
    public Builder clearHeaderText() {
      if (headerTextBuilder_ == null) {
        headerText_ = null;
        onChanged();
      } else {
        headerTextBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }
    /**
     * <pre>
     * Alert header. Contains a short summary of the alert text as plain-text.
     * </pre>
     *
     * <code>optional .transit_realtime.TranslatedString header_text = 10;</code>
     */
    public sen.khyber.subway.client.proto.TranslatedString.Builder getHeaderTextBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getHeaderTextFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Alert header. Contains a short summary of the alert text as plain-text.
     * </pre>
     *
     * <code>optional .transit_realtime.TranslatedString header_text = 10;</code>
     */
    public sen.khyber.subway.client.proto.TranslatedStringOrBuilder getHeaderTextOrBuilder() {
      if (headerTextBuilder_ != null) {
        return headerTextBuilder_.getMessageOrBuilder();
      } else {
        return headerText_ == null ?
            sen.khyber.subway.client.proto.TranslatedString.getDefaultInstance() : headerText_;
      }
    }
    /**
     * <pre>
     * Alert header. Contains a short summary of the alert text as plain-text.
     * </pre>
     *
     * <code>optional .transit_realtime.TranslatedString header_text = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        sen.khyber.subway.client.proto.TranslatedString, sen.khyber.subway.client.proto.TranslatedString.Builder, sen.khyber.subway.client.proto.TranslatedStringOrBuilder> 
        getHeaderTextFieldBuilder() {
      if (headerTextBuilder_ == null) {
        headerTextBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            sen.khyber.subway.client.proto.TranslatedString, sen.khyber.subway.client.proto.TranslatedString.Builder, sen.khyber.subway.client.proto.TranslatedStringOrBuilder>(
                getHeaderText(),
                getParentForChildren(),
                isClean());
        headerText_ = null;
      }
      return headerTextBuilder_;
    }

    private sen.khyber.subway.client.proto.TranslatedString descriptionText_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        sen.khyber.subway.client.proto.TranslatedString, sen.khyber.subway.client.proto.TranslatedString.Builder, sen.khyber.subway.client.proto.TranslatedStringOrBuilder> descriptionTextBuilder_;
    /**
     * <pre>
     * Full description for the alert as plain-text. The information in the
     * description should add to the information of the header.
     * </pre>
     *
     * <code>optional .transit_realtime.TranslatedString description_text = 11;</code>
     */
    public boolean hasDescriptionText() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <pre>
     * Full description for the alert as plain-text. The information in the
     * description should add to the information of the header.
     * </pre>
     *
     * <code>optional .transit_realtime.TranslatedString description_text = 11;</code>
     */
    public sen.khyber.subway.client.proto.TranslatedString getDescriptionText() {
      if (descriptionTextBuilder_ == null) {
        return descriptionText_ == null ? sen.khyber.subway.client.proto.TranslatedString.getDefaultInstance() : descriptionText_;
      } else {
        return descriptionTextBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Full description for the alert as plain-text. The information in the
     * description should add to the information of the header.
     * </pre>
     *
     * <code>optional .transit_realtime.TranslatedString description_text = 11;</code>
     */
    public Builder setDescriptionText(sen.khyber.subway.client.proto.TranslatedString value) {
      if (descriptionTextBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        descriptionText_ = value;
        onChanged();
      } else {
        descriptionTextBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <pre>
     * Full description for the alert as plain-text. The information in the
     * description should add to the information of the header.
     * </pre>
     *
     * <code>optional .transit_realtime.TranslatedString description_text = 11;</code>
     */
    public Builder setDescriptionText(
        sen.khyber.subway.client.proto.TranslatedString.Builder builderForValue) {
      if (descriptionTextBuilder_ == null) {
        descriptionText_ = builderForValue.build();
        onChanged();
      } else {
        descriptionTextBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <pre>
     * Full description for the alert as plain-text. The information in the
     * description should add to the information of the header.
     * </pre>
     *
     * <code>optional .transit_realtime.TranslatedString description_text = 11;</code>
     */
    public Builder mergeDescriptionText(sen.khyber.subway.client.proto.TranslatedString value) {
      if (descriptionTextBuilder_ == null) {
        if (((bitField0_ & 0x00000040) == 0x00000040) &&
            descriptionText_ != null &&
            descriptionText_ != sen.khyber.subway.client.proto.TranslatedString.getDefaultInstance()) {
          descriptionText_ =
            sen.khyber.subway.client.proto.TranslatedString.newBuilder(descriptionText_).mergeFrom(value).buildPartial();
        } else {
          descriptionText_ = value;
        }
        onChanged();
      } else {
        descriptionTextBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <pre>
     * Full description for the alert as plain-text. The information in the
     * description should add to the information of the header.
     * </pre>
     *
     * <code>optional .transit_realtime.TranslatedString description_text = 11;</code>
     */
    public Builder clearDescriptionText() {
      if (descriptionTextBuilder_ == null) {
        descriptionText_ = null;
        onChanged();
      } else {
        descriptionTextBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }
    /**
     * <pre>
     * Full description for the alert as plain-text. The information in the
     * description should add to the information of the header.
     * </pre>
     *
     * <code>optional .transit_realtime.TranslatedString description_text = 11;</code>
     */
    public sen.khyber.subway.client.proto.TranslatedString.Builder getDescriptionTextBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getDescriptionTextFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Full description for the alert as plain-text. The information in the
     * description should add to the information of the header.
     * </pre>
     *
     * <code>optional .transit_realtime.TranslatedString description_text = 11;</code>
     */
    public sen.khyber.subway.client.proto.TranslatedStringOrBuilder getDescriptionTextOrBuilder() {
      if (descriptionTextBuilder_ != null) {
        return descriptionTextBuilder_.getMessageOrBuilder();
      } else {
        return descriptionText_ == null ?
            sen.khyber.subway.client.proto.TranslatedString.getDefaultInstance() : descriptionText_;
      }
    }
    /**
     * <pre>
     * Full description for the alert as plain-text. The information in the
     * description should add to the information of the header.
     * </pre>
     *
     * <code>optional .transit_realtime.TranslatedString description_text = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        sen.khyber.subway.client.proto.TranslatedString, sen.khyber.subway.client.proto.TranslatedString.Builder, sen.khyber.subway.client.proto.TranslatedStringOrBuilder> 
        getDescriptionTextFieldBuilder() {
      if (descriptionTextBuilder_ == null) {
        descriptionTextBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            sen.khyber.subway.client.proto.TranslatedString, sen.khyber.subway.client.proto.TranslatedString.Builder, sen.khyber.subway.client.proto.TranslatedStringOrBuilder>(
                getDescriptionText(),
                getParentForChildren(),
                isClean());
        descriptionText_ = null;
      }
      return descriptionTextBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:transit_realtime.Alert)
  }

  // @@protoc_insertion_point(class_scope:transit_realtime.Alert)
  private static final sen.khyber.subway.client.proto.Alert DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sen.khyber.subway.client.proto.Alert();
  }

  public static sen.khyber.subway.client.proto.Alert getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Alert>
      PARSER = new com.google.protobuf.AbstractParser<Alert>() {
    public Alert parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Alert(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Alert> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Alert> getParserForType() {
    return PARSER;
  }

  public sen.khyber.subway.client.proto.Alert getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

