// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gtfs-realtime.proto

package sen.khyber.subway.client.proto;

/**
 * <pre>
 * A definition (or update) of an entity in the transit feed.
 * </pre>
 *
 * Protobuf type {@code transit_realtime.FeedEntity}
 */
public  final class FeedEntity extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:transit_realtime.FeedEntity)
    FeedEntityOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FeedEntity.newBuilder() to construct.
  private FeedEntity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FeedEntity() {
    id_ = "";
    isDeleted_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FeedEntity(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            id_ = bs;
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            isDeleted_ = input.readBool();
            break;
          }
          case 26: {
            sen.khyber.subway.client.proto.TripUpdate.Builder subBuilder = null;
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
              subBuilder = tripUpdate_.toBuilder();
            }
            tripUpdate_ = input.readMessage(sen.khyber.subway.client.proto.TripUpdate.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(tripUpdate_);
              tripUpdate_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000004;
            break;
          }
          case 34: {
            sen.khyber.subway.client.proto.VehiclePosition.Builder subBuilder = null;
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
              subBuilder = vehicle_.toBuilder();
            }
            vehicle_ = input.readMessage(sen.khyber.subway.client.proto.VehiclePosition.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(vehicle_);
              vehicle_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000008;
            break;
          }
          case 42: {
            sen.khyber.subway.client.proto.Alert.Builder subBuilder = null;
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
              subBuilder = alert_.toBuilder();
            }
            alert_ = input.readMessage(sen.khyber.subway.client.proto.Alert.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(alert_);
              alert_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000010;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sen.khyber.subway.client.proto.GtfsRealtime.internal_static_transit_realtime_FeedEntity_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sen.khyber.subway.client.proto.GtfsRealtime.internal_static_transit_realtime_FeedEntity_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sen.khyber.subway.client.proto.FeedEntity.class, sen.khyber.subway.client.proto.FeedEntity.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <pre>
   * The ids are used only to provide incrementality support. The id should be
   * unique within a FeedMessage. Consequent FeedMessages may contain
   * FeedEntities with the same id. In case of a DIFFERENTIAL update the new
   * FeedEntity with some id will replace the old FeedEntity with the same id
   * (or delete it - see is_deleted below).
   * The actual GTFS entities (e.g. stations, routes, trips) referenced by the
   * feed must be specified by explicit selectors (see EntitySelector below for
   * more info).
   * </pre>
   *
   * <code>required string id = 1;</code>
   */
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <pre>
   * The ids are used only to provide incrementality support. The id should be
   * unique within a FeedMessage. Consequent FeedMessages may contain
   * FeedEntities with the same id. In case of a DIFFERENTIAL update the new
   * FeedEntity with some id will replace the old FeedEntity with the same id
   * (or delete it - see is_deleted below).
   * The actual GTFS entities (e.g. stations, routes, trips) referenced by the
   * feed must be specified by explicit selectors (see EntitySelector below for
   * more info).
   * </pre>
   *
   * <code>required string id = 1;</code>
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        id_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * The ids are used only to provide incrementality support. The id should be
   * unique within a FeedMessage. Consequent FeedMessages may contain
   * FeedEntities with the same id. In case of a DIFFERENTIAL update the new
   * FeedEntity with some id will replace the old FeedEntity with the same id
   * (or delete it - see is_deleted below).
   * The actual GTFS entities (e.g. stations, routes, trips) referenced by the
   * feed must be specified by explicit selectors (see EntitySelector below for
   * more info).
   * </pre>
   *
   * <code>required string id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IS_DELETED_FIELD_NUMBER = 2;
  private boolean isDeleted_;
  /**
   * <pre>
   * Whether this entity is to be deleted. Relevant only for incremental
   * fetches.
   * </pre>
   *
   * <code>optional bool is_deleted = 2 [default = false];</code>
   */
  public boolean hasIsDeleted() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <pre>
   * Whether this entity is to be deleted. Relevant only for incremental
   * fetches.
   * </pre>
   *
   * <code>optional bool is_deleted = 2 [default = false];</code>
   */
  public boolean getIsDeleted() {
    return isDeleted_;
  }

  public static final int TRIP_UPDATE_FIELD_NUMBER = 3;
  private sen.khyber.subway.client.proto.TripUpdate tripUpdate_;
  /**
   * <pre>
   * Data about the entity itself. Exactly one of the following fields must be
   * present (unless the entity is being deleted).
   * </pre>
   *
   * <code>optional .transit_realtime.TripUpdate trip_update = 3;</code>
   */
  public boolean hasTripUpdate() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <pre>
   * Data about the entity itself. Exactly one of the following fields must be
   * present (unless the entity is being deleted).
   * </pre>
   *
   * <code>optional .transit_realtime.TripUpdate trip_update = 3;</code>
   */
  public sen.khyber.subway.client.proto.TripUpdate getTripUpdate() {
    return tripUpdate_ == null ? sen.khyber.subway.client.proto.TripUpdate.getDefaultInstance() : tripUpdate_;
  }
  /**
   * <pre>
   * Data about the entity itself. Exactly one of the following fields must be
   * present (unless the entity is being deleted).
   * </pre>
   *
   * <code>optional .transit_realtime.TripUpdate trip_update = 3;</code>
   */
  public sen.khyber.subway.client.proto.TripUpdateOrBuilder getTripUpdateOrBuilder() {
    return tripUpdate_ == null ? sen.khyber.subway.client.proto.TripUpdate.getDefaultInstance() : tripUpdate_;
  }

  public static final int VEHICLE_FIELD_NUMBER = 4;
  private sen.khyber.subway.client.proto.VehiclePosition vehicle_;
  /**
   * <code>optional .transit_realtime.VehiclePosition vehicle = 4;</code>
   */
  public boolean hasVehicle() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional .transit_realtime.VehiclePosition vehicle = 4;</code>
   */
  public sen.khyber.subway.client.proto.VehiclePosition getVehicle() {
    return vehicle_ == null ? sen.khyber.subway.client.proto.VehiclePosition.getDefaultInstance() : vehicle_;
  }
  /**
   * <code>optional .transit_realtime.VehiclePosition vehicle = 4;</code>
   */
  public sen.khyber.subway.client.proto.VehiclePositionOrBuilder getVehicleOrBuilder() {
    return vehicle_ == null ? sen.khyber.subway.client.proto.VehiclePosition.getDefaultInstance() : vehicle_;
  }

  public static final int ALERT_FIELD_NUMBER = 5;
  private sen.khyber.subway.client.proto.Alert alert_;
  /**
   * <code>optional .transit_realtime.Alert alert = 5;</code>
   */
  public boolean hasAlert() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional .transit_realtime.Alert alert = 5;</code>
   */
  public sen.khyber.subway.client.proto.Alert getAlert() {
    return alert_ == null ? sen.khyber.subway.client.proto.Alert.getDefaultInstance() : alert_;
  }
  /**
   * <code>optional .transit_realtime.Alert alert = 5;</code>
   */
  public sen.khyber.subway.client.proto.AlertOrBuilder getAlertOrBuilder() {
    return alert_ == null ? sen.khyber.subway.client.proto.Alert.getDefaultInstance() : alert_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (hasTripUpdate()) {
      if (!getTripUpdate().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    if (hasVehicle()) {
      if (!getVehicle().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    if (hasAlert()) {
      if (!getAlert().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBool(2, isDeleted_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeMessage(3, getTripUpdate());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeMessage(4, getVehicle());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeMessage(5, getAlert());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, isDeleted_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getTripUpdate());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getVehicle());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getAlert());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sen.khyber.subway.client.proto.FeedEntity)) {
      return super.equals(obj);
    }
    sen.khyber.subway.client.proto.FeedEntity other = (sen.khyber.subway.client.proto.FeedEntity) obj;

    boolean result = true;
    result = result && (hasId() == other.hasId());
    if (hasId()) {
      result = result && getId()
          .equals(other.getId());
    }
    result = result && (hasIsDeleted() == other.hasIsDeleted());
    if (hasIsDeleted()) {
      result = result && (getIsDeleted()
          == other.getIsDeleted());
    }
    result = result && (hasTripUpdate() == other.hasTripUpdate());
    if (hasTripUpdate()) {
      result = result && getTripUpdate()
          .equals(other.getTripUpdate());
    }
    result = result && (hasVehicle() == other.hasVehicle());
    if (hasVehicle()) {
      result = result && getVehicle()
          .equals(other.getVehicle());
    }
    result = result && (hasAlert() == other.hasAlert());
    if (hasAlert()) {
      result = result && getAlert()
          .equals(other.getAlert());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    if (hasIsDeleted()) {
      hash = (37 * hash) + IS_DELETED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsDeleted());
    }
    if (hasTripUpdate()) {
      hash = (37 * hash) + TRIP_UPDATE_FIELD_NUMBER;
      hash = (53 * hash) + getTripUpdate().hashCode();
    }
    if (hasVehicle()) {
      hash = (37 * hash) + VEHICLE_FIELD_NUMBER;
      hash = (53 * hash) + getVehicle().hashCode();
    }
    if (hasAlert()) {
      hash = (37 * hash) + ALERT_FIELD_NUMBER;
      hash = (53 * hash) + getAlert().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sen.khyber.subway.client.proto.FeedEntity parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sen.khyber.subway.client.proto.FeedEntity parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sen.khyber.subway.client.proto.FeedEntity parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sen.khyber.subway.client.proto.FeedEntity parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sen.khyber.subway.client.proto.FeedEntity parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sen.khyber.subway.client.proto.FeedEntity parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sen.khyber.subway.client.proto.FeedEntity parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sen.khyber.subway.client.proto.FeedEntity parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static sen.khyber.subway.client.proto.FeedEntity parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static sen.khyber.subway.client.proto.FeedEntity parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sen.khyber.subway.client.proto.FeedEntity parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sen.khyber.subway.client.proto.FeedEntity parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sen.khyber.subway.client.proto.FeedEntity prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A definition (or update) of an entity in the transit feed.
   * </pre>
   *
   * Protobuf type {@code transit_realtime.FeedEntity}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:transit_realtime.FeedEntity)
      sen.khyber.subway.client.proto.FeedEntityOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sen.khyber.subway.client.proto.GtfsRealtime.internal_static_transit_realtime_FeedEntity_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sen.khyber.subway.client.proto.GtfsRealtime.internal_static_transit_realtime_FeedEntity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sen.khyber.subway.client.proto.FeedEntity.class, sen.khyber.subway.client.proto.FeedEntity.Builder.class);
    }

    // Construct using sen.khyber.subway.client.proto.FeedEntity.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTripUpdateFieldBuilder();
        getVehicleFieldBuilder();
        getAlertFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      id_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      isDeleted_ = false;
      bitField0_ = (bitField0_ & ~0x00000002);
      if (tripUpdateBuilder_ == null) {
        tripUpdate_ = null;
      } else {
        tripUpdateBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      if (vehicleBuilder_ == null) {
        vehicle_ = null;
      } else {
        vehicleBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      if (alertBuilder_ == null) {
        alert_ = null;
      } else {
        alertBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sen.khyber.subway.client.proto.GtfsRealtime.internal_static_transit_realtime_FeedEntity_descriptor;
    }

    public sen.khyber.subway.client.proto.FeedEntity getDefaultInstanceForType() {
      return sen.khyber.subway.client.proto.FeedEntity.getDefaultInstance();
    }

    public sen.khyber.subway.client.proto.FeedEntity build() {
      sen.khyber.subway.client.proto.FeedEntity result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public sen.khyber.subway.client.proto.FeedEntity buildPartial() {
      sen.khyber.subway.client.proto.FeedEntity result = new sen.khyber.subway.client.proto.FeedEntity(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.id_ = id_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.isDeleted_ = isDeleted_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      if (tripUpdateBuilder_ == null) {
        result.tripUpdate_ = tripUpdate_;
      } else {
        result.tripUpdate_ = tripUpdateBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      if (vehicleBuilder_ == null) {
        result.vehicle_ = vehicle_;
      } else {
        result.vehicle_ = vehicleBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      if (alertBuilder_ == null) {
        result.alert_ = alert_;
      } else {
        result.alert_ = alertBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sen.khyber.subway.client.proto.FeedEntity) {
        return mergeFrom((sen.khyber.subway.client.proto.FeedEntity)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sen.khyber.subway.client.proto.FeedEntity other) {
      if (other == sen.khyber.subway.client.proto.FeedEntity.getDefaultInstance()) return this;
      if (other.hasId()) {
        bitField0_ |= 0x00000001;
        id_ = other.id_;
        onChanged();
      }
      if (other.hasIsDeleted()) {
        setIsDeleted(other.getIsDeleted());
      }
      if (other.hasTripUpdate()) {
        mergeTripUpdate(other.getTripUpdate());
      }
      if (other.hasVehicle()) {
        mergeVehicle(other.getVehicle());
      }
      if (other.hasAlert()) {
        mergeAlert(other.getAlert());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      if (!hasId()) {
        return false;
      }
      if (hasTripUpdate()) {
        if (!getTripUpdate().isInitialized()) {
          return false;
        }
      }
      if (hasVehicle()) {
        if (!getVehicle().isInitialized()) {
          return false;
        }
      }
      if (hasAlert()) {
        if (!getAlert().isInitialized()) {
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      sen.khyber.subway.client.proto.FeedEntity parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (sen.khyber.subway.client.proto.FeedEntity) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <pre>
     * The ids are used only to provide incrementality support. The id should be
     * unique within a FeedMessage. Consequent FeedMessages may contain
     * FeedEntities with the same id. In case of a DIFFERENTIAL update the new
     * FeedEntity with some id will replace the old FeedEntity with the same id
     * (or delete it - see is_deleted below).
     * The actual GTFS entities (e.g. stations, routes, trips) referenced by the
     * feed must be specified by explicit selectors (see EntitySelector below for
     * more info).
     * </pre>
     *
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * The ids are used only to provide incrementality support. The id should be
     * unique within a FeedMessage. Consequent FeedMessages may contain
     * FeedEntities with the same id. In case of a DIFFERENTIAL update the new
     * FeedEntity with some id will replace the old FeedEntity with the same id
     * (or delete it - see is_deleted below).
     * The actual GTFS entities (e.g. stations, routes, trips) referenced by the
     * feed must be specified by explicit selectors (see EntitySelector below for
     * more info).
     * </pre>
     *
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The ids are used only to provide incrementality support. The id should be
     * unique within a FeedMessage. Consequent FeedMessages may contain
     * FeedEntities with the same id. In case of a DIFFERENTIAL update the new
     * FeedEntity with some id will replace the old FeedEntity with the same id
     * (or delete it - see is_deleted below).
     * The actual GTFS entities (e.g. stations, routes, trips) referenced by the
     * feed must be specified by explicit selectors (see EntitySelector below for
     * more info).
     * </pre>
     *
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The ids are used only to provide incrementality support. The id should be
     * unique within a FeedMessage. Consequent FeedMessages may contain
     * FeedEntities with the same id. In case of a DIFFERENTIAL update the new
     * FeedEntity with some id will replace the old FeedEntity with the same id
     * (or delete it - see is_deleted below).
     * The actual GTFS entities (e.g. stations, routes, trips) referenced by the
     * feed must be specified by explicit selectors (see EntitySelector below for
     * more info).
     * </pre>
     *
     * <code>required string id = 1;</code>
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ids are used only to provide incrementality support. The id should be
     * unique within a FeedMessage. Consequent FeedMessages may contain
     * FeedEntities with the same id. In case of a DIFFERENTIAL update the new
     * FeedEntity with some id will replace the old FeedEntity with the same id
     * (or delete it - see is_deleted below).
     * The actual GTFS entities (e.g. stations, routes, trips) referenced by the
     * feed must be specified by explicit selectors (see EntitySelector below for
     * more info).
     * </pre>
     *
     * <code>required string id = 1;</code>
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ids are used only to provide incrementality support. The id should be
     * unique within a FeedMessage. Consequent FeedMessages may contain
     * FeedEntities with the same id. In case of a DIFFERENTIAL update the new
     * FeedEntity with some id will replace the old FeedEntity with the same id
     * (or delete it - see is_deleted below).
     * The actual GTFS entities (e.g. stations, routes, trips) referenced by the
     * feed must be specified by explicit selectors (see EntitySelector below for
     * more info).
     * </pre>
     *
     * <code>required string id = 1;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }

    private boolean isDeleted_ ;
    /**
     * <pre>
     * Whether this entity is to be deleted. Relevant only for incremental
     * fetches.
     * </pre>
     *
     * <code>optional bool is_deleted = 2 [default = false];</code>
     */
    public boolean hasIsDeleted() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * Whether this entity is to be deleted. Relevant only for incremental
     * fetches.
     * </pre>
     *
     * <code>optional bool is_deleted = 2 [default = false];</code>
     */
    public boolean getIsDeleted() {
      return isDeleted_;
    }
    /**
     * <pre>
     * Whether this entity is to be deleted. Relevant only for incremental
     * fetches.
     * </pre>
     *
     * <code>optional bool is_deleted = 2 [default = false];</code>
     */
    public Builder setIsDeleted(boolean value) {
      bitField0_ |= 0x00000002;
      isDeleted_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether this entity is to be deleted. Relevant only for incremental
     * fetches.
     * </pre>
     *
     * <code>optional bool is_deleted = 2 [default = false];</code>
     */
    public Builder clearIsDeleted() {
      bitField0_ = (bitField0_ & ~0x00000002);
      isDeleted_ = false;
      onChanged();
      return this;
    }

    private sen.khyber.subway.client.proto.TripUpdate tripUpdate_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        sen.khyber.subway.client.proto.TripUpdate, sen.khyber.subway.client.proto.TripUpdate.Builder, sen.khyber.subway.client.proto.TripUpdateOrBuilder> tripUpdateBuilder_;
    /**
     * <pre>
     * Data about the entity itself. Exactly one of the following fields must be
     * present (unless the entity is being deleted).
     * </pre>
     *
     * <code>optional .transit_realtime.TripUpdate trip_update = 3;</code>
     */
    public boolean hasTripUpdate() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * Data about the entity itself. Exactly one of the following fields must be
     * present (unless the entity is being deleted).
     * </pre>
     *
     * <code>optional .transit_realtime.TripUpdate trip_update = 3;</code>
     */
    public sen.khyber.subway.client.proto.TripUpdate getTripUpdate() {
      if (tripUpdateBuilder_ == null) {
        return tripUpdate_ == null ? sen.khyber.subway.client.proto.TripUpdate.getDefaultInstance() : tripUpdate_;
      } else {
        return tripUpdateBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Data about the entity itself. Exactly one of the following fields must be
     * present (unless the entity is being deleted).
     * </pre>
     *
     * <code>optional .transit_realtime.TripUpdate trip_update = 3;</code>
     */
    public Builder setTripUpdate(sen.khyber.subway.client.proto.TripUpdate value) {
      if (tripUpdateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tripUpdate_ = value;
        onChanged();
      } else {
        tripUpdateBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <pre>
     * Data about the entity itself. Exactly one of the following fields must be
     * present (unless the entity is being deleted).
     * </pre>
     *
     * <code>optional .transit_realtime.TripUpdate trip_update = 3;</code>
     */
    public Builder setTripUpdate(
        sen.khyber.subway.client.proto.TripUpdate.Builder builderForValue) {
      if (tripUpdateBuilder_ == null) {
        tripUpdate_ = builderForValue.build();
        onChanged();
      } else {
        tripUpdateBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <pre>
     * Data about the entity itself. Exactly one of the following fields must be
     * present (unless the entity is being deleted).
     * </pre>
     *
     * <code>optional .transit_realtime.TripUpdate trip_update = 3;</code>
     */
    public Builder mergeTripUpdate(sen.khyber.subway.client.proto.TripUpdate value) {
      if (tripUpdateBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004) &&
            tripUpdate_ != null &&
            tripUpdate_ != sen.khyber.subway.client.proto.TripUpdate.getDefaultInstance()) {
          tripUpdate_ =
            sen.khyber.subway.client.proto.TripUpdate.newBuilder(tripUpdate_).mergeFrom(value).buildPartial();
        } else {
          tripUpdate_ = value;
        }
        onChanged();
      } else {
        tripUpdateBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <pre>
     * Data about the entity itself. Exactly one of the following fields must be
     * present (unless the entity is being deleted).
     * </pre>
     *
     * <code>optional .transit_realtime.TripUpdate trip_update = 3;</code>
     */
    public Builder clearTripUpdate() {
      if (tripUpdateBuilder_ == null) {
        tripUpdate_ = null;
        onChanged();
      } else {
        tripUpdateBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }
    /**
     * <pre>
     * Data about the entity itself. Exactly one of the following fields must be
     * present (unless the entity is being deleted).
     * </pre>
     *
     * <code>optional .transit_realtime.TripUpdate trip_update = 3;</code>
     */
    public sen.khyber.subway.client.proto.TripUpdate.Builder getTripUpdateBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getTripUpdateFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Data about the entity itself. Exactly one of the following fields must be
     * present (unless the entity is being deleted).
     * </pre>
     *
     * <code>optional .transit_realtime.TripUpdate trip_update = 3;</code>
     */
    public sen.khyber.subway.client.proto.TripUpdateOrBuilder getTripUpdateOrBuilder() {
      if (tripUpdateBuilder_ != null) {
        return tripUpdateBuilder_.getMessageOrBuilder();
      } else {
        return tripUpdate_ == null ?
            sen.khyber.subway.client.proto.TripUpdate.getDefaultInstance() : tripUpdate_;
      }
    }
    /**
     * <pre>
     * Data about the entity itself. Exactly one of the following fields must be
     * present (unless the entity is being deleted).
     * </pre>
     *
     * <code>optional .transit_realtime.TripUpdate trip_update = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        sen.khyber.subway.client.proto.TripUpdate, sen.khyber.subway.client.proto.TripUpdate.Builder, sen.khyber.subway.client.proto.TripUpdateOrBuilder> 
        getTripUpdateFieldBuilder() {
      if (tripUpdateBuilder_ == null) {
        tripUpdateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            sen.khyber.subway.client.proto.TripUpdate, sen.khyber.subway.client.proto.TripUpdate.Builder, sen.khyber.subway.client.proto.TripUpdateOrBuilder>(
                getTripUpdate(),
                getParentForChildren(),
                isClean());
        tripUpdate_ = null;
      }
      return tripUpdateBuilder_;
    }

    private sen.khyber.subway.client.proto.VehiclePosition vehicle_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        sen.khyber.subway.client.proto.VehiclePosition, sen.khyber.subway.client.proto.VehiclePosition.Builder, sen.khyber.subway.client.proto.VehiclePositionOrBuilder> vehicleBuilder_;
    /**
     * <code>optional .transit_realtime.VehiclePosition vehicle = 4;</code>
     */
    public boolean hasVehicle() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .transit_realtime.VehiclePosition vehicle = 4;</code>
     */
    public sen.khyber.subway.client.proto.VehiclePosition getVehicle() {
      if (vehicleBuilder_ == null) {
        return vehicle_ == null ? sen.khyber.subway.client.proto.VehiclePosition.getDefaultInstance() : vehicle_;
      } else {
        return vehicleBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .transit_realtime.VehiclePosition vehicle = 4;</code>
     */
    public Builder setVehicle(sen.khyber.subway.client.proto.VehiclePosition value) {
      if (vehicleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        vehicle_ = value;
        onChanged();
      } else {
        vehicleBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .transit_realtime.VehiclePosition vehicle = 4;</code>
     */
    public Builder setVehicle(
        sen.khyber.subway.client.proto.VehiclePosition.Builder builderForValue) {
      if (vehicleBuilder_ == null) {
        vehicle_ = builderForValue.build();
        onChanged();
      } else {
        vehicleBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .transit_realtime.VehiclePosition vehicle = 4;</code>
     */
    public Builder mergeVehicle(sen.khyber.subway.client.proto.VehiclePosition value) {
      if (vehicleBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008) &&
            vehicle_ != null &&
            vehicle_ != sen.khyber.subway.client.proto.VehiclePosition.getDefaultInstance()) {
          vehicle_ =
            sen.khyber.subway.client.proto.VehiclePosition.newBuilder(vehicle_).mergeFrom(value).buildPartial();
        } else {
          vehicle_ = value;
        }
        onChanged();
      } else {
        vehicleBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .transit_realtime.VehiclePosition vehicle = 4;</code>
     */
    public Builder clearVehicle() {
      if (vehicleBuilder_ == null) {
        vehicle_ = null;
        onChanged();
      } else {
        vehicleBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }
    /**
     * <code>optional .transit_realtime.VehiclePosition vehicle = 4;</code>
     */
    public sen.khyber.subway.client.proto.VehiclePosition.Builder getVehicleBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getVehicleFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .transit_realtime.VehiclePosition vehicle = 4;</code>
     */
    public sen.khyber.subway.client.proto.VehiclePositionOrBuilder getVehicleOrBuilder() {
      if (vehicleBuilder_ != null) {
        return vehicleBuilder_.getMessageOrBuilder();
      } else {
        return vehicle_ == null ?
            sen.khyber.subway.client.proto.VehiclePosition.getDefaultInstance() : vehicle_;
      }
    }
    /**
     * <code>optional .transit_realtime.VehiclePosition vehicle = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        sen.khyber.subway.client.proto.VehiclePosition, sen.khyber.subway.client.proto.VehiclePosition.Builder, sen.khyber.subway.client.proto.VehiclePositionOrBuilder> 
        getVehicleFieldBuilder() {
      if (vehicleBuilder_ == null) {
        vehicleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            sen.khyber.subway.client.proto.VehiclePosition, sen.khyber.subway.client.proto.VehiclePosition.Builder, sen.khyber.subway.client.proto.VehiclePositionOrBuilder>(
                getVehicle(),
                getParentForChildren(),
                isClean());
        vehicle_ = null;
      }
      return vehicleBuilder_;
    }

    private sen.khyber.subway.client.proto.Alert alert_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        sen.khyber.subway.client.proto.Alert, sen.khyber.subway.client.proto.Alert.Builder, sen.khyber.subway.client.proto.AlertOrBuilder> alertBuilder_;
    /**
     * <code>optional .transit_realtime.Alert alert = 5;</code>
     */
    public boolean hasAlert() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .transit_realtime.Alert alert = 5;</code>
     */
    public sen.khyber.subway.client.proto.Alert getAlert() {
      if (alertBuilder_ == null) {
        return alert_ == null ? sen.khyber.subway.client.proto.Alert.getDefaultInstance() : alert_;
      } else {
        return alertBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .transit_realtime.Alert alert = 5;</code>
     */
    public Builder setAlert(sen.khyber.subway.client.proto.Alert value) {
      if (alertBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        alert_ = value;
        onChanged();
      } else {
        alertBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <code>optional .transit_realtime.Alert alert = 5;</code>
     */
    public Builder setAlert(
        sen.khyber.subway.client.proto.Alert.Builder builderForValue) {
      if (alertBuilder_ == null) {
        alert_ = builderForValue.build();
        onChanged();
      } else {
        alertBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <code>optional .transit_realtime.Alert alert = 5;</code>
     */
    public Builder mergeAlert(sen.khyber.subway.client.proto.Alert value) {
      if (alertBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010) &&
            alert_ != null &&
            alert_ != sen.khyber.subway.client.proto.Alert.getDefaultInstance()) {
          alert_ =
            sen.khyber.subway.client.proto.Alert.newBuilder(alert_).mergeFrom(value).buildPartial();
        } else {
          alert_ = value;
        }
        onChanged();
      } else {
        alertBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <code>optional .transit_realtime.Alert alert = 5;</code>
     */
    public Builder clearAlert() {
      if (alertBuilder_ == null) {
        alert_ = null;
        onChanged();
      } else {
        alertBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }
    /**
     * <code>optional .transit_realtime.Alert alert = 5;</code>
     */
    public sen.khyber.subway.client.proto.Alert.Builder getAlertBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getAlertFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .transit_realtime.Alert alert = 5;</code>
     */
    public sen.khyber.subway.client.proto.AlertOrBuilder getAlertOrBuilder() {
      if (alertBuilder_ != null) {
        return alertBuilder_.getMessageOrBuilder();
      } else {
        return alert_ == null ?
            sen.khyber.subway.client.proto.Alert.getDefaultInstance() : alert_;
      }
    }
    /**
     * <code>optional .transit_realtime.Alert alert = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        sen.khyber.subway.client.proto.Alert, sen.khyber.subway.client.proto.Alert.Builder, sen.khyber.subway.client.proto.AlertOrBuilder> 
        getAlertFieldBuilder() {
      if (alertBuilder_ == null) {
        alertBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            sen.khyber.subway.client.proto.Alert, sen.khyber.subway.client.proto.Alert.Builder, sen.khyber.subway.client.proto.AlertOrBuilder>(
                getAlert(),
                getParentForChildren(),
                isClean());
        alert_ = null;
      }
      return alertBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:transit_realtime.FeedEntity)
  }

  // @@protoc_insertion_point(class_scope:transit_realtime.FeedEntity)
  private static final sen.khyber.subway.client.proto.FeedEntity DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sen.khyber.subway.client.proto.FeedEntity();
  }

  public static sen.khyber.subway.client.proto.FeedEntity getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<FeedEntity>
      PARSER = new com.google.protobuf.AbstractParser<FeedEntity>() {
    public FeedEntity parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new FeedEntity(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FeedEntity> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FeedEntity> getParserForType() {
    return PARSER;
  }

  public sen.khyber.subway.client.proto.FeedEntity getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

