// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gtfs-realtime.proto

package sen.khyber.subway.client.proto;

public interface TranslatedStringOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transit_realtime.TranslatedString)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * At least one translation must be provided.
   * </pre>
   *
   * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
   */
  java.util.List<sen.khyber.subway.client.proto.TranslatedString.Translation> 
      getTranslationList();
  /**
   * <pre>
   * At least one translation must be provided.
   * </pre>
   *
   * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
   */
  sen.khyber.subway.client.proto.TranslatedString.Translation getTranslation(int index);
  /**
   * <pre>
   * At least one translation must be provided.
   * </pre>
   *
   * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
   */
  int getTranslationCount();
  /**
   * <pre>
   * At least one translation must be provided.
   * </pre>
   *
   * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
   */
  java.util.List<? extends sen.khyber.subway.client.proto.TranslatedString.TranslationOrBuilder> 
      getTranslationOrBuilderList();
  /**
   * <pre>
   * At least one translation must be provided.
   * </pre>
   *
   * <code>repeated .transit_realtime.TranslatedString.Translation translation = 1;</code>
   */
  sen.khyber.subway.client.proto.TranslatedString.TranslationOrBuilder getTranslationOrBuilder(
      int index);
}
