// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gtfs-realtime.proto

package sen.khyber.subway.client.proto;

/**
 * <pre>
 * Realtime positioning information for a given vehicle.
 * </pre>
 *
 * Protobuf type {@code transit_realtime.VehiclePosition}
 */
public  final class VehiclePosition extends
    com.google.protobuf.GeneratedMessageV3.ExtendableMessage<
      VehiclePosition> implements
    // @@protoc_insertion_point(message_implements:transit_realtime.VehiclePosition)
    VehiclePositionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VehiclePosition.newBuilder() to construct.
  private VehiclePosition(com.google.protobuf.GeneratedMessageV3.ExtendableBuilder<sen.khyber.subway.client.proto.VehiclePosition, ?> builder) {
    super(builder);
  }
  private VehiclePosition() {
    currentStopSequence_ = 0;
    stopId_ = "";
    currentStatus_ = 2;
    timestamp_ = 0L;
    congestionLevel_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private VehiclePosition(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            sen.khyber.subway.client.proto.TripDescriptor.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              subBuilder = trip_.toBuilder();
            }
            trip_ = input.readMessage(sen.khyber.subway.client.proto.TripDescriptor.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(trip_);
              trip_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 18: {
            sen.khyber.subway.client.proto.Position.Builder subBuilder = null;
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
              subBuilder = position_.toBuilder();
            }
            position_ = input.readMessage(sen.khyber.subway.client.proto.Position.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(position_);
              position_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000004;
            break;
          }
          case 24: {
            bitField0_ |= 0x00000008;
            currentStopSequence_ = input.readUInt32();
            break;
          }
          case 32: {
            int rawValue = input.readEnum();
            sen.khyber.subway.client.proto.VehiclePosition.VehicleStopStatus value = sen.khyber.subway.client.proto.VehiclePosition.VehicleStopStatus.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(4, rawValue);
            } else {
              bitField0_ |= 0x00000020;
              currentStatus_ = rawValue;
            }
            break;
          }
          case 40: {
            bitField0_ |= 0x00000040;
            timestamp_ = input.readUInt64();
            break;
          }
          case 48: {
            int rawValue = input.readEnum();
            sen.khyber.subway.client.proto.VehiclePosition.CongestionLevel value = sen.khyber.subway.client.proto.VehiclePosition.CongestionLevel.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(6, rawValue);
            } else {
              bitField0_ |= 0x00000080;
              congestionLevel_ = rawValue;
            }
            break;
          }
          case 58: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000010;
            stopId_ = bs;
            break;
          }
          case 66: {
            sen.khyber.subway.client.proto.VehicleDescriptor.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
              subBuilder = vehicle_.toBuilder();
            }
            vehicle_ = input.readMessage(sen.khyber.subway.client.proto.VehicleDescriptor.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(vehicle_);
              vehicle_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sen.khyber.subway.client.proto.GtfsRealtime.internal_static_transit_realtime_VehiclePosition_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sen.khyber.subway.client.proto.GtfsRealtime.internal_static_transit_realtime_VehiclePosition_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sen.khyber.subway.client.proto.VehiclePosition.class, sen.khyber.subway.client.proto.VehiclePosition.Builder.class);
  }

  /**
   * Protobuf enum {@code transit_realtime.VehiclePosition.VehicleStopStatus}
   */
  public enum VehicleStopStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * The vehicle is just about to arrive at the stop (on a stop
     * display, the vehicle symbol typically flashes).
     * </pre>
     *
     * <code>INCOMING_AT = 0;</code>
     */
    INCOMING_AT(0),
    /**
     * <pre>
     * The vehicle is standing at the stop.
     * </pre>
     *
     * <code>STOPPED_AT = 1;</code>
     */
    STOPPED_AT(1),
    /**
     * <pre>
     * The vehicle has departed and is in transit to the next stop.
     * </pre>
     *
     * <code>IN_TRANSIT_TO = 2;</code>
     */
    IN_TRANSIT_TO(2),
    ;

    /**
     * <pre>
     * The vehicle is just about to arrive at the stop (on a stop
     * display, the vehicle symbol typically flashes).
     * </pre>
     *
     * <code>INCOMING_AT = 0;</code>
     */
    public static final int INCOMING_AT_VALUE = 0;
    /**
     * <pre>
     * The vehicle is standing at the stop.
     * </pre>
     *
     * <code>STOPPED_AT = 1;</code>
     */
    public static final int STOPPED_AT_VALUE = 1;
    /**
     * <pre>
     * The vehicle has departed and is in transit to the next stop.
     * </pre>
     *
     * <code>IN_TRANSIT_TO = 2;</code>
     */
    public static final int IN_TRANSIT_TO_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static VehicleStopStatus valueOf(int value) {
      return forNumber(value);
    }

    public static VehicleStopStatus forNumber(int value) {
      switch (value) {
        case 0: return INCOMING_AT;
        case 1: return STOPPED_AT;
        case 2: return IN_TRANSIT_TO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<VehicleStopStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        VehicleStopStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<VehicleStopStatus>() {
            public VehicleStopStatus findValueByNumber(int number) {
              return VehicleStopStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return sen.khyber.subway.client.proto.VehiclePosition.getDescriptor().getEnumTypes().get(0);
    }

    private static final VehicleStopStatus[] VALUES = values();

    public static VehicleStopStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private VehicleStopStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:transit_realtime.VehiclePosition.VehicleStopStatus)
  }

  /**
   * <pre>
   * Congestion level that is affecting this vehicle.
   * </pre>
   *
   * Protobuf enum {@code transit_realtime.VehiclePosition.CongestionLevel}
   */
  public enum CongestionLevel
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_CONGESTION_LEVEL = 0;</code>
     */
    UNKNOWN_CONGESTION_LEVEL(0),
    /**
     * <code>RUNNING_SMOOTHLY = 1;</code>
     */
    RUNNING_SMOOTHLY(1),
    /**
     * <code>STOP_AND_GO = 2;</code>
     */
    STOP_AND_GO(2),
    /**
     * <code>CONGESTION = 3;</code>
     */
    CONGESTION(3),
    /**
     * <pre>
     * People leaving their cars.
     * </pre>
     *
     * <code>SEVERE_CONGESTION = 4;</code>
     */
    SEVERE_CONGESTION(4),
    ;

    /**
     * <code>UNKNOWN_CONGESTION_LEVEL = 0;</code>
     */
    public static final int UNKNOWN_CONGESTION_LEVEL_VALUE = 0;
    /**
     * <code>RUNNING_SMOOTHLY = 1;</code>
     */
    public static final int RUNNING_SMOOTHLY_VALUE = 1;
    /**
     * <code>STOP_AND_GO = 2;</code>
     */
    public static final int STOP_AND_GO_VALUE = 2;
    /**
     * <code>CONGESTION = 3;</code>
     */
    public static final int CONGESTION_VALUE = 3;
    /**
     * <pre>
     * People leaving their cars.
     * </pre>
     *
     * <code>SEVERE_CONGESTION = 4;</code>
     */
    public static final int SEVERE_CONGESTION_VALUE = 4;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CongestionLevel valueOf(int value) {
      return forNumber(value);
    }

    public static CongestionLevel forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_CONGESTION_LEVEL;
        case 1: return RUNNING_SMOOTHLY;
        case 2: return STOP_AND_GO;
        case 3: return CONGESTION;
        case 4: return SEVERE_CONGESTION;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CongestionLevel>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CongestionLevel> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CongestionLevel>() {
            public CongestionLevel findValueByNumber(int number) {
              return CongestionLevel.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return sen.khyber.subway.client.proto.VehiclePosition.getDescriptor().getEnumTypes().get(1);
    }

    private static final CongestionLevel[] VALUES = values();

    public static CongestionLevel valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CongestionLevel(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:transit_realtime.VehiclePosition.CongestionLevel)
  }

  private int bitField0_;
  public static final int TRIP_FIELD_NUMBER = 1;
  private sen.khyber.subway.client.proto.TripDescriptor trip_;
  /**
   * <pre>
   * The Trip that this vehicle is serving.
   * Can be empty or partial if the vehicle can not be identified with a given
   * trip instance.
   * </pre>
   *
   * <code>optional .transit_realtime.TripDescriptor trip = 1;</code>
   */
  public boolean hasTrip() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <pre>
   * The Trip that this vehicle is serving.
   * Can be empty or partial if the vehicle can not be identified with a given
   * trip instance.
   * </pre>
   *
   * <code>optional .transit_realtime.TripDescriptor trip = 1;</code>
   */
  public sen.khyber.subway.client.proto.TripDescriptor getTrip() {
    return trip_ == null ? sen.khyber.subway.client.proto.TripDescriptor.getDefaultInstance() : trip_;
  }
  /**
   * <pre>
   * The Trip that this vehicle is serving.
   * Can be empty or partial if the vehicle can not be identified with a given
   * trip instance.
   * </pre>
   *
   * <code>optional .transit_realtime.TripDescriptor trip = 1;</code>
   */
  public sen.khyber.subway.client.proto.TripDescriptorOrBuilder getTripOrBuilder() {
    return trip_ == null ? sen.khyber.subway.client.proto.TripDescriptor.getDefaultInstance() : trip_;
  }

  public static final int VEHICLE_FIELD_NUMBER = 8;
  private sen.khyber.subway.client.proto.VehicleDescriptor vehicle_;
  /**
   * <pre>
   * Additional information on the vehicle that is serving this trip.
   * </pre>
   *
   * <code>optional .transit_realtime.VehicleDescriptor vehicle = 8;</code>
   */
  public boolean hasVehicle() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <pre>
   * Additional information on the vehicle that is serving this trip.
   * </pre>
   *
   * <code>optional .transit_realtime.VehicleDescriptor vehicle = 8;</code>
   */
  public sen.khyber.subway.client.proto.VehicleDescriptor getVehicle() {
    return vehicle_ == null ? sen.khyber.subway.client.proto.VehicleDescriptor.getDefaultInstance() : vehicle_;
  }
  /**
   * <pre>
   * Additional information on the vehicle that is serving this trip.
   * </pre>
   *
   * <code>optional .transit_realtime.VehicleDescriptor vehicle = 8;</code>
   */
  public sen.khyber.subway.client.proto.VehicleDescriptorOrBuilder getVehicleOrBuilder() {
    return vehicle_ == null ? sen.khyber.subway.client.proto.VehicleDescriptor.getDefaultInstance() : vehicle_;
  }

  public static final int POSITION_FIELD_NUMBER = 2;
  private sen.khyber.subway.client.proto.Position position_;
  /**
   * <pre>
   * Current position of this vehicle.
   * </pre>
   *
   * <code>optional .transit_realtime.Position position = 2;</code>
   */
  public boolean hasPosition() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <pre>
   * Current position of this vehicle.
   * </pre>
   *
   * <code>optional .transit_realtime.Position position = 2;</code>
   */
  public sen.khyber.subway.client.proto.Position getPosition() {
    return position_ == null ? sen.khyber.subway.client.proto.Position.getDefaultInstance() : position_;
  }
  /**
   * <pre>
   * Current position of this vehicle.
   * </pre>
   *
   * <code>optional .transit_realtime.Position position = 2;</code>
   */
  public sen.khyber.subway.client.proto.PositionOrBuilder getPositionOrBuilder() {
    return position_ == null ? sen.khyber.subway.client.proto.Position.getDefaultInstance() : position_;
  }

  public static final int CURRENT_STOP_SEQUENCE_FIELD_NUMBER = 3;
  private int currentStopSequence_;
  /**
   * <pre>
   * The stop sequence index of the current stop. The meaning of
   * current_stop_sequence (i.e., the stop that it refers to) is determined by
   * current_status.
   * If current_status is missing IN_TRANSIT_TO is assumed.
   * </pre>
   *
   * <code>optional uint32 current_stop_sequence = 3;</code>
   */
  public boolean hasCurrentStopSequence() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <pre>
   * The stop sequence index of the current stop. The meaning of
   * current_stop_sequence (i.e., the stop that it refers to) is determined by
   * current_status.
   * If current_status is missing IN_TRANSIT_TO is assumed.
   * </pre>
   *
   * <code>optional uint32 current_stop_sequence = 3;</code>
   */
  public int getCurrentStopSequence() {
    return currentStopSequence_;
  }

  public static final int STOP_ID_FIELD_NUMBER = 7;
  private volatile java.lang.Object stopId_;
  /**
   * <pre>
   * Identifies the current stop. The value must be the same as in stops.txt in
   * the corresponding GTFS feed.
   * </pre>
   *
   * <code>optional string stop_id = 7;</code>
   */
  public boolean hasStopId() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <pre>
   * Identifies the current stop. The value must be the same as in stops.txt in
   * the corresponding GTFS feed.
   * </pre>
   *
   * <code>optional string stop_id = 7;</code>
   */
  public java.lang.String getStopId() {
    java.lang.Object ref = stopId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        stopId_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * Identifies the current stop. The value must be the same as in stops.txt in
   * the corresponding GTFS feed.
   * </pre>
   *
   * <code>optional string stop_id = 7;</code>
   */
  public com.google.protobuf.ByteString
      getStopIdBytes() {
    java.lang.Object ref = stopId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stopId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CURRENT_STATUS_FIELD_NUMBER = 4;
  private int currentStatus_;
  /**
   * <pre>
   * The exact status of the vehicle with respect to the current stop.
   * Ignored if current_stop_sequence is missing.
   * </pre>
   *
   * <code>optional .transit_realtime.VehiclePosition.VehicleStopStatus current_status = 4 [default = IN_TRANSIT_TO];</code>
   */
  public boolean hasCurrentStatus() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <pre>
   * The exact status of the vehicle with respect to the current stop.
   * Ignored if current_stop_sequence is missing.
   * </pre>
   *
   * <code>optional .transit_realtime.VehiclePosition.VehicleStopStatus current_status = 4 [default = IN_TRANSIT_TO];</code>
   */
  public sen.khyber.subway.client.proto.VehiclePosition.VehicleStopStatus getCurrentStatus() {
    sen.khyber.subway.client.proto.VehiclePosition.VehicleStopStatus result = sen.khyber.subway.client.proto.VehiclePosition.VehicleStopStatus.valueOf(currentStatus_);
    return result == null ? sen.khyber.subway.client.proto.VehiclePosition.VehicleStopStatus.IN_TRANSIT_TO : result;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 5;
  private long timestamp_;
  /**
   * <pre>
   * Moment at which the vehicle's position was measured. In POSIX time
   * (i.e., number of seconds since January 1st 1970 00:00:00 UTC).
   * </pre>
   *
   * <code>optional uint64 timestamp = 5;</code>
   */
  public boolean hasTimestamp() {
    return ((bitField0_ & 0x00000040) == 0x00000040);
  }
  /**
   * <pre>
   * Moment at which the vehicle's position was measured. In POSIX time
   * (i.e., number of seconds since January 1st 1970 00:00:00 UTC).
   * </pre>
   *
   * <code>optional uint64 timestamp = 5;</code>
   */
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int CONGESTION_LEVEL_FIELD_NUMBER = 6;
  private int congestionLevel_;
  /**
   * <code>optional .transit_realtime.VehiclePosition.CongestionLevel congestion_level = 6;</code>
   */
  public boolean hasCongestionLevel() {
    return ((bitField0_ & 0x00000080) == 0x00000080);
  }
  /**
   * <code>optional .transit_realtime.VehiclePosition.CongestionLevel congestion_level = 6;</code>
   */
  public sen.khyber.subway.client.proto.VehiclePosition.CongestionLevel getCongestionLevel() {
    sen.khyber.subway.client.proto.VehiclePosition.CongestionLevel result = sen.khyber.subway.client.proto.VehiclePosition.CongestionLevel.valueOf(congestionLevel_);
    return result == null ? sen.khyber.subway.client.proto.VehiclePosition.CongestionLevel.UNKNOWN_CONGESTION_LEVEL : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (hasTrip()) {
      if (!getTrip().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    if (hasVehicle()) {
      if (!getVehicle().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    if (hasPosition()) {
      if (!getPosition().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    if (!extensionsAreInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .ExtendableMessage<sen.khyber.subway.client.proto.VehiclePosition>.ExtensionWriter
        extensionWriter = newExtensionWriter();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeMessage(1, getTrip());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeMessage(2, getPosition());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeUInt32(3, currentStopSequence_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeEnum(4, currentStatus_);
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      output.writeUInt64(5, timestamp_);
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      output.writeEnum(6, congestionLevel_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, stopId_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeMessage(8, getVehicle());
    }
    extensionWriter.writeUntil(2000, output);
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTrip());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPosition());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, currentStopSequence_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, currentStatus_);
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(5, timestamp_);
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, congestionLevel_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, stopId_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getVehicle());
    }
    size += extensionsSerializedSize();
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sen.khyber.subway.client.proto.VehiclePosition)) {
      return super.equals(obj);
    }
    sen.khyber.subway.client.proto.VehiclePosition other = (sen.khyber.subway.client.proto.VehiclePosition) obj;

    boolean result = true;
    result = result && (hasTrip() == other.hasTrip());
    if (hasTrip()) {
      result = result && getTrip()
          .equals(other.getTrip());
    }
    result = result && (hasVehicle() == other.hasVehicle());
    if (hasVehicle()) {
      result = result && getVehicle()
          .equals(other.getVehicle());
    }
    result = result && (hasPosition() == other.hasPosition());
    if (hasPosition()) {
      result = result && getPosition()
          .equals(other.getPosition());
    }
    result = result && (hasCurrentStopSequence() == other.hasCurrentStopSequence());
    if (hasCurrentStopSequence()) {
      result = result && (getCurrentStopSequence()
          == other.getCurrentStopSequence());
    }
    result = result && (hasStopId() == other.hasStopId());
    if (hasStopId()) {
      result = result && getStopId()
          .equals(other.getStopId());
    }
    result = result && (hasCurrentStatus() == other.hasCurrentStatus());
    if (hasCurrentStatus()) {
      result = result && currentStatus_ == other.currentStatus_;
    }
    result = result && (hasTimestamp() == other.hasTimestamp());
    if (hasTimestamp()) {
      result = result && (getTimestamp()
          == other.getTimestamp());
    }
    result = result && (hasCongestionLevel() == other.hasCongestionLevel());
    if (hasCongestionLevel()) {
      result = result && congestionLevel_ == other.congestionLevel_;
    }
    result = result && unknownFields.equals(other.unknownFields);
    result = result &&
        getExtensionFields().equals(other.getExtensionFields());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTrip()) {
      hash = (37 * hash) + TRIP_FIELD_NUMBER;
      hash = (53 * hash) + getTrip().hashCode();
    }
    if (hasVehicle()) {
      hash = (37 * hash) + VEHICLE_FIELD_NUMBER;
      hash = (53 * hash) + getVehicle().hashCode();
    }
    if (hasPosition()) {
      hash = (37 * hash) + POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getPosition().hashCode();
    }
    if (hasCurrentStopSequence()) {
      hash = (37 * hash) + CURRENT_STOP_SEQUENCE_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentStopSequence();
    }
    if (hasStopId()) {
      hash = (37 * hash) + STOP_ID_FIELD_NUMBER;
      hash = (53 * hash) + getStopId().hashCode();
    }
    if (hasCurrentStatus()) {
      hash = (37 * hash) + CURRENT_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + currentStatus_;
    }
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
    }
    if (hasCongestionLevel()) {
      hash = (37 * hash) + CONGESTION_LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + congestionLevel_;
    }
    hash = hashFields(hash, getExtensionFields());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sen.khyber.subway.client.proto.VehiclePosition parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sen.khyber.subway.client.proto.VehiclePosition parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sen.khyber.subway.client.proto.VehiclePosition parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sen.khyber.subway.client.proto.VehiclePosition parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sen.khyber.subway.client.proto.VehiclePosition parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sen.khyber.subway.client.proto.VehiclePosition parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sen.khyber.subway.client.proto.VehiclePosition parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sen.khyber.subway.client.proto.VehiclePosition parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static sen.khyber.subway.client.proto.VehiclePosition parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static sen.khyber.subway.client.proto.VehiclePosition parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sen.khyber.subway.client.proto.VehiclePosition parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sen.khyber.subway.client.proto.VehiclePosition parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sen.khyber.subway.client.proto.VehiclePosition prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Realtime positioning information for a given vehicle.
   * </pre>
   *
   * Protobuf type {@code transit_realtime.VehiclePosition}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.ExtendableBuilder<
        sen.khyber.subway.client.proto.VehiclePosition, Builder> implements
      // @@protoc_insertion_point(builder_implements:transit_realtime.VehiclePosition)
      sen.khyber.subway.client.proto.VehiclePositionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sen.khyber.subway.client.proto.GtfsRealtime.internal_static_transit_realtime_VehiclePosition_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sen.khyber.subway.client.proto.GtfsRealtime.internal_static_transit_realtime_VehiclePosition_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sen.khyber.subway.client.proto.VehiclePosition.class, sen.khyber.subway.client.proto.VehiclePosition.Builder.class);
    }

    // Construct using sen.khyber.subway.client.proto.VehiclePosition.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTripFieldBuilder();
        getVehicleFieldBuilder();
        getPositionFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (tripBuilder_ == null) {
        trip_ = null;
      } else {
        tripBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (vehicleBuilder_ == null) {
        vehicle_ = null;
      } else {
        vehicleBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (positionBuilder_ == null) {
        position_ = null;
      } else {
        positionBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      currentStopSequence_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      stopId_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      currentStatus_ = 2;
      bitField0_ = (bitField0_ & ~0x00000020);
      timestamp_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000040);
      congestionLevel_ = 0;
      bitField0_ = (bitField0_ & ~0x00000080);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sen.khyber.subway.client.proto.GtfsRealtime.internal_static_transit_realtime_VehiclePosition_descriptor;
    }

    public sen.khyber.subway.client.proto.VehiclePosition getDefaultInstanceForType() {
      return sen.khyber.subway.client.proto.VehiclePosition.getDefaultInstance();
    }

    public sen.khyber.subway.client.proto.VehiclePosition build() {
      sen.khyber.subway.client.proto.VehiclePosition result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public sen.khyber.subway.client.proto.VehiclePosition buildPartial() {
      sen.khyber.subway.client.proto.VehiclePosition result = new sen.khyber.subway.client.proto.VehiclePosition(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      if (tripBuilder_ == null) {
        result.trip_ = trip_;
      } else {
        result.trip_ = tripBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      if (vehicleBuilder_ == null) {
        result.vehicle_ = vehicle_;
      } else {
        result.vehicle_ = vehicleBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      if (positionBuilder_ == null) {
        result.position_ = position_;
      } else {
        result.position_ = positionBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.currentStopSequence_ = currentStopSequence_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.stopId_ = stopId_;
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000020;
      }
      result.currentStatus_ = currentStatus_;
      if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
        to_bitField0_ |= 0x00000040;
      }
      result.timestamp_ = timestamp_;
      if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
        to_bitField0_ |= 0x00000080;
      }
      result.congestionLevel_ = congestionLevel_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public <Type> Builder setExtension(
        com.google.protobuf.GeneratedMessage.GeneratedExtension<
            sen.khyber.subway.client.proto.VehiclePosition, Type> extension,
        Type value) {
      return (Builder) super.setExtension(extension, value);
    }
    public <Type> Builder setExtension(
        com.google.protobuf.GeneratedMessage.GeneratedExtension<
            sen.khyber.subway.client.proto.VehiclePosition, java.util.List<Type>> extension,
        int index, Type value) {
      return (Builder) super.setExtension(extension, index, value);
    }
    public <Type> Builder addExtension(
        com.google.protobuf.GeneratedMessage.GeneratedExtension<
            sen.khyber.subway.client.proto.VehiclePosition, java.util.List<Type>> extension,
        Type value) {
      return (Builder) super.addExtension(extension, value);
    }
    public <Type> Builder clearExtension(
        com.google.protobuf.GeneratedMessage.GeneratedExtension<
            sen.khyber.subway.client.proto.VehiclePosition, ?> extension) {
      return (Builder) super.clearExtension(extension);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sen.khyber.subway.client.proto.VehiclePosition) {
        return mergeFrom((sen.khyber.subway.client.proto.VehiclePosition)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sen.khyber.subway.client.proto.VehiclePosition other) {
      if (other == sen.khyber.subway.client.proto.VehiclePosition.getDefaultInstance()) return this;
      if (other.hasTrip()) {
        mergeTrip(other.getTrip());
      }
      if (other.hasVehicle()) {
        mergeVehicle(other.getVehicle());
      }
      if (other.hasPosition()) {
        mergePosition(other.getPosition());
      }
      if (other.hasCurrentStopSequence()) {
        setCurrentStopSequence(other.getCurrentStopSequence());
      }
      if (other.hasStopId()) {
        bitField0_ |= 0x00000010;
        stopId_ = other.stopId_;
        onChanged();
      }
      if (other.hasCurrentStatus()) {
        setCurrentStatus(other.getCurrentStatus());
      }
      if (other.hasTimestamp()) {
        setTimestamp(other.getTimestamp());
      }
      if (other.hasCongestionLevel()) {
        setCongestionLevel(other.getCongestionLevel());
      }
      this.mergeExtensionFields(other);
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      if (hasTrip()) {
        if (!getTrip().isInitialized()) {
          return false;
        }
      }
      if (hasVehicle()) {
        if (!getVehicle().isInitialized()) {
          return false;
        }
      }
      if (hasPosition()) {
        if (!getPosition().isInitialized()) {
          return false;
        }
      }
      if (!extensionsAreInitialized()) {
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      sen.khyber.subway.client.proto.VehiclePosition parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (sen.khyber.subway.client.proto.VehiclePosition) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private sen.khyber.subway.client.proto.TripDescriptor trip_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        sen.khyber.subway.client.proto.TripDescriptor, sen.khyber.subway.client.proto.TripDescriptor.Builder, sen.khyber.subway.client.proto.TripDescriptorOrBuilder> tripBuilder_;
    /**
     * <pre>
     * The Trip that this vehicle is serving.
     * Can be empty or partial if the vehicle can not be identified with a given
     * trip instance.
     * </pre>
     *
     * <code>optional .transit_realtime.TripDescriptor trip = 1;</code>
     */
    public boolean hasTrip() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * The Trip that this vehicle is serving.
     * Can be empty or partial if the vehicle can not be identified with a given
     * trip instance.
     * </pre>
     *
     * <code>optional .transit_realtime.TripDescriptor trip = 1;</code>
     */
    public sen.khyber.subway.client.proto.TripDescriptor getTrip() {
      if (tripBuilder_ == null) {
        return trip_ == null ? sen.khyber.subway.client.proto.TripDescriptor.getDefaultInstance() : trip_;
      } else {
        return tripBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The Trip that this vehicle is serving.
     * Can be empty or partial if the vehicle can not be identified with a given
     * trip instance.
     * </pre>
     *
     * <code>optional .transit_realtime.TripDescriptor trip = 1;</code>
     */
    public Builder setTrip(sen.khyber.subway.client.proto.TripDescriptor value) {
      if (tripBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        trip_ = value;
        onChanged();
      } else {
        tripBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * The Trip that this vehicle is serving.
     * Can be empty or partial if the vehicle can not be identified with a given
     * trip instance.
     * </pre>
     *
     * <code>optional .transit_realtime.TripDescriptor trip = 1;</code>
     */
    public Builder setTrip(
        sen.khyber.subway.client.proto.TripDescriptor.Builder builderForValue) {
      if (tripBuilder_ == null) {
        trip_ = builderForValue.build();
        onChanged();
      } else {
        tripBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * The Trip that this vehicle is serving.
     * Can be empty or partial if the vehicle can not be identified with a given
     * trip instance.
     * </pre>
     *
     * <code>optional .transit_realtime.TripDescriptor trip = 1;</code>
     */
    public Builder mergeTrip(sen.khyber.subway.client.proto.TripDescriptor value) {
      if (tripBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            trip_ != null &&
            trip_ != sen.khyber.subway.client.proto.TripDescriptor.getDefaultInstance()) {
          trip_ =
            sen.khyber.subway.client.proto.TripDescriptor.newBuilder(trip_).mergeFrom(value).buildPartial();
        } else {
          trip_ = value;
        }
        onChanged();
      } else {
        tripBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * The Trip that this vehicle is serving.
     * Can be empty or partial if the vehicle can not be identified with a given
     * trip instance.
     * </pre>
     *
     * <code>optional .transit_realtime.TripDescriptor trip = 1;</code>
     */
    public Builder clearTrip() {
      if (tripBuilder_ == null) {
        trip_ = null;
        onChanged();
      } else {
        tripBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <pre>
     * The Trip that this vehicle is serving.
     * Can be empty or partial if the vehicle can not be identified with a given
     * trip instance.
     * </pre>
     *
     * <code>optional .transit_realtime.TripDescriptor trip = 1;</code>
     */
    public sen.khyber.subway.client.proto.TripDescriptor.Builder getTripBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getTripFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The Trip that this vehicle is serving.
     * Can be empty or partial if the vehicle can not be identified with a given
     * trip instance.
     * </pre>
     *
     * <code>optional .transit_realtime.TripDescriptor trip = 1;</code>
     */
    public sen.khyber.subway.client.proto.TripDescriptorOrBuilder getTripOrBuilder() {
      if (tripBuilder_ != null) {
        return tripBuilder_.getMessageOrBuilder();
      } else {
        return trip_ == null ?
            sen.khyber.subway.client.proto.TripDescriptor.getDefaultInstance() : trip_;
      }
    }
    /**
     * <pre>
     * The Trip that this vehicle is serving.
     * Can be empty or partial if the vehicle can not be identified with a given
     * trip instance.
     * </pre>
     *
     * <code>optional .transit_realtime.TripDescriptor trip = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        sen.khyber.subway.client.proto.TripDescriptor, sen.khyber.subway.client.proto.TripDescriptor.Builder, sen.khyber.subway.client.proto.TripDescriptorOrBuilder> 
        getTripFieldBuilder() {
      if (tripBuilder_ == null) {
        tripBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            sen.khyber.subway.client.proto.TripDescriptor, sen.khyber.subway.client.proto.TripDescriptor.Builder, sen.khyber.subway.client.proto.TripDescriptorOrBuilder>(
                getTrip(),
                getParentForChildren(),
                isClean());
        trip_ = null;
      }
      return tripBuilder_;
    }

    private sen.khyber.subway.client.proto.VehicleDescriptor vehicle_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        sen.khyber.subway.client.proto.VehicleDescriptor, sen.khyber.subway.client.proto.VehicleDescriptor.Builder, sen.khyber.subway.client.proto.VehicleDescriptorOrBuilder> vehicleBuilder_;
    /**
     * <pre>
     * Additional information on the vehicle that is serving this trip.
     * </pre>
     *
     * <code>optional .transit_realtime.VehicleDescriptor vehicle = 8;</code>
     */
    public boolean hasVehicle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * Additional information on the vehicle that is serving this trip.
     * </pre>
     *
     * <code>optional .transit_realtime.VehicleDescriptor vehicle = 8;</code>
     */
    public sen.khyber.subway.client.proto.VehicleDescriptor getVehicle() {
      if (vehicleBuilder_ == null) {
        return vehicle_ == null ? sen.khyber.subway.client.proto.VehicleDescriptor.getDefaultInstance() : vehicle_;
      } else {
        return vehicleBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Additional information on the vehicle that is serving this trip.
     * </pre>
     *
     * <code>optional .transit_realtime.VehicleDescriptor vehicle = 8;</code>
     */
    public Builder setVehicle(sen.khyber.subway.client.proto.VehicleDescriptor value) {
      if (vehicleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        vehicle_ = value;
        onChanged();
      } else {
        vehicleBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <pre>
     * Additional information on the vehicle that is serving this trip.
     * </pre>
     *
     * <code>optional .transit_realtime.VehicleDescriptor vehicle = 8;</code>
     */
    public Builder setVehicle(
        sen.khyber.subway.client.proto.VehicleDescriptor.Builder builderForValue) {
      if (vehicleBuilder_ == null) {
        vehicle_ = builderForValue.build();
        onChanged();
      } else {
        vehicleBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <pre>
     * Additional information on the vehicle that is serving this trip.
     * </pre>
     *
     * <code>optional .transit_realtime.VehicleDescriptor vehicle = 8;</code>
     */
    public Builder mergeVehicle(sen.khyber.subway.client.proto.VehicleDescriptor value) {
      if (vehicleBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            vehicle_ != null &&
            vehicle_ != sen.khyber.subway.client.proto.VehicleDescriptor.getDefaultInstance()) {
          vehicle_ =
            sen.khyber.subway.client.proto.VehicleDescriptor.newBuilder(vehicle_).mergeFrom(value).buildPartial();
        } else {
          vehicle_ = value;
        }
        onChanged();
      } else {
        vehicleBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <pre>
     * Additional information on the vehicle that is serving this trip.
     * </pre>
     *
     * <code>optional .transit_realtime.VehicleDescriptor vehicle = 8;</code>
     */
    public Builder clearVehicle() {
      if (vehicleBuilder_ == null) {
        vehicle_ = null;
        onChanged();
      } else {
        vehicleBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <pre>
     * Additional information on the vehicle that is serving this trip.
     * </pre>
     *
     * <code>optional .transit_realtime.VehicleDescriptor vehicle = 8;</code>
     */
    public sen.khyber.subway.client.proto.VehicleDescriptor.Builder getVehicleBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getVehicleFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Additional information on the vehicle that is serving this trip.
     * </pre>
     *
     * <code>optional .transit_realtime.VehicleDescriptor vehicle = 8;</code>
     */
    public sen.khyber.subway.client.proto.VehicleDescriptorOrBuilder getVehicleOrBuilder() {
      if (vehicleBuilder_ != null) {
        return vehicleBuilder_.getMessageOrBuilder();
      } else {
        return vehicle_ == null ?
            sen.khyber.subway.client.proto.VehicleDescriptor.getDefaultInstance() : vehicle_;
      }
    }
    /**
     * <pre>
     * Additional information on the vehicle that is serving this trip.
     * </pre>
     *
     * <code>optional .transit_realtime.VehicleDescriptor vehicle = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        sen.khyber.subway.client.proto.VehicleDescriptor, sen.khyber.subway.client.proto.VehicleDescriptor.Builder, sen.khyber.subway.client.proto.VehicleDescriptorOrBuilder> 
        getVehicleFieldBuilder() {
      if (vehicleBuilder_ == null) {
        vehicleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            sen.khyber.subway.client.proto.VehicleDescriptor, sen.khyber.subway.client.proto.VehicleDescriptor.Builder, sen.khyber.subway.client.proto.VehicleDescriptorOrBuilder>(
                getVehicle(),
                getParentForChildren(),
                isClean());
        vehicle_ = null;
      }
      return vehicleBuilder_;
    }

    private sen.khyber.subway.client.proto.Position position_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        sen.khyber.subway.client.proto.Position, sen.khyber.subway.client.proto.Position.Builder, sen.khyber.subway.client.proto.PositionOrBuilder> positionBuilder_;
    /**
     * <pre>
     * Current position of this vehicle.
     * </pre>
     *
     * <code>optional .transit_realtime.Position position = 2;</code>
     */
    public boolean hasPosition() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * Current position of this vehicle.
     * </pre>
     *
     * <code>optional .transit_realtime.Position position = 2;</code>
     */
    public sen.khyber.subway.client.proto.Position getPosition() {
      if (positionBuilder_ == null) {
        return position_ == null ? sen.khyber.subway.client.proto.Position.getDefaultInstance() : position_;
      } else {
        return positionBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Current position of this vehicle.
     * </pre>
     *
     * <code>optional .transit_realtime.Position position = 2;</code>
     */
    public Builder setPosition(sen.khyber.subway.client.proto.Position value) {
      if (positionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        position_ = value;
        onChanged();
      } else {
        positionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <pre>
     * Current position of this vehicle.
     * </pre>
     *
     * <code>optional .transit_realtime.Position position = 2;</code>
     */
    public Builder setPosition(
        sen.khyber.subway.client.proto.Position.Builder builderForValue) {
      if (positionBuilder_ == null) {
        position_ = builderForValue.build();
        onChanged();
      } else {
        positionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <pre>
     * Current position of this vehicle.
     * </pre>
     *
     * <code>optional .transit_realtime.Position position = 2;</code>
     */
    public Builder mergePosition(sen.khyber.subway.client.proto.Position value) {
      if (positionBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004) &&
            position_ != null &&
            position_ != sen.khyber.subway.client.proto.Position.getDefaultInstance()) {
          position_ =
            sen.khyber.subway.client.proto.Position.newBuilder(position_).mergeFrom(value).buildPartial();
        } else {
          position_ = value;
        }
        onChanged();
      } else {
        positionBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <pre>
     * Current position of this vehicle.
     * </pre>
     *
     * <code>optional .transit_realtime.Position position = 2;</code>
     */
    public Builder clearPosition() {
      if (positionBuilder_ == null) {
        position_ = null;
        onChanged();
      } else {
        positionBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }
    /**
     * <pre>
     * Current position of this vehicle.
     * </pre>
     *
     * <code>optional .transit_realtime.Position position = 2;</code>
     */
    public sen.khyber.subway.client.proto.Position.Builder getPositionBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getPositionFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Current position of this vehicle.
     * </pre>
     *
     * <code>optional .transit_realtime.Position position = 2;</code>
     */
    public sen.khyber.subway.client.proto.PositionOrBuilder getPositionOrBuilder() {
      if (positionBuilder_ != null) {
        return positionBuilder_.getMessageOrBuilder();
      } else {
        return position_ == null ?
            sen.khyber.subway.client.proto.Position.getDefaultInstance() : position_;
      }
    }
    /**
     * <pre>
     * Current position of this vehicle.
     * </pre>
     *
     * <code>optional .transit_realtime.Position position = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        sen.khyber.subway.client.proto.Position, sen.khyber.subway.client.proto.Position.Builder, sen.khyber.subway.client.proto.PositionOrBuilder> 
        getPositionFieldBuilder() {
      if (positionBuilder_ == null) {
        positionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            sen.khyber.subway.client.proto.Position, sen.khyber.subway.client.proto.Position.Builder, sen.khyber.subway.client.proto.PositionOrBuilder>(
                getPosition(),
                getParentForChildren(),
                isClean());
        position_ = null;
      }
      return positionBuilder_;
    }

    private int currentStopSequence_ ;
    /**
     * <pre>
     * The stop sequence index of the current stop. The meaning of
     * current_stop_sequence (i.e., the stop that it refers to) is determined by
     * current_status.
     * If current_status is missing IN_TRANSIT_TO is assumed.
     * </pre>
     *
     * <code>optional uint32 current_stop_sequence = 3;</code>
     */
    public boolean hasCurrentStopSequence() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * The stop sequence index of the current stop. The meaning of
     * current_stop_sequence (i.e., the stop that it refers to) is determined by
     * current_status.
     * If current_status is missing IN_TRANSIT_TO is assumed.
     * </pre>
     *
     * <code>optional uint32 current_stop_sequence = 3;</code>
     */
    public int getCurrentStopSequence() {
      return currentStopSequence_;
    }
    /**
     * <pre>
     * The stop sequence index of the current stop. The meaning of
     * current_stop_sequence (i.e., the stop that it refers to) is determined by
     * current_status.
     * If current_status is missing IN_TRANSIT_TO is assumed.
     * </pre>
     *
     * <code>optional uint32 current_stop_sequence = 3;</code>
     */
    public Builder setCurrentStopSequence(int value) {
      bitField0_ |= 0x00000008;
      currentStopSequence_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The stop sequence index of the current stop. The meaning of
     * current_stop_sequence (i.e., the stop that it refers to) is determined by
     * current_status.
     * If current_status is missing IN_TRANSIT_TO is assumed.
     * </pre>
     *
     * <code>optional uint32 current_stop_sequence = 3;</code>
     */
    public Builder clearCurrentStopSequence() {
      bitField0_ = (bitField0_ & ~0x00000008);
      currentStopSequence_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object stopId_ = "";
    /**
     * <pre>
     * Identifies the current stop. The value must be the same as in stops.txt in
     * the corresponding GTFS feed.
     * </pre>
     *
     * <code>optional string stop_id = 7;</code>
     */
    public boolean hasStopId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     * Identifies the current stop. The value must be the same as in stops.txt in
     * the corresponding GTFS feed.
     * </pre>
     *
     * <code>optional string stop_id = 7;</code>
     */
    public java.lang.String getStopId() {
      java.lang.Object ref = stopId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          stopId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Identifies the current stop. The value must be the same as in stops.txt in
     * the corresponding GTFS feed.
     * </pre>
     *
     * <code>optional string stop_id = 7;</code>
     */
    public com.google.protobuf.ByteString
        getStopIdBytes() {
      java.lang.Object ref = stopId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stopId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Identifies the current stop. The value must be the same as in stops.txt in
     * the corresponding GTFS feed.
     * </pre>
     *
     * <code>optional string stop_id = 7;</code>
     */
    public Builder setStopId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      stopId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Identifies the current stop. The value must be the same as in stops.txt in
     * the corresponding GTFS feed.
     * </pre>
     *
     * <code>optional string stop_id = 7;</code>
     */
    public Builder clearStopId() {
      bitField0_ = (bitField0_ & ~0x00000010);
      stopId_ = getDefaultInstance().getStopId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Identifies the current stop. The value must be the same as in stops.txt in
     * the corresponding GTFS feed.
     * </pre>
     *
     * <code>optional string stop_id = 7;</code>
     */
    public Builder setStopIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      stopId_ = value;
      onChanged();
      return this;
    }

    private int currentStatus_ = 2;
    /**
     * <pre>
     * The exact status of the vehicle with respect to the current stop.
     * Ignored if current_stop_sequence is missing.
     * </pre>
     *
     * <code>optional .transit_realtime.VehiclePosition.VehicleStopStatus current_status = 4 [default = IN_TRANSIT_TO];</code>
     */
    public boolean hasCurrentStatus() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <pre>
     * The exact status of the vehicle with respect to the current stop.
     * Ignored if current_stop_sequence is missing.
     * </pre>
     *
     * <code>optional .transit_realtime.VehiclePosition.VehicleStopStatus current_status = 4 [default = IN_TRANSIT_TO];</code>
     */
    public sen.khyber.subway.client.proto.VehiclePosition.VehicleStopStatus getCurrentStatus() {
      sen.khyber.subway.client.proto.VehiclePosition.VehicleStopStatus result = sen.khyber.subway.client.proto.VehiclePosition.VehicleStopStatus.valueOf(currentStatus_);
      return result == null ? sen.khyber.subway.client.proto.VehiclePosition.VehicleStopStatus.IN_TRANSIT_TO : result;
    }
    /**
     * <pre>
     * The exact status of the vehicle with respect to the current stop.
     * Ignored if current_stop_sequence is missing.
     * </pre>
     *
     * <code>optional .transit_realtime.VehiclePosition.VehicleStopStatus current_status = 4 [default = IN_TRANSIT_TO];</code>
     */
    public Builder setCurrentStatus(sen.khyber.subway.client.proto.VehiclePosition.VehicleStopStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000020;
      currentStatus_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The exact status of the vehicle with respect to the current stop.
     * Ignored if current_stop_sequence is missing.
     * </pre>
     *
     * <code>optional .transit_realtime.VehiclePosition.VehicleStopStatus current_status = 4 [default = IN_TRANSIT_TO];</code>
     */
    public Builder clearCurrentStatus() {
      bitField0_ = (bitField0_ & ~0x00000020);
      currentStatus_ = 2;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <pre>
     * Moment at which the vehicle's position was measured. In POSIX time
     * (i.e., number of seconds since January 1st 1970 00:00:00 UTC).
     * </pre>
     *
     * <code>optional uint64 timestamp = 5;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <pre>
     * Moment at which the vehicle's position was measured. In POSIX time
     * (i.e., number of seconds since January 1st 1970 00:00:00 UTC).
     * </pre>
     *
     * <code>optional uint64 timestamp = 5;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * Moment at which the vehicle's position was measured. In POSIX time
     * (i.e., number of seconds since January 1st 1970 00:00:00 UTC).
     * </pre>
     *
     * <code>optional uint64 timestamp = 5;</code>
     */
    public Builder setTimestamp(long value) {
      bitField0_ |= 0x00000040;
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Moment at which the vehicle's position was measured. In POSIX time
     * (i.e., number of seconds since January 1st 1970 00:00:00 UTC).
     * </pre>
     *
     * <code>optional uint64 timestamp = 5;</code>
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000040);
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private int congestionLevel_ = 0;
    /**
     * <code>optional .transit_realtime.VehiclePosition.CongestionLevel congestion_level = 6;</code>
     */
    public boolean hasCongestionLevel() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional .transit_realtime.VehiclePosition.CongestionLevel congestion_level = 6;</code>
     */
    public sen.khyber.subway.client.proto.VehiclePosition.CongestionLevel getCongestionLevel() {
      sen.khyber.subway.client.proto.VehiclePosition.CongestionLevel result = sen.khyber.subway.client.proto.VehiclePosition.CongestionLevel.valueOf(congestionLevel_);
      return result == null ? sen.khyber.subway.client.proto.VehiclePosition.CongestionLevel.UNKNOWN_CONGESTION_LEVEL : result;
    }
    /**
     * <code>optional .transit_realtime.VehiclePosition.CongestionLevel congestion_level = 6;</code>
     */
    public Builder setCongestionLevel(sen.khyber.subway.client.proto.VehiclePosition.CongestionLevel value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000080;
      congestionLevel_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .transit_realtime.VehiclePosition.CongestionLevel congestion_level = 6;</code>
     */
    public Builder clearCongestionLevel() {
      bitField0_ = (bitField0_ & ~0x00000080);
      congestionLevel_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:transit_realtime.VehiclePosition)
  }

  // @@protoc_insertion_point(class_scope:transit_realtime.VehiclePosition)
  private static final sen.khyber.subway.client.proto.VehiclePosition DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sen.khyber.subway.client.proto.VehiclePosition();
  }

  public static sen.khyber.subway.client.proto.VehiclePosition getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<VehiclePosition>
      PARSER = new com.google.protobuf.AbstractParser<VehiclePosition>() {
    public VehiclePosition parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new VehiclePosition(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<VehiclePosition> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VehiclePosition> getParserForType() {
    return PARSER;
  }

  public sen.khyber.subway.client.proto.VehiclePosition getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

