// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gtfs-realtime.proto

package sen.khyber.web.subway.client.proto;

/**
 * <pre>
 * A selector for an entity in a GTFS feed.
 * </pre>
 * <p>
 * Protobuf type {@code transit_realtime.EntitySelector}
 */
public final class EntitySelector extends
        com.google.protobuf.GeneratedMessageV3.ExtendableMessage<
                EntitySelector> implements
        // @@protoc_insertion_point(message_implements:transit_realtime.EntitySelector)
        EntitySelectorOrBuilder {
    
    private static final long serialVersionUID = 0L;
    
    // Use EntitySelector.newBuilder() to construct.
    private EntitySelector(
            final com.google.protobuf.GeneratedMessageV3.ExtendableBuilder<EntitySelector, ?>
                    builder) {
        super(builder);
    }
    
    private EntitySelector() {
        agencyId_ = "";
        routeId_ = "";
        routeType_ = 0;
        stopId_ = "";
    }
    
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return unknownFields;
    }
    
    private EntitySelector(
            final com.google.protobuf.CodedInputStream input,
            final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        final int mutable_bitField0_ = 0;
        final com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                final int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        final com.google.protobuf.ByteString bs = input.readBytes();
                        bitField0_ |= 0x00000001;
                        agencyId_ = bs;
                        break;
                    }
                    case 18: {
                        final com.google.protobuf.ByteString bs = input.readBytes();
                        bitField0_ |= 0x00000002;
                        routeId_ = bs;
                        break;
                    }
                    case 24: {
                        bitField0_ |= 0x00000004;
                        routeType_ = input.readInt32();
                        break;
                    }
                    case 34: {
                        TripDescriptor.Builder subBuilder = null;
                        if (((bitField0_ & 0x00000008) == 0x00000008)) {
                            subBuilder = trip_.toBuilder();
                        }
                        trip_ = input.readMessage(TripDescriptor.PARSER, extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(trip_);
                            trip_ = subBuilder.buildPartial();
                        }
                        bitField0_ |= 0x00000008;
                        break;
                    }
                    case 42: {
                        final com.google.protobuf.ByteString bs = input.readBytes();
                        bitField0_ |= 0x00000010;
                        stopId_ = bs;
                        break;
                    }
                }
            }
        } catch (final com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (final java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return GtfsRealtime.internal_static_transit_realtime_EntitySelector_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return GtfsRealtime.internal_static_transit_realtime_EntitySelector_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        EntitySelector.class, EntitySelector.Builder.class);
    }
    
    private int bitField0_;
    public static final int AGENCY_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object agencyId_;
    
    /**
     * <pre>
     * The values of the fields should correspond to the appropriate fields in the
     * GTFS feed.
     * At least one specifier must be given. If several are given, then the
     * matching has to apply to all the given specifiers.
     * </pre>
     * <p>
     * <code>optional string agency_id = 1;</code>
     */
    @Override
    public boolean hasAgencyId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    
    /**
     * <pre>
     * The values of the fields should correspond to the appropriate fields in the
     * GTFS feed.
     * At least one specifier must be given. If several are given, then the
     * matching has to apply to all the given specifiers.
     * </pre>
     * <p>
     * <code>optional string agency_id = 1;</code>
     */
    @Override
    public java.lang.String getAgencyId() {
        final java.lang.Object ref = agencyId_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            final com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            final java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
                agencyId_ = s;
            }
            return s;
        }
    }
    
    /**
     * <pre>
     * The values of the fields should correspond to the appropriate fields in the
     * GTFS feed.
     * At least one specifier must be given. If several are given, then the
     * matching has to apply to all the given specifiers.
     * </pre>
     * <p>
     * <code>optional string agency_id = 1;</code>
     */
    @Override
    public com.google.protobuf.ByteString
    getAgencyIdBytes() {
        final java.lang.Object ref = agencyId_;
        if (ref instanceof java.lang.String) {
            final com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            agencyId_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }
    
    public static final int ROUTE_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object routeId_;
    
    /**
     * <code>optional string route_id = 2;</code>
     */
    @Override
    public boolean hasRouteId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    
    /**
     * <code>optional string route_id = 2;</code>
     */
    @Override
    public java.lang.String getRouteId() {
        final java.lang.Object ref = routeId_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            final com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            final java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
                routeId_ = s;
            }
            return s;
        }
    }
    
    /**
     * <code>optional string route_id = 2;</code>
     */
    @Override
    public com.google.protobuf.ByteString
    getRouteIdBytes() {
        final java.lang.Object ref = routeId_;
        if (ref instanceof java.lang.String) {
            final com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            routeId_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }
    
    public static final int ROUTE_TYPE_FIELD_NUMBER = 3;
    private int routeType_;
    
    /**
     * <pre>
     * corresponds to route_type in GTFS.
     * </pre>
     * <p>
     * <code>optional int32 route_type = 3;</code>
     */
    @Override
    public boolean hasRouteType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    
    /**
     * <pre>
     * corresponds to route_type in GTFS.
     * </pre>
     * <p>
     * <code>optional int32 route_type = 3;</code>
     */
    @Override
    public int getRouteType() {
        return routeType_;
    }
    
    public static final int TRIP_FIELD_NUMBER = 4;
    private TripDescriptor trip_;
    
    /**
     * <code>optional .transit_realtime.TripDescriptor trip = 4;</code>
     */
    @Override
    public boolean hasTrip() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    
    /**
     * <code>optional .transit_realtime.TripDescriptor trip = 4;</code>
     */
    @Override
    public TripDescriptor getTrip() {
        return trip_ == null ? TripDescriptor.getDefaultInstance() : trip_;
    }
    
    /**
     * <code>optional .transit_realtime.TripDescriptor trip = 4;</code>
     */
    @Override
    public TripDescriptorOrBuilder getTripOrBuilder() {
        return trip_ == null ? TripDescriptor.getDefaultInstance() : trip_;
    }
    
    public static final int STOP_ID_FIELD_NUMBER = 5;
    private volatile java.lang.Object stopId_;
    
    /**
     * <code>optional string stop_id = 5;</code>
     */
    @Override
    public boolean hasStopId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    
    /**
     * <code>optional string stop_id = 5;</code>
     */
    @Override
    public java.lang.String getStopId() {
        final java.lang.Object ref = stopId_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            final com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            final java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
                stopId_ = s;
            }
            return s;
        }
    }
    
    /**
     * <code>optional string stop_id = 5;</code>
     */
    @Override
    public com.google.protobuf.ByteString
    getStopIdBytes() {
        final java.lang.Object ref = stopId_;
        if (ref instanceof java.lang.String) {
            final com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            stopId_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }
    
    private byte memoizedIsInitialized = -1;
    
    @Override
    public final boolean isInitialized() {
        final byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) {return true;}
        if (isInitialized == 0) {return false;}
        
        if (hasTrip()) {
            if (!getTrip().isInitialized()) {
                memoizedIsInitialized = 0;
                return false;
            }
        }
        if (!extensionsAreInitialized()) {
            memoizedIsInitialized = 0;
            return false;
        }
        memoizedIsInitialized = 1;
        return true;
    }
    
    @Override
    public void writeTo(final com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        final com.google.protobuf.GeneratedMessageV3
                .ExtendableMessage<EntitySelector>.ExtensionWriter
                extensionWriter = newExtensionWriter();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, agencyId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, routeId_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
            output.writeInt32(3, routeType_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
            output.writeMessage(4, getTrip());
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 5, stopId_);
        }
        extensionWriter.writeUntil(2000, output);
        unknownFields.writeTo(output);
    }
    
    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) {return size;}
        
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, agencyId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, routeId_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(3, routeType_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(4, getTrip());
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, stopId_);
        }
        size += extensionsSerializedSize();
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }
    
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof EntitySelector)) {
            return super.equals(obj);
        }
        final EntitySelector other = (EntitySelector) obj;
        
        boolean result = true;
        result = result && (hasAgencyId() == other.hasAgencyId());
        if (hasAgencyId()) {
            result = result && getAgencyId()
                    .equals(other.getAgencyId());
        }
        result = result && (hasRouteId() == other.hasRouteId());
        if (hasRouteId()) {
            result = result && getRouteId()
                    .equals(other.getRouteId());
        }
        result = result && (hasRouteType() == other.hasRouteType());
        if (hasRouteType()) {
            result = result && (getRouteType()
                    == other.getRouteType());
        }
        result = result && (hasTrip() == other.hasTrip());
        if (hasTrip()) {
            result = result && getTrip()
                    .equals(other.getTrip());
        }
        result = result && (hasStopId() == other.hasStopId());
        if (hasStopId()) {
            result = result && getStopId()
                    .equals(other.getStopId());
        }
        result = result && unknownFields.equals(other.unknownFields);
        result = result &&
                getExtensionFields().equals(other.getExtensionFields());
        return result;
    }
    
    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasAgencyId()) {
            hash = (37 * hash) + AGENCY_ID_FIELD_NUMBER;
            hash = (53 * hash) + getAgencyId().hashCode();
        }
        if (hasRouteId()) {
            hash = (37 * hash) + ROUTE_ID_FIELD_NUMBER;
            hash = (53 * hash) + getRouteId().hashCode();
        }
        if (hasRouteType()) {
            hash = (37 * hash) + ROUTE_TYPE_FIELD_NUMBER;
            hash = (53 * hash) + getRouteType();
        }
        if (hasTrip()) {
            hash = (37 * hash) + TRIP_FIELD_NUMBER;
            hash = (53 * hash) + getTrip().hashCode();
        }
        if (hasStopId()) {
            hash = (37 * hash) + STOP_ID_FIELD_NUMBER;
            hash = (53 * hash) + getStopId().hashCode();
        }
        hash = hashFields(hash, getExtensionFields());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }
    
    public static EntitySelector parseFrom(
            final java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    
    public static EntitySelector parseFrom(
            final java.nio.ByteBuffer data,
            final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    
    public static EntitySelector parseFrom(
            final com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    
    public static EntitySelector parseFrom(
            final com.google.protobuf.ByteString data,
            final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    
    public static EntitySelector parseFrom(final byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    
    public static EntitySelector parseFrom(
            final byte[] data,
            final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    
    public static EntitySelector parseFrom(final java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }
    
    public static EntitySelector parseFrom(
            final java.io.InputStream input,
            final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }
    
    public static EntitySelector parseDelimitedFrom(final java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }
    
    public static EntitySelector parseDelimitedFrom(
            final java.io.InputStream input,
            final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    
    public static EntitySelector parseFrom(
            final com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }
    
    public static EntitySelector parseFrom(
            final com.google.protobuf.CodedInputStream input,
            final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }
    
    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    
    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }
    
    public static Builder newBuilder(final EntitySelector prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    
    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }
    
    @java.lang.Override
    protected Builder newBuilderForType(
            final com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        final Builder builder = new Builder(parent);
        return builder;
    }
    
    /**
     * <pre>
     * A selector for an entity in a GTFS feed.
     * </pre>
     * <p>
     * Protobuf type {@code transit_realtime.EntitySelector}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.ExtendableBuilder<
                    EntitySelector, Builder> implements
            // @@protoc_insertion_point(builder_implements:transit_realtime.EntitySelector)
            EntitySelectorOrBuilder {
        
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return GtfsRealtime.internal_static_transit_realtime_EntitySelector_descriptor;
        }
        
        @Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return GtfsRealtime.internal_static_transit_realtime_EntitySelector_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            EntitySelector.class, EntitySelector.Builder.class);
        }
        
        // Construct using sen.khyber.subway.client.proto.EntitySelector.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }
        
        private Builder(
                final com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }
        
        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
                getTripFieldBuilder();
            }
        }
        
        @Override
        public Builder clear() {
            super.clear();
            agencyId_ = "";
            bitField0_ = (bitField0_ & ~0x00000001);
            routeId_ = "";
            bitField0_ = (bitField0_ & ~0x00000002);
            routeType_ = 0;
            bitField0_ = (bitField0_ & ~0x00000004);
            if (tripBuilder_ == null) {
                trip_ = null;
            } else {
                tripBuilder_.clear();
            }
            bitField0_ = (bitField0_ & ~0x00000008);
            stopId_ = "";
            bitField0_ = (bitField0_ & ~0x00000010);
            return this;
        }
        
        @Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return GtfsRealtime.internal_static_transit_realtime_EntitySelector_descriptor;
        }
        
        @Override
        public EntitySelector getDefaultInstanceForType() {
            return EntitySelector.getDefaultInstance();
        }
        
        @Override
        public EntitySelector build() {
            final EntitySelector result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }
        
        @Override
        public EntitySelector buildPartial() {
            final EntitySelector result = new EntitySelector(this);
            final int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                to_bitField0_ |= 0x00000001;
            }
            result.agencyId_ = agencyId_;
            if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                to_bitField0_ |= 0x00000002;
            }
            result.routeId_ = routeId_;
            if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                to_bitField0_ |= 0x00000004;
            }
            result.routeType_ = routeType_;
            if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                to_bitField0_ |= 0x00000008;
            }
            if (tripBuilder_ == null) {
                result.trip_ = trip_;
            } else {
                result.trip_ = tripBuilder_.build();
            }
            if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
                to_bitField0_ |= 0x00000010;
            }
            result.stopId_ = stopId_;
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
        }
        
        @Override
        public Builder clone() {
            return (Builder) super.clone();
        }
        
        @Override
        public Builder setField(
                final com.google.protobuf.Descriptors.FieldDescriptor field,
                final java.lang.Object value) {
            return (Builder) super.setField(field, value);
        }
        
        @Override
        public Builder clearField(
                final com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }
        
        @Override
        public Builder clearOneof(
                final com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }
        
        @Override
        public Builder setRepeatedField(
                final com.google.protobuf.Descriptors.FieldDescriptor field,
                final int index, final java.lang.Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }
        
        @Override
        public Builder addRepeatedField(
                final com.google.protobuf.Descriptors.FieldDescriptor field,
                final java.lang.Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }
        
        @Override
        public <Type> Builder setExtension(
                final com.google.protobuf.GeneratedMessage.GeneratedExtension<
                        EntitySelector, Type> extension,
                final Type value) {
            return (Builder) super.setExtension(extension, value);
        }
        
        @Override
        public <Type> Builder setExtension(
                final com.google.protobuf.GeneratedMessage.GeneratedExtension<
                        EntitySelector, java.util.List<Type>> extension,
                final int index, final Type value) {
            return (Builder) super.setExtension(extension, index, value);
        }
        
        @Override
        public <Type> Builder addExtension(
                final com.google.protobuf.GeneratedMessage.GeneratedExtension<
                        EntitySelector, java.util.List<Type>> extension,
                final Type value) {
            return (Builder) super.addExtension(extension, value);
        }
        
        @Override
        public <Type> Builder clearExtension(
                final com.google.protobuf.GeneratedMessage.GeneratedExtension<
                        EntitySelector, ?> extension) {
            return (Builder) super.clearExtension(extension);
        }
        
        @Override
        public Builder mergeFrom(final com.google.protobuf.Message other) {
            if (other instanceof EntitySelector) {
                return mergeFrom((EntitySelector) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }
        
        public Builder mergeFrom(final EntitySelector other) {
            if (other == EntitySelector.getDefaultInstance()) {return this;}
            if (other.hasAgencyId()) {
                bitField0_ |= 0x00000001;
                agencyId_ = other.agencyId_;
                onChanged();
            }
            if (other.hasRouteId()) {
                bitField0_ |= 0x00000002;
                routeId_ = other.routeId_;
                onChanged();
            }
            if (other.hasRouteType()) {
                setRouteType(other.getRouteType());
            }
            if (other.hasTrip()) {
                mergeTrip(other.getTrip());
            }
            if (other.hasStopId()) {
                bitField0_ |= 0x00000010;
                stopId_ = other.stopId_;
                onChanged();
            }
            mergeExtensionFields(other);
            mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }
        
        @Override
        public final boolean isInitialized() {
            if (hasTrip()) {
                if (!getTrip().isInitialized()) {
                    return false;
                }
            }
            if (!extensionsAreInitialized()) {
                return false;
            }
            return true;
        }
        
        @Override
        public Builder mergeFrom(
                final com.google.protobuf.CodedInputStream input,
                final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            EntitySelector parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (final com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (EntitySelector) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }
        
        private int bitField0_;
        
        private java.lang.Object agencyId_ = "";
        
        /**
         * <pre>
         * The values of the fields should correspond to the appropriate fields in the
         * GTFS feed.
         * At least one specifier must be given. If several are given, then the
         * matching has to apply to all the given specifiers.
         * </pre>
         * <p>
         * <code>optional string agency_id = 1;</code>
         */
        @Override
        public boolean hasAgencyId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        
        /**
         * <pre>
         * The values of the fields should correspond to the appropriate fields in the
         * GTFS feed.
         * At least one specifier must be given. If several are given, then the
         * matching has to apply to all the given specifiers.
         * </pre>
         * <p>
         * <code>optional string agency_id = 1;</code>
         */
        @Override
        public java.lang.String getAgencyId() {
            final java.lang.Object ref = agencyId_;
            if (!(ref instanceof java.lang.String)) {
                final com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                final java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    agencyId_ = s;
                }
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }
        
        /**
         * <pre>
         * The values of the fields should correspond to the appropriate fields in the
         * GTFS feed.
         * At least one specifier must be given. If several are given, then the
         * matching has to apply to all the given specifiers.
         * </pre>
         * <p>
         * <code>optional string agency_id = 1;</code>
         */
        @Override
        public com.google.protobuf.ByteString
        getAgencyIdBytes() {
            final java.lang.Object ref = agencyId_;
            if (ref instanceof String) {
                final com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                agencyId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }
        
        /**
         * <pre>
         * The values of the fields should correspond to the appropriate fields in the
         * GTFS feed.
         * At least one specifier must be given. If several are given, then the
         * matching has to apply to all the given specifiers.
         * </pre>
         * <p>
         * <code>optional string agency_id = 1;</code>
         */
        public Builder setAgencyId(
                final java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000001;
            agencyId_ = value;
            onChanged();
            return this;
        }
        
        /**
         * <pre>
         * The values of the fields should correspond to the appropriate fields in the
         * GTFS feed.
         * At least one specifier must be given. If several are given, then the
         * matching has to apply to all the given specifiers.
         * </pre>
         * <p>
         * <code>optional string agency_id = 1;</code>
         */
        public Builder clearAgencyId() {
            bitField0_ = (bitField0_ & ~0x00000001);
            agencyId_ = getDefaultInstance().getAgencyId();
            onChanged();
            return this;
        }
        
        /**
         * <pre>
         * The values of the fields should correspond to the appropriate fields in the
         * GTFS feed.
         * At least one specifier must be given. If several are given, then the
         * matching has to apply to all the given specifiers.
         * </pre>
         * <p>
         * <code>optional string agency_id = 1;</code>
         */
        public Builder setAgencyIdBytes(
                final com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000001;
            agencyId_ = value;
            onChanged();
            return this;
        }
        
        private java.lang.Object routeId_ = "";
        
        /**
         * <code>optional string route_id = 2;</code>
         */
        @Override
        public boolean hasRouteId() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        
        /**
         * <code>optional string route_id = 2;</code>
         */
        @Override
        public java.lang.String getRouteId() {
            final java.lang.Object ref = routeId_;
            if (!(ref instanceof java.lang.String)) {
                final com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                final java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    routeId_ = s;
                }
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }
        
        /**
         * <code>optional string route_id = 2;</code>
         */
        @Override
        public com.google.protobuf.ByteString
        getRouteIdBytes() {
            final java.lang.Object ref = routeId_;
            if (ref instanceof String) {
                final com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                routeId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }
        
        /**
         * <code>optional string route_id = 2;</code>
         */
        public Builder setRouteId(
                final java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000002;
            routeId_ = value;
            onChanged();
            return this;
        }
        
        /**
         * <code>optional string route_id = 2;</code>
         */
        public Builder clearRouteId() {
            bitField0_ = (bitField0_ & ~0x00000002);
            routeId_ = getDefaultInstance().getRouteId();
            onChanged();
            return this;
        }
        
        /**
         * <code>optional string route_id = 2;</code>
         */
        public Builder setRouteIdBytes(
                final com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000002;
            routeId_ = value;
            onChanged();
            return this;
        }
        
        private int routeType_;
        
        /**
         * <pre>
         * corresponds to route_type in GTFS.
         * </pre>
         * <p>
         * <code>optional int32 route_type = 3;</code>
         */
        @Override
        public boolean hasRouteType() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        
        /**
         * <pre>
         * corresponds to route_type in GTFS.
         * </pre>
         * <p>
         * <code>optional int32 route_type = 3;</code>
         */
        @Override
        public int getRouteType() {
            return routeType_;
        }
        
        /**
         * <pre>
         * corresponds to route_type in GTFS.
         * </pre>
         * <p>
         * <code>optional int32 route_type = 3;</code>
         */
        public Builder setRouteType(final int value) {
            bitField0_ |= 0x00000004;
            routeType_ = value;
            onChanged();
            return this;
        }
        
        /**
         * <pre>
         * corresponds to route_type in GTFS.
         * </pre>
         * <p>
         * <code>optional int32 route_type = 3;</code>
         */
        public Builder clearRouteType() {
            bitField0_ = (bitField0_ & ~0x00000004);
            routeType_ = 0;
            onChanged();
            return this;
        }
        
        private TripDescriptor trip_ = null;
        private com.google.protobuf.SingleFieldBuilderV3<
                TripDescriptor, TripDescriptor.Builder, TripDescriptorOrBuilder> tripBuilder_;
        
        /**
         * <code>optional .transit_realtime.TripDescriptor trip = 4;</code>
         */
        @Override
        public boolean hasTrip() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        
        /**
         * <code>optional .transit_realtime.TripDescriptor trip = 4;</code>
         */
        @Override
        public TripDescriptor getTrip() {
            if (tripBuilder_ == null) {
                return trip_ == null ? TripDescriptor.getDefaultInstance() : trip_;
            } else {
                return tripBuilder_.getMessage();
            }
        }
        
        /**
         * <code>optional .transit_realtime.TripDescriptor trip = 4;</code>
         */
        public Builder setTrip(final TripDescriptor value) {
            if (tripBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                trip_ = value;
                onChanged();
            } else {
                tripBuilder_.setMessage(value);
            }
            bitField0_ |= 0x00000008;
            return this;
        }
        
        /**
         * <code>optional .transit_realtime.TripDescriptor trip = 4;</code>
         */
        public Builder setTrip(
                final TripDescriptor.Builder builderForValue) {
            if (tripBuilder_ == null) {
                trip_ = builderForValue.build();
                onChanged();
            } else {
                tripBuilder_.setMessage(builderForValue.build());
            }
            bitField0_ |= 0x00000008;
            return this;
        }
        
        /**
         * <code>optional .transit_realtime.TripDescriptor trip = 4;</code>
         */
        public Builder mergeTrip(final TripDescriptor value) {
            if (tripBuilder_ == null) {
                if (((bitField0_ & 0x00000008) == 0x00000008) &&
                        trip_ != null &&
                        trip_ != TripDescriptor.getDefaultInstance()) {
                    trip_ =
                            TripDescriptor.newBuilder(trip_).mergeFrom(value).buildPartial();
                } else {
                    trip_ = value;
                }
                onChanged();
            } else {
                tripBuilder_.mergeFrom(value);
            }
            bitField0_ |= 0x00000008;
            return this;
        }
        
        /**
         * <code>optional .transit_realtime.TripDescriptor trip = 4;</code>
         */
        public Builder clearTrip() {
            if (tripBuilder_ == null) {
                trip_ = null;
                onChanged();
            } else {
                tripBuilder_.clear();
            }
            bitField0_ = (bitField0_ & ~0x00000008);
            return this;
        }
        
        /**
         * <code>optional .transit_realtime.TripDescriptor trip = 4;</code>
         */
        public TripDescriptor.Builder getTripBuilder() {
            bitField0_ |= 0x00000008;
            onChanged();
            return getTripFieldBuilder().getBuilder();
        }
        
        /**
         * <code>optional .transit_realtime.TripDescriptor trip = 4;</code>
         */
        @Override
        public TripDescriptorOrBuilder getTripOrBuilder() {
            if (tripBuilder_ != null) {
                return tripBuilder_.getMessageOrBuilder();
            } else {
                return trip_ == null ?
                        TripDescriptor.getDefaultInstance() : trip_;
            }
        }
        
        /**
         * <code>optional .transit_realtime.TripDescriptor trip = 4;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                TripDescriptor, TripDescriptor.Builder, TripDescriptorOrBuilder>
        getTripFieldBuilder() {
            if (tripBuilder_ == null) {
                tripBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<>(
                        getTrip(),
                        getParentForChildren(),
                        isClean());
                trip_ = null;
            }
            return tripBuilder_;
        }
        
        private java.lang.Object stopId_ = "";
        
        /**
         * <code>optional string stop_id = 5;</code>
         */
        @Override
        public boolean hasStopId() {
            return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        
        /**
         * <code>optional string stop_id = 5;</code>
         */
        @Override
        public java.lang.String getStopId() {
            final java.lang.Object ref = stopId_;
            if (!(ref instanceof java.lang.String)) {
                final com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                final java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    stopId_ = s;
                }
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }
        
        /**
         * <code>optional string stop_id = 5;</code>
         */
        @Override
        public com.google.protobuf.ByteString
        getStopIdBytes() {
            final java.lang.Object ref = stopId_;
            if (ref instanceof String) {
                final com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                stopId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }
        
        /**
         * <code>optional string stop_id = 5;</code>
         */
        public Builder setStopId(
                final java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000010;
            stopId_ = value;
            onChanged();
            return this;
        }
        
        /**
         * <code>optional string stop_id = 5;</code>
         */
        public Builder clearStopId() {
            bitField0_ = (bitField0_ & ~0x00000010);
            stopId_ = getDefaultInstance().getStopId();
            onChanged();
            return this;
        }
        
        /**
         * <code>optional string stop_id = 5;</code>
         */
        public Builder setStopIdBytes(
                final com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000010;
            stopId_ = value;
            onChanged();
            return this;
        }
        
        @Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }
        
        @Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }
        
        
        // @@protoc_insertion_point(builder_scope:transit_realtime.EntitySelector)
    }
    
    // @@protoc_insertion_point(class_scope:transit_realtime.EntitySelector)
    private static final EntitySelector DEFAULT_INSTANCE;
    
    static {
        DEFAULT_INSTANCE = new EntitySelector();
    }
    
    public static EntitySelector getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }
    
    @java.lang.Deprecated public static final com.google.protobuf.Parser<EntitySelector>
            PARSER = new com.google.protobuf.AbstractParser<>() {
        
        @Override
        public EntitySelector parsePartialFrom(
                final com.google.protobuf.CodedInputStream input,
                final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new EntitySelector(input, extensionRegistry);
        }
    };
    
    public static com.google.protobuf.Parser<EntitySelector> parser() {
        return PARSER;
    }
    
    @java.lang.Override
    public com.google.protobuf.Parser<EntitySelector> getParserForType() {
        return PARSER;
    }
    
    @Override
    public EntitySelector getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }
    
}

