// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gtfs-realtime.proto

package sen.khyber.web.subway.client.proto;

public interface FeedMessageOrBuilder extends
        // @@protoc_insertion_point(interface_extends:transit_realtime.FeedMessage)
        com.google.protobuf.MessageOrBuilder {
    
    /**
     * <pre>
     * Metadata about this feed and feed message.
     * </pre>
     * <p>
     * <code>required .transit_realtime.FeedHeader header = 1;</code>
     */
    boolean hasHeader();
    
    /**
     * <pre>
     * Metadata about this feed and feed message.
     * </pre>
     * <p>
     * <code>required .transit_realtime.FeedHeader header = 1;</code>
     */
    FeedHeader getHeader();
    
    /**
     * <pre>
     * Metadata about this feed and feed message.
     * </pre>
     * <p>
     * <code>required .transit_realtime.FeedHeader header = 1;</code>
     */
    FeedHeaderOrBuilder getHeaderOrBuilder();
    
    /**
     * <pre>
     * Contents of the feed.
     * </pre>
     * <p>
     * <code>repeated .transit_realtime.FeedEntity entity = 2;</code>
     */
    java.util.List<FeedEntity>
    getEntityList();
    
    /**
     * <pre>
     * Contents of the feed.
     * </pre>
     * <p>
     * <code>repeated .transit_realtime.FeedEntity entity = 2;</code>
     */
    FeedEntity getEntity(int index);
    
    /**
     * <pre>
     * Contents of the feed.
     * </pre>
     * <p>
     * <code>repeated .transit_realtime.FeedEntity entity = 2;</code>
     */
    int getEntityCount();
    
    /**
     * <pre>
     * Contents of the feed.
     * </pre>
     * <p>
     * <code>repeated .transit_realtime.FeedEntity entity = 2;</code>
     */
    java.util.List<? extends FeedEntityOrBuilder>
    getEntityOrBuilderList();
    
    /**
     * <pre>
     * Contents of the feed.
     * </pre>
     * <p>
     * <code>repeated .transit_realtime.FeedEntity entity = 2;</code>
     */
    FeedEntityOrBuilder getEntityOrBuilder(
            int index);
}
