// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gtfs-realtime.proto

package sen.khyber.web.subway.client.proto;

import sen.khyber.web.subway.client.proto.FeedHeader.Incrementality;

import com.google.protobuf.ByteString;
import com.google.protobuf.GeneratedMessageV3.ExtendableMessageOrBuilder;

public interface FeedHeaderOrBuilder extends ExtendableMessageOrBuilder<FeedHeader> {
    
    /**
     * <pre>
     * Version of the feed specification.
     * The current version is 1.0.
     * </pre>
     * <p>
     * <code>required string gtfs_realtime_version = 1;</code>
     */
    boolean hasGtfsRealtimeVersion();
    
    /**
     * <pre>
     * Version of the feed specification.
     * The current version is 1.0.
     * </pre>
     * <p>
     * <code>required string gtfs_realtime_version = 1;</code>
     */
    String getGtfsRealtimeVersion();
    
    /**
     * <pre>
     * Version of the feed specification.
     * The current version is 1.0.
     * </pre>
     * <p>
     * <code>required string gtfs_realtime_version = 1;</code>
     */
    ByteString getGtfsRealtimeVersionBytes();
    
    /**
     * <code>optional .transit_realtime.FeedHeader.Incrementality incrementality = 2 [default =
     * FULL_DATASET];</code>
     */
    boolean hasIncrementality();
    
    /**
     * <code>optional .transit_realtime.FeedHeader.Incrementality incrementality = 2 [default =
     * FULL_DATASET];</code>
     */
    Incrementality getIncrementality();
    
    /**
     * <pre>
     * This timestamp identifies the moment when the content of this feed contains been
     * created (in server time). In POSIX time (i.e., number of seconds since
     * January 1st 1970 00:00:00 UTC).
     * </pre>
     * <p>
     * <code>optional uint64 timestamp = 3;</code>
     */
    boolean hasTimestamp();
    
    /**
     * <pre>
     * This timestamp identifies the moment when the content of this feed contains been
     * created (in server time). In POSIX time (i.e., number of seconds since
     * January 1st 1970 00:00:00 UTC).
     * </pre>
     * <p>
     * <code>optional uint64 timestamp = 3;</code>
     */
    long getTimestamp();
    
}
