// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gtfs-realtime.proto

package sen.khyber.web.subway.client.proto;

import com.google.protobuf.Descriptors.Descriptor;
import com.google.protobuf.Descriptors.FileDescriptor;
import com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner;
import com.google.protobuf.ExtensionRegistry;
import com.google.protobuf.ExtensionRegistryLite;
import com.google.protobuf.GeneratedMessageV3.FieldAccessorTable;

public final class GtfsRealtime {
    
    private GtfsRealtime() {}
    
    public static void registerAllExtensions(final ExtensionRegistryLite registry) {}
    
    public static void registerAllExtensions(final ExtensionRegistry registry) {
        registerAllExtensions((ExtensionRegistryLite) registry);
    }
    
    static final Descriptor internal_static_transit_realtime_FeedMessage_descriptor;
    static final FieldAccessorTable internal_static_transit_realtime_FeedMessage_fieldAccessorTable;
    static final Descriptor internal_static_transit_realtime_FeedHeader_descriptor;
    static final FieldAccessorTable internal_static_transit_realtime_FeedHeader_fieldAccessorTable;
    static final Descriptor internal_static_transit_realtime_FeedEntity_descriptor;
    static final FieldAccessorTable internal_static_transit_realtime_FeedEntity_fieldAccessorTable;
    static final Descriptor internal_static_transit_realtime_TripUpdate_descriptor;
    static final FieldAccessorTable internal_static_transit_realtime_TripUpdate_fieldAccessorTable;
    static final Descriptor internal_static_transit_realtime_TripUpdate_StopTimeEvent_descriptor;
    static final FieldAccessorTable
            internal_static_transit_realtime_TripUpdate_StopTimeEvent_fieldAccessorTable;
    static final Descriptor internal_static_transit_realtime_TripUpdate_StopTimeUpdate_descriptor;
    static final FieldAccessorTable
            internal_static_transit_realtime_TripUpdate_StopTimeUpdate_fieldAccessorTable;
    static final Descriptor internal_static_transit_realtime_VehiclePosition_descriptor;
    static final FieldAccessorTable
            internal_static_transit_realtime_VehiclePosition_fieldAccessorTable;
    static final Descriptor internal_static_transit_realtime_Alert_descriptor;
    static final FieldAccessorTable internal_static_transit_realtime_Alert_fieldAccessorTable;
    static final Descriptor internal_static_transit_realtime_TimeRange_descriptor;
    static final FieldAccessorTable internal_static_transit_realtime_TimeRange_fieldAccessorTable;
    static final Descriptor internal_static_transit_realtime_Position_descriptor;
    static final FieldAccessorTable internal_static_transit_realtime_Position_fieldAccessorTable;
    static final Descriptor internal_static_transit_realtime_TripDescriptor_descriptor;
    static final FieldAccessorTable
            internal_static_transit_realtime_TripDescriptor_fieldAccessorTable;
    static final Descriptor internal_static_transit_realtime_VehicleDescriptor_descriptor;
    static final FieldAccessorTable
            internal_static_transit_realtime_VehicleDescriptor_fieldAccessorTable;
    static final Descriptor internal_static_transit_realtime_EntitySelector_descriptor;
    static final FieldAccessorTable
            internal_static_transit_realtime_EntitySelector_fieldAccessorTable;
    static final Descriptor internal_static_transit_realtime_TranslatedString_descriptor;
    static final FieldAccessorTable
            internal_static_transit_realtime_TranslatedString_fieldAccessorTable;
    static final Descriptor
            internal_static_transit_realtime_TranslatedString_Translation_descriptor;
    static final FieldAccessorTable
            internal_static_transit_realtime_TranslatedString_Translation_fieldAccessorTable;
    
    public static FileDescriptor getDescriptor() {
        return descriptor;
    }
    
    private static FileDescriptor descriptor;
    
    static {
        final String[] descriptorData = {
                "\n\023gtfs-realtime.proto\022\020transit_realtime\""
                        + "i\n\013FeedMessage\022,\n\006header\030\001 \002(\0132\034.transit"
                        + "_realtime.FeedHeader\022,\n\006entity\030\002 \003(\0132\034.t"
                        + "ransit_realtime.FeedEntity\"\317\001\n\nFeedHeade"
                        + "r\022\035\n\025gtfs_realtime_version\030\001 \002(\t\022Q\n\016incr"
                        + "ementality\030\002 \001(\0162+.transit_realtime.Feed"
                        + "Header.Incrementality:\014FULL_DATASET\022\021\n\tt"
                        + "imestamp\030\003 \001(\004\"4\n\016Incrementality\022\020\n\014FULL"
                        + "_DATASET\020\000\022\020\n\014DIFFERENTIAL\020\001*\006\010\350\007\020"
                        + "\320\017\"\302\001\n" + "\nFeedEntity\022\n\n\002id\030\001 \002"
                        + "(\t\022\031\n\nis_deleted\030\002 ",
                "\001(\010:\005false\0221\n\013trip_update\030\003 \001(\0132\034.transi"
                        + "t_realtime.TripUpdate\0222\n\007vehicle\030\004 \001(\0132!"
                        + ".transit_realtime.VehiclePosition\022&\n\005ale"
                        + "rt\030\005 \001(\0132\027.transit_realtime.Alert\"\213\005\n\nTr"
                        + "ipUpdate\022.\n\004trip\030\001 \002(\0132 .transit_realtim"
                        + "e.TripDescriptor\0224\n\007vehicle\030\003 \001(\0132#.tran"
                        + "sit_realtime.VehicleDescriptor\022E\n\020stop_t"
                        + "ime_update\030\002 \003(\0132+.transit_realtime.Trip"
                        + "Update.StopTimeUpdate\022\021\n\ttimestamp\030\004 \001(\004"
                        + "\032I\n\rStopTimeEvent\022\r\n\005delay\030\001 \001"
                        + "(\005\022\014\n\004time",
                "\030\002 \001(\003\022\023\n\013uncertainty\030\003 \001"
                        + "(\005*\006\010\350\007\020\320\017\032\351\002\n\016"
                        + "StopTimeUpdate\022\025\n\rstop_sequence\030\001 \001(\r\022\017\n"
                        + "\007stop_id\030\004 \001(\t\022;\n\007arrival\030\002 \001(\0132*.transi"
                        + "t_realtime.TripUpdate.StopTimeEvent\022=\n\td"
                        + "eparture\030\003 \001(\0132*.transit_realtime.TripUp"
                        + "date.StopTimeEvent\022j\n\025schedule_relations"
                        + "hip\030\005 \001(\0162@.transit_realtime.TripUpdate."
                        + "StopTimeUpdate.ScheduleRelationship:\tSCH"
                        + "EDULED\"?\n\024ScheduleRelationship\022\r\n\tSCHEDU"
                        + "LED\020\000\022\013\n\007SKIPPED\020\001\022\013\n\007NO_DATA\020\002"
                        + "*\006\010\350\007\020\320\017*",
                "\006\010\350\007\020\320\017\"\341\004\n\017VehiclePosition\022.\n\004trip\030"
                        + "\001 \001(" + "\0132 .transit_realtime.TripDescriptor\0224\n\007v"
                        + "ehicle\030\010 \001(\0132#.transit_realtime.VehicleD"
                        + "escriptor\022,\n\010position\030\002 \001(\0132\032.transit_re"
                        + "altime.Position\022\035\n\025current_stop_sequence"
                        + "\030\003 \001(\r\022\017\n\007stop_id\030\007 \001"
                        + "(\t\022Z\n\016current_statu"
                        + "s\030\004 \001(\01623.transit_realtime.VehiclePositi"
                        + "on.VehicleStopStatus:\rIN_TRANSIT_TO\022\021\n\tt"
                        + "imestamp\030\005 \001(\004\022K\n\020congestion_level\030\006 \001(\016"
                        + "21.transit_realtime.VehiclePosition.Cong",
                "estionLevel\"G\n\021VehicleStopStatus\022\017\n\013INCO"
                        + "MING_AT\020\000\022\016\n\nSTOPPED_AT\020\001\022\021\n\rIN_TRANSIT_"
                        + "TO\020\002\"}\n\017CongestionLevel\022\034\n\030UNKNOWN_CONGE"
                        + "STION_LEVEL\020\000\022\024\n\020RUNNING_SMOOTHLY\020\001\022\017\n\013S"
                        + "TOP_AND_GO\020\002\022\016\n\nCONGESTION\020\003\022\025\n\021SEVERE_C"
                        + "ONGESTION\020\004*\006\010\350\007\020\320\017\"\266\006\n\005Alert\0222"
                        + "\n\ractive_" + "period\030\001 \003(\0132\033.transit_realtime.TimeRang"
                        + "e\0229\n\017informed_entity\030\005 \003(\0132 .transit_rea"
                        + "ltime.EntitySelector\022;\n\005cause\030\006 \001(\0162\035.tr"
                        + "ansit_realtime.Alert.Cause:\rUNKNOWN_CAUS",
                "E\022>\n\006effect\030\007 \001(\0162\036.transit_realtime.Ale"
                        + "rt.Effect:\016UNKNOWN_EFFECT\022/\n\003url\030\010 \001(\0132\""
                        + ".transit_realtime.TranslatedString\0227\n\013he"
                        + "ader_text\030\n \001(\0132\".transit_realtime.Trans"
                        + "latedString\022<\n\020description_text\030\013 \001(\0132\"."
                        + "transit_realtime.TranslatedString\"\330\001\n\005Ca"
                        + "use\022\021\n\rUNKNOWN_CAUSE\020\001\022\017\n\013OTHER_CAUSE\020\002"
                        + "\022"
                        + "\025\n\021TECHNICAL_PROBLEM\020\003\022\n\n\006STRIKE\020\004\022\021\n"
                        + "\rDE"
                        + "MONSTRATION\020\005\022\014\n\010ACCIDENT\020\006\022\013\n\007HOLIDAY"
                        + "\020\007"
                        + "\022\013\n\007WEATHER\020\010\022\017\n\013MAINTENANCE\020\t\022\020\n"
                        + "\014CONSTR",
                "UCTION\020\n\022\023\n\017POLICE_ACTIVITY\020\013\022\025\n\021MEDICAL"
                        + "_EMERGENCY\020\014\"\265\001\n\006Effect\022\016\n\nNO_SERVICE\020\001"
                        + "\022" + "\023\n\017REDUCED_SERVICE\020\002\022\026\n\022SIGNIFICANT_DELA"
                        + "YS\020\003\022\n\n\006DETOUR\020\004\022\026\n\022ADDITIONAL_SERVICE\020"
                        + "\005"
                        + "\022\024\n\020MODIFIED_SERVICE\020\006\022\020\n\014OTHER_EFFECT\020\007"
                        + "\022\022\n\016UNKNOWN_EFFECT\020\010\022\016\n\nSTOP_MOVED\020\t*\006"
                        + "\010\350"
                        + "\007\020\320\017\"\'\n\tTimeRange\022\r\n\005start\030\001 \001"
                        + "(\004\022\013\n\003end\030"
                        + "\002 \001(\004\"i\n\010Position\022\020\n\010latitude\030\001 \002"
                        + "(\002\022\021\n\tl"
                        + "ongitude\030\002 \002(\002\022\017\n\007bearing\030\003 \001"
                        + "(\002\022\020\n\010odome"
                        + "ter\030\004 \001(\001\022\r\n\005speed\030\005 \001"
                        + "(\002*\006\010\350\007\020\320\017\"\212\002\n\016Tri",
                "pDescriptor\022\017\n\007trip_id\030\001 \001(\t\022\020\n\010route_id"
                        + "\030\005 \001(\t\022\022\n\nstart_time\030\002 \001"
                        + "(\t\022\022\n\nstart_date"
                        + "\030\003 \001(\t\022T\n\025schedule_relationship\030\004 \001(\01625."
                        + "transit_realtime.TripDescriptor.Schedule"
                        + "Relationship\"O\n\024ScheduleRelationship\022\r\n\t"
                        + "SCHEDULED\020\000\022\t\n\005ADDED\020\001\022\017\n\013UNSCHEDULED\020"
                        + "\002\022"
                        + "\014\n\010CANCELED\020\003*\006\010\350\007\020\320\017\"M\n"
                        + "\021VehicleDescript"
                        + "or\022\n\n\002id\030\001 \001(\t\022\r\n\005label\030\002 \001"
                        + "(\t\022\025\n\rlicense" + "_plate\030\003 \001"
                        + "(\t*\006\010\350\007\020\320\017\"\222\001\n\016EntitySelector\022"
                        + "\021\n\tagency_id\030\001 \001(\t\022\020\n\010route_id\030\002 \001"
                        + "(\t\022\022\n\n",
                "route_type\030\003 \001(\005\022.\n\004trip\030\004 \001(\0132 .transit"
                        + "_realtime.TripDescriptor\022\017\n\007stop_id\030\005 \001("
                        + "\t*\006\010\350\007\020\320\017\"\206\001\n\020TranslatedString\022C\n"
                        + "\013transl" + "ation\030\001 \003(\0132..transit_realtime.Translate"
                        + "dString.Translation\032-\n\013Translation\022\014\n\004te"
                        + "xt\030\001 \002(\t\022\020\n\010language\030\002 \001(\tB\"\n\036sen"
                        + ".khyber" + ".subway.client.protoP\001"
        };
        final InternalDescriptorAssigner assigner = new InternalDescriptorAssigner() {
            
            @Override
            public ExtensionRegistry assignDescriptors(final FileDescriptor root) {
                descriptor = root;
                return null;
            }
        };
        FileDescriptor.internalBuildGeneratedFileFrom(descriptorData, new FileDescriptor[] {
        }, assigner);
        internal_static_transit_realtime_FeedMessage_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_transit_realtime_FeedMessage_fieldAccessorTable =
                new FieldAccessorTable(internal_static_transit_realtime_FeedMessage_descriptor,
                        new String[] {"Header", "Entity",});
        internal_static_transit_realtime_FeedHeader_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_transit_realtime_FeedHeader_fieldAccessorTable =
                new FieldAccessorTable(internal_static_transit_realtime_FeedHeader_descriptor,
                        new String[] {"GtfsRealtimeVersion", "Incrementality", "Timestamp",});
        internal_static_transit_realtime_FeedEntity_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_transit_realtime_FeedEntity_fieldAccessorTable =
                new FieldAccessorTable(internal_static_transit_realtime_FeedEntity_descriptor,
                        new String[] {"Id", "IsDeleted", "TripUpdate", "Vehicle", "Alert",});
        internal_static_transit_realtime_TripUpdate_descriptor =
                getDescriptor().getMessageTypes().get(3);
        internal_static_transit_realtime_TripUpdate_fieldAccessorTable =
                new FieldAccessorTable(internal_static_transit_realtime_TripUpdate_descriptor,
                        new String[] {"Trip", "Vehicle", "StopTimeUpdate", "Timestamp",});
        internal_static_transit_realtime_TripUpdate_StopTimeEvent_descriptor =
                internal_static_transit_realtime_TripUpdate_descriptor.getNestedTypes().get(0);
        internal_static_transit_realtime_TripUpdate_StopTimeEvent_fieldAccessorTable =
                new FieldAccessorTable(
                        internal_static_transit_realtime_TripUpdate_StopTimeEvent_descriptor,
                        new String[] {"Delay", "Time", "Uncertainty",});
        internal_static_transit_realtime_TripUpdate_StopTimeUpdate_descriptor =
                internal_static_transit_realtime_TripUpdate_descriptor.getNestedTypes().get(1);
        internal_static_transit_realtime_TripUpdate_StopTimeUpdate_fieldAccessorTable =
                new FieldAccessorTable(
                        internal_static_transit_realtime_TripUpdate_StopTimeUpdate_descriptor,
                        new String[] {
                                "StopSequence", "StopId", "Arrival", "Departure",
                                "ScheduleRelationship",
                        });
        internal_static_transit_realtime_VehiclePosition_descriptor =
                getDescriptor().getMessageTypes().get(4);
        internal_static_transit_realtime_VehiclePosition_fieldAccessorTable =
                new FieldAccessorTable(internal_static_transit_realtime_VehiclePosition_descriptor,
                        new String[] {
                                "Trip", "Vehicle", "Position", "CurrentStopSequence", "StopId",
                                "CurrentStatus", "Timestamp", "CongestionLevel",
                        });
        internal_static_transit_realtime_Alert_descriptor =
                getDescriptor().getMessageTypes().get(5);
        internal_static_transit_realtime_Alert_fieldAccessorTable =
                new FieldAccessorTable(internal_static_transit_realtime_Alert_descriptor,
                        new String[] {
                                "ActivePeriod", "InformedEntity", "Cause", "Effect", "Url",
                                "HeaderText", "DescriptionText",
                        });
        internal_static_transit_realtime_TimeRange_descriptor =
                getDescriptor().getMessageTypes().get(6);
        internal_static_transit_realtime_TimeRange_fieldAccessorTable =
                new FieldAccessorTable(internal_static_transit_realtime_TimeRange_descriptor,
                        new String[] {"Start", "End",});
        internal_static_transit_realtime_Position_descriptor =
                getDescriptor().getMessageTypes().get(7);
        internal_static_transit_realtime_Position_fieldAccessorTable =
                new FieldAccessorTable(internal_static_transit_realtime_Position_descriptor,
                        new String[] {"Latitude", "Longitude", "Bearing", "Odometer", "Speed",});
        internal_static_transit_realtime_TripDescriptor_descriptor =
                getDescriptor().getMessageTypes().get(8);
        internal_static_transit_realtime_TripDescriptor_fieldAccessorTable =
                new FieldAccessorTable(internal_static_transit_realtime_TripDescriptor_descriptor,
                        new String[] {
                                "TripId", "RouteId", "StartTime", "StartDate",
                                "ScheduleRelationship",
                        });
        internal_static_transit_realtime_VehicleDescriptor_descriptor =
                getDescriptor().getMessageTypes().get(9);
        internal_static_transit_realtime_VehicleDescriptor_fieldAccessorTable =
                new FieldAccessorTable(
                        internal_static_transit_realtime_VehicleDescriptor_descriptor,
                        new String[] {"Id", "Label", "LicensePlate",});
        internal_static_transit_realtime_EntitySelector_descriptor =
                getDescriptor().getMessageTypes().get(10);
        internal_static_transit_realtime_EntitySelector_fieldAccessorTable =
                new FieldAccessorTable(internal_static_transit_realtime_EntitySelector_descriptor,
                        new String[] {"AgencyId", "RouteId", "RouteType", "Trip", "StopId",});
        internal_static_transit_realtime_TranslatedString_descriptor =
                getDescriptor().getMessageTypes().get(11);
        internal_static_transit_realtime_TranslatedString_fieldAccessorTable =
                new FieldAccessorTable(internal_static_transit_realtime_TranslatedString_descriptor,
                        new String[] {"Translation",});
        internal_static_transit_realtime_TranslatedString_Translation_descriptor =
                internal_static_transit_realtime_TranslatedString_descriptor.getNestedTypes()
                        .get(0);
        internal_static_transit_realtime_TranslatedString_Translation_fieldAccessorTable =
                new FieldAccessorTable(
                        internal_static_transit_realtime_TranslatedString_Translation_descriptor,
                        new String[] {"Text", "Language",});
    }
    
}