// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gtfs-realtime.proto

package sen.khyber.web.subway.client.proto;

import sen.khyber.proto.ProtoUtils;

import lombok.AccessLevel;
import lombok.Setter;

import java.io.IOException;
import java.io.InputStream;
import java.nio.ByteBuffer;
import java.util.List;
import java.util.Objects;

import com.google.protobuf.AbstractParser;
import com.google.protobuf.ByteString;
import com.google.protobuf.CodedInputStream;
import com.google.protobuf.CodedOutputStream;
import com.google.protobuf.Descriptors.Descriptor;
import com.google.protobuf.Descriptors.EnumDescriptor;
import com.google.protobuf.Descriptors.EnumValueDescriptor;
import com.google.protobuf.Descriptors.FieldDescriptor;
import com.google.protobuf.Descriptors.OneofDescriptor;
import com.google.protobuf.ExtensionRegistryLite;
import com.google.protobuf.GeneratedMessage.GeneratedExtension;
import com.google.protobuf.GeneratedMessageV3;
import com.google.protobuf.GeneratedMessageV3.ExtendableMessage;
import com.google.protobuf.Internal.EnumLiteMap;
import com.google.protobuf.InvalidProtocolBufferException;
import com.google.protobuf.Message;
import com.google.protobuf.Parser;
import com.google.protobuf.ProtocolMessageEnum;
import com.google.protobuf.UnknownFieldSet;

/**
 * <pre>
 * A descriptor that identifies an instance of a GTFS trip, or all instances of
 * a trip along a route.
 * - To specify a single trip instance, the trip_id (and if necessary,
 *   start_time) is set. If route_id is also set, then it should be same as one
 *   that the given trip corresponds to.
 * - To specify all the trips along a given route, only the route_id should be
 *   set. Note that if the trip_id is not known, then stop sequence ids in
 *   TripUpdate are not sufficient, and stop_ids must be provided as well. In
 *   addition, absolute arrival/departure times must be provided.
 * </pre>
 * <p>
 * Protobuf type {@code transit_realtime.TripDescriptor}
 */
public final class TripDescriptor extends ExtendableMessage<TripDescriptor>
        implements TripDescriptorOrBuilder {
    
    private static final long serialVersionUID = 0L;
    
    // Use TripDescriptor.newBuilder() to construct.
    private TripDescriptor(final ExtendableBuilder<TripDescriptor, ?> builder) {
        super(builder);
    }
    
    private TripDescriptor() {
        tripId_ = "";
        routeId_ = "";
        startTime_ = "";
        startDate_ = "";
        scheduleRelationship_ = 0;
    }
    
    @Override
    public final UnknownFieldSet getUnknownFields() {
        return unknownFields;
    }
    
    private TripDescriptor(final CodedInputStream input,
            final ExtensionRegistryLite extensionRegistry) throws InvalidProtocolBufferException {
        this();
        final int mutable_bitField0_ = 0;
        final UnknownFieldSet.Builder unknownFields = UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                final int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        final ByteString bs = input.readBytes();
                        bitField0_ |= 0x00000001;
                        tripId_ = bs;
                        break;
                    }
                    case 18: {
                        final ByteString bs = input.readBytes();
                        bitField0_ |= 0x00000004;
                        startTime_ = bs;
                        break;
                    }
                    case 26: {
                        final ByteString bs = input.readBytes();
                        bitField0_ |= 0x00000008;
                        startDate_ = bs;
                        break;
                    }
                    case 32: {
                        final int rawValue = input.readEnum();
                        final ScheduleRelationship value = ScheduleRelationship.valueOf(rawValue);
                        if (value == null) {
                            unknownFields.mergeVarintField(4, rawValue);
                        } else {
                            bitField0_ |= 0x00000010;
                            scheduleRelationship_ = rawValue;
                        }
                        break;
                    }
                    case 42: {
                        final ByteString bs = input.readBytes();
                        bitField0_ |= 0x00000002;
                        routeId_ = bs;
                        break;
                    }
                }
            }
        } catch (final InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (final IOException e) {
            throw new InvalidProtocolBufferException(e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }
    
    public static final Descriptor getDescriptor() {
        return GtfsRealtime.internal_static_transit_realtime_TripDescriptor_descriptor;
    }
    
    @Override
    protected FieldAccessorTable internalGetFieldAccessorTable() {
        return GtfsRealtime.internal_static_transit_realtime_TripDescriptor_fieldAccessorTable
                .ensureFieldAccessorsInitialized(TripDescriptor.class, Builder.class);
    }
    
    /**
     * <pre>
     * The relation between this trip and the static schedule. If a trip is done
     * in accordance with temporary schedule, not reflected in GTFS, then it
     * shouldn't be marked as SCHEDULED, but likely as ADDED.
     * </pre>
     * <p>
     * Protobuf enum {@code transit_realtime.TripDescriptor.ScheduleRelationship}
     */
    public enum ScheduleRelationship implements ProtocolMessageEnum {
        /**
         * <pre>
         * Trip that is running in accordance with its GTFS schedule, or is close
         * enough to the scheduled trip to be associated with it.
         * </pre>
         * <p>
         * <code>SCHEDULED = 0;</code>
         */
        SCHEDULED(0),
        /**
         * <pre>
         * An extra trip that was added in addition to a running schedule, for
         * example, to replace a broken vehicle or to respond to sudden passenger
         * load.
         * </pre>
         * <p>
         * <code>ADDED = 1;</code>
         */
        ADDED(1),
        /**
         * <pre>
         * A trip that is running with no schedule associated to it, for example, if
         * there is no schedule at all.
         * </pre>
         * <p>
         * <code>UNSCHEDULED = 2;</code>
         */
        UNSCHEDULED(2),
        /**
         * <pre>
         * A trip that existed in the schedule but was removed.
         * </pre>
         * <p>
         * <code>CANCELED = 3;</code>
         */
        CANCELED(3),;
        
        /**
         * <pre>
         * Trip that is running in accordance with its GTFS schedule, or is close
         * enough to the scheduled trip to be associated with it.
         * </pre>
         * <p>
         * <code>SCHEDULED = 0;</code>
         */
        public static final int SCHEDULED_VALUE = 0;
        /**
         * <pre>
         * An extra trip that was added in addition to a running schedule, for
         * example, to replace a broken vehicle or to respond to sudden passenger
         * load.
         * </pre>
         * <p>
         * <code>ADDED = 1;</code>
         */
        public static final int ADDED_VALUE = 1;
        /**
         * <pre>
         * A trip that is running with no schedule associated to it, for example, if
         * there is no schedule at all.
         * </pre>
         * <p>
         * <code>UNSCHEDULED = 2;</code>
         */
        public static final int UNSCHEDULED_VALUE = 2;
        /**
         * <pre>
         * A trip that existed in the schedule but was removed.
         * </pre>
         * <p>
         * <code>CANCELED = 3;</code>
         */
        public static final int CANCELED_VALUE = 3;
        
        
        @Override
        public final int getNumber() {
            return value;
        }
        
        /**
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @Deprecated
        public static ScheduleRelationship valueOf(final int value) {
            return forNumber(value);
        }
        
        public static ScheduleRelationship forNumber(final int value) {
            switch (value) {
                case 0:
                    return SCHEDULED;
                case 1:
                    return ADDED;
                case 2:
                    return UNSCHEDULED;
                case 3:
                    return CANCELED;
                default:
                    return null;
            }
        }
        
        public static EnumLiteMap<ScheduleRelationship> internalGetValueMap() {
            return internalValueMap;
        }
        
        private static final EnumLiteMap<ScheduleRelationship> internalValueMap =
                ScheduleRelationship::forNumber;
        
        @Override
        public final EnumValueDescriptor getValueDescriptor() {
            return getDescriptor().getValues().get(ordinal());
        }
        
        @Override
        public final EnumDescriptor getDescriptorForType() {
            return getDescriptor();
        }
        
        public static final EnumDescriptor getDescriptor() {
            return TripDescriptor.getDescriptor().getEnumTypes().get(0);
        }
        
        private static final ScheduleRelationship[] VALUES = values();
        
        public static ScheduleRelationship valueOf(final EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new IllegalArgumentException("EnumValueDescriptor is not for this type.");
            }
            return VALUES[desc.getIndex()];
        }
        
        private final int value;
        
        ScheduleRelationship(final int value) {
            this.value = value;
        }
        
        // @@protoc_insertion_point(enum_scope:transit_realtime.TripDescriptor.ScheduleRelationship)
    }
    
    private int bitField0_;
    public static final int TRIP_ID_FIELD_NUMBER = 1;
    private volatile @Setter(AccessLevel.PRIVATE) Object tripId_;
    
    /**
     * <pre>
     * The trip_id from the GTFS feed that this selector refers to.
     * For non frequency expanded trips, this field is enough to uniquely identify
     * the trip. For frequency expanded, start_time and start_date might also be
     * necessary.
     * </pre>
     * <p>
     * <code>optional string trip_id = 1;</code>
     */
    @Override
    public boolean hasTripId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    
    /**
     * <pre>
     * The trip_id from the GTFS feed that this selector refers to.
     * For non frequency expanded trips, this field is enough to uniquely identify
     * the trip. For frequency expanded, start_time and start_date might also be
     * necessary.
     * </pre>
     * <p>
     * <code>optional string trip_id = 1;</code>
     */
    @Override
    public String getTripId() {
        return ProtoUtils.asString(tripId_, this::setTripId_);
    }
    
    /**
     * <pre>
     * The trip_id from the GTFS feed that this selector refers to.
     * For non frequency expanded trips, this field is enough to uniquely identify
     * the trip. For frequency expanded, start_time and start_date might also be
     * necessary.
     * </pre>
     * <p>
     * <code>optional string trip_id = 1;</code>
     */
    @Override
    public ByteString getTripIdBytes() {
        return ProtoUtils.asBytes(tripId_, this::setTripId_);
    }
    
    public static final int ROUTE_ID_FIELD_NUMBER = 5;
    @Setter(AccessLevel.PRIVATE) private volatile Object routeId_;
    
    /**
     * <pre>
     * The route_id from the GTFS that this selector refers to.
     * </pre>
     * <p>
     * <code>optional string route_id = 5;</code>
     */
    @Override
    public boolean hasRouteId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    
    /**
     * <pre>
     * The route_id from the GTFS that this selector refers to.
     * </pre>
     * <p>
     * <code>optional string route_id = 5;</code>
     */
    @Override
    public String getRouteId() {
        return ProtoUtils.asString(routeId_, this::setRouteId_);
    }
    
    /**
     * <pre>
     * The route_id from the GTFS that this selector refers to.
     * </pre>
     * <p>
     * <code>optional string route_id = 5;</code>
     */
    @Override
    public ByteString getRouteIdBytes() {
        return ProtoUtils.asBytes(routeId_, this::setRouteId_);
    }
    
    public static final int START_TIME_FIELD_NUMBER = 2;
    @Setter(AccessLevel.PRIVATE) private volatile Object startTime_;
    
    /**
     * <pre>
     * The scheduled start time of this trip instance.
     * This field should be given only if the trip is frequency-expanded in the
     * GTFS feed. The value must precisely correspond to start_time specified for
     * the route in the GTFS feed plus some multiple of headway_secs.
     * Format of the field is same as that of GTFS/frequencies.txt/start_time,
     * e.g., 11:15:35 or 25:15:35.
     * </pre>
     * <p>
     * <code>optional string start_time = 2;</code>
     */
    @Override
    public boolean hasStartTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    
    /**
     * <pre>
     * The scheduled start time of this trip instance.
     * This field should be given only if the trip is frequency-expanded in the
     * GTFS feed. The value must precisely correspond to start_time specified for
     * the route in the GTFS feed plus some multiple of headway_secs.
     * Format of the field is same as that of GTFS/frequencies.txt/start_time,
     * e.g., 11:15:35 or 25:15:35.
     * </pre>
     * <p>
     * <code>optional string start_time = 2;</code>
     */
    @Override
    public String getStartTime() {
        return ProtoUtils.asString(startTime_, this::setStartTime_);
    }
    
    /**
     * <pre>
     * The scheduled start time of this trip instance.
     * This field should be given only if the trip is frequency-expanded in the
     * GTFS feed. The value must precisely correspond to start_time specified for
     * the route in the GTFS feed plus some multiple of headway_secs.
     * Format of the field is same as that of GTFS/frequencies.txt/start_time,
     * e.g., 11:15:35 or 25:15:35.
     * </pre>
     * <p>
     * <code>optional string start_time = 2;</code>
     */
    @Override
    public ByteString getStartTimeBytes() {
        return ProtoUtils.asBytes(startTime_, this::setStartTime_);
    }
    
    public static final int START_DATE_FIELD_NUMBER = 3;
    @Setter(AccessLevel.PRIVATE) private volatile Object startDate_;
    
    /**
     * <pre>
     * The scheduled start date of this trip instance.
     * Must be provided to disambiguate trips that are so late as to collide with
     * a scheduled trip on a next day. For example, for a train that departs 8:00
     * and 20:00 every day, and is 12 hours late, there would be two distinct
     * trips on the same time.
     * This field can be provided but is not mandatory for schedules in which such
     * collisions are impossible - for example, a service running on hourly
     * schedule where a vehicle that is one hour late is not considered to be
     * related to schedule anymore.
     * In YYYYMMDD format.
     * </pre>
     * <p>
     * <code>optional string start_date = 3;</code>
     */
    @Override
    public boolean hasStartDate() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    
    /**
     * <pre>
     * The scheduled start date of this trip instance.
     * Must be provided to disambiguate trips that are so late as to collide with
     * a scheduled trip on a next day. For example, for a train that departs 8:00
     * and 20:00 every day, and is 12 hours late, there would be two distinct
     * trips on the same time.
     * This field can be provided but is not mandatory for schedules in which such
     * collisions are impossible - for example, a service running on hourly
     * schedule where a vehicle that is one hour late is not considered to be
     * related to schedule anymore.
     * In YYYYMMDD format.
     * </pre>
     * <p>
     * <code>optional string start_date = 3;</code>
     */
    @Override
    public String getStartDate() {
        return ProtoUtils.asString(startDate_, this::setStartDate_);
    }
    
    /**
     * <pre>
     * The scheduled start date of this trip instance.
     * Must be provided to disambiguate trips that are so late as to collide with
     * a scheduled trip on a next day. For example, for a train that departs 8:00
     * and 20:00 every day, and is 12 hours late, there would be two distinct
     * trips on the same time.
     * This field can be provided but is not mandatory for schedules in which such
     * collisions are impossible - for example, a service running on hourly
     * schedule where a vehicle that is one hour late is not considered to be
     * related to schedule anymore.
     * In YYYYMMDD format.
     * </pre>
     * <p>
     * <code>optional string start_date = 3;</code>
     */
    @Override
    public ByteString getStartDateBytes() {
        return ProtoUtils.asBytes(startDate_, this::setStartDate_);
    }
    
    public static final int SCHEDULE_RELATIONSHIP_FIELD_NUMBER = 4;
    private int scheduleRelationship_;
    
    /**
     * <code>optional .transit_realtime.TripDescriptor.ScheduleRelationship schedule_relationship
     * = 4;</code>
     */
    @Override
    public boolean hasScheduleRelationship() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    
    /**
     * <code>optional .transit_realtime.TripDescriptor.ScheduleRelationship schedule_relationship
     * = 4;</code>
     */
    @Override
    public ScheduleRelationship getScheduleRelationship() {
        final ScheduleRelationship result = ScheduleRelationship.valueOf(scheduleRelationship_);
        return result == null ? ScheduleRelationship.SCHEDULED : result;
    }
    
    private byte memoizedIsInitialized = -1;
    
    @Override
    public final boolean isInitialized() {
        final byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) {return true;}
        if (isInitialized == 0) {return false;}
        
        if (!extensionsAreInitialized()) {
            memoizedIsInitialized = 0;
            return false;
        }
        memoizedIsInitialized = 1;
        return true;
    }
    
    @Override
    public void writeTo(final CodedOutputStream output) throws IOException {
        final ExtendableMessage<TripDescriptor>.ExtensionWriter extensionWriter =
                newExtensionWriter();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
            GeneratedMessageV3.writeString(output, 1, tripId_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
            GeneratedMessageV3.writeString(output, 2, startTime_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
            GeneratedMessageV3.writeString(output, 3, startDate_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
            output.writeEnum(4, scheduleRelationship_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
            GeneratedMessageV3.writeString(output, 5, routeId_);
        }
        extensionWriter.writeUntil(2000, output);
        unknownFields.writeTo(output);
    }
    
    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) {return size;}
        
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
            size += GeneratedMessageV3.computeStringSize(1, tripId_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
            size += GeneratedMessageV3.computeStringSize(2, startTime_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
            size += GeneratedMessageV3.computeStringSize(3, startDate_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
            size += CodedOutputStream.computeEnumSize(4, scheduleRelationship_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
            size += GeneratedMessageV3.computeStringSize(5, routeId_);
        }
        size += extensionsSerializedSize();
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }
    
    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof TripDescriptor)) {
            return super.equals(obj);
        }
        final TripDescriptor other = (TripDescriptor) obj;
        
        boolean result = true;
        result = result && (hasTripId() == other.hasTripId());
        if (hasTripId()) {
            result = result && getTripId().equals(other.getTripId());
        }
        result = result && (hasRouteId() == other.hasRouteId());
        if (hasRouteId()) {
            result = result && getRouteId().equals(other.getRouteId());
        }
        result = result && (hasStartTime() == other.hasStartTime());
        if (hasStartTime()) {
            result = result && getStartTime().equals(other.getStartTime());
        }
        result = result && (hasStartDate() == other.hasStartDate());
        if (hasStartDate()) {
            result = result && getStartDate().equals(other.getStartDate());
        }
        result = result && (hasScheduleRelationship() == other.hasScheduleRelationship());
        if (hasScheduleRelationship()) {
            result = result && scheduleRelationship_ == other.scheduleRelationship_;
        }
        result = result && unknownFields.equals(other.unknownFields);
        result = result && getExtensionFields().equals(other.getExtensionFields());
        return result;
    }
    
    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasTripId()) {
            hash = (37 * hash) + TRIP_ID_FIELD_NUMBER;
            hash = (53 * hash) + getTripId().hashCode();
        }
        if (hasRouteId()) {
            hash = (37 * hash) + ROUTE_ID_FIELD_NUMBER;
            hash = (53 * hash) + getRouteId().hashCode();
        }
        if (hasStartTime()) {
            hash = (37 * hash) + START_TIME_FIELD_NUMBER;
            hash = (53 * hash) + getStartTime().hashCode();
        }
        if (hasStartDate()) {
            hash = (37 * hash) + START_DATE_FIELD_NUMBER;
            hash = (53 * hash) + getStartDate().hashCode();
        }
        if (hasScheduleRelationship()) {
            hash = (37 * hash) + SCHEDULE_RELATIONSHIP_FIELD_NUMBER;
            hash = (53 * hash) + scheduleRelationship_;
        }
        hash = hashFields(hash, getExtensionFields());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }
    
    public static TripDescriptor parseFrom(final ByteBuffer data)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    
    public static TripDescriptor parseFrom(final ByteBuffer data,
            final ExtensionRegistryLite extensionRegistry) throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    
    public static TripDescriptor parseFrom(final ByteString data)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    
    public static TripDescriptor parseFrom(final ByteString data,
            final ExtensionRegistryLite extensionRegistry) throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    
    public static TripDescriptor parseFrom(final byte[] data)
            throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    
    public static TripDescriptor parseFrom(final byte[] data,
            final ExtensionRegistryLite extensionRegistry) throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    
    public static TripDescriptor parseFrom(final InputStream input) throws IOException {
        return GeneratedMessageV3.parseWithIOException(PARSER, input);
    }
    
    public static TripDescriptor parseFrom(final InputStream input,
            final ExtensionRegistryLite extensionRegistry) throws IOException {
        return GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }
    
    public static TripDescriptor parseDelimitedFrom(final InputStream input) throws IOException {
        return GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }
    
    public static TripDescriptor parseDelimitedFrom(final InputStream input,
            final ExtensionRegistryLite extensionRegistry) throws IOException {
        return GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    
    public static TripDescriptor parseFrom(final CodedInputStream input) throws IOException {
        return GeneratedMessageV3.parseWithIOException(PARSER, input);
    }
    
    public static TripDescriptor parseFrom(final CodedInputStream input,
            final ExtensionRegistryLite extensionRegistry) throws IOException {
        return GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }
    
    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    
    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }
    
    public static Builder newBuilder(final TripDescriptor prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    
    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }
    
    @Override
    protected Builder newBuilderForType(final BuilderParent parent) {
        final Builder builder = new Builder(parent);
        return builder;
    }
    
    /**
     * <pre>
     * A descriptor that identifies an instance of a GTFS trip, or all instances of
     * a trip along a route.
     * - To specify a single trip instance, the trip_id (and if necessary,
     *   start_time) is set. If route_id is also set, then it should be same as one
     *   that the given trip corresponds to.
     * - To specify all the trips along a given route, only the route_id should be
     *   set. Note that if the trip_id is not known, then stop sequence ids in
     *   TripUpdate are not sufficient, and stop_ids must be provided as well. In
     *   addition, absolute arrival/departure times must be provided.
     * </pre>
     * <p>
     * Protobuf type {@code transit_realtime.TripDescriptor}
     */
    public static final class Builder extends ExtendableBuilder<TripDescriptor, Builder> implements
            // @@protoc_insertion_point(builder_implements:transit_realtime.TripDescriptor)
            TripDescriptorOrBuilder {
        
        public static final Descriptor getDescriptor() {
            return GtfsRealtime.internal_static_transit_realtime_TripDescriptor_descriptor;
        }
        
        @Override
        protected FieldAccessorTable internalGetFieldAccessorTable() {
            return GtfsRealtime.internal_static_transit_realtime_TripDescriptor_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(TripDescriptor.class, Builder.class);
        }
        
        // Construct using sen.khyber.subway.client.proto.TripDescriptor.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }
        
        private Builder(final BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }
        
        private void maybeForceBuilderInitialization() {
            if (GeneratedMessageV3.alwaysUseFieldBuilders) {
            }
        }
        
        @Override
        public Builder clear() {
            super.clear();
            tripId_ = "";
            bitField0_ = (bitField0_ & ~0x00000001);
            routeId_ = "";
            bitField0_ = (bitField0_ & ~0x00000002);
            startTime_ = "";
            bitField0_ = (bitField0_ & ~0x00000004);
            startDate_ = "";
            bitField0_ = (bitField0_ & ~0x00000008);
            scheduleRelationship_ = 0;
            bitField0_ = (bitField0_ & ~0x00000010);
            return this;
        }
        
        @Override
        public Descriptor getDescriptorForType() {
            return GtfsRealtime.internal_static_transit_realtime_TripDescriptor_descriptor;
        }
        
        @Override
        public TripDescriptor getDefaultInstanceForType() {
            return getDefaultInstance();
        }
        
        @Override
        public TripDescriptor build() {
            final TripDescriptor result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }
        
        @Override
        public TripDescriptor buildPartial() {
            final TripDescriptor result = new TripDescriptor(this);
            final int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                to_bitField0_ |= 0x00000001;
            }
            result.tripId_ = tripId_;
            if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                to_bitField0_ |= 0x00000002;
            }
            result.routeId_ = routeId_;
            if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                to_bitField0_ |= 0x00000004;
            }
            result.startTime_ = startTime_;
            if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                to_bitField0_ |= 0x00000008;
            }
            result.startDate_ = startDate_;
            if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
                to_bitField0_ |= 0x00000010;
            }
            result.scheduleRelationship_ = scheduleRelationship_;
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
        }
        
        @Override
        public Builder clone() {
            return super.clone();
        }
        
        @Override
        public Builder setField(final FieldDescriptor field, final Object value) {
            return super.setField(field, value);
        }
        
        @Override
        public Builder clearField(final FieldDescriptor field) {
            return super.clearField(field);
        }
        
        @Override
        public Builder clearOneof(final OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }
        
        @Override
        public Builder setRepeatedField(final FieldDescriptor field, final int index,
                final Object value) {
            return super.setRepeatedField(field, index, value);
        }
        
        @Override
        public Builder addRepeatedField(final FieldDescriptor field, final Object value) {
            return super.addRepeatedField(field, value);
        }
        
        @Override
        public <Type> Builder setExtension(final GeneratedExtension<TripDescriptor, Type> extension,
                final Type value) {
            return super.setExtension(extension, value);
        }
        
        @Override
        public <Type> Builder setExtension(
                final GeneratedExtension<TripDescriptor, List<Type>> extension, final int index,
                final Type value) {
            return super.setExtension(extension, index, value);
        }
        
        @Override
        public <Type> Builder addExtension(
                final GeneratedExtension<TripDescriptor, List<Type>> extension, final Type value) {
            return super.addExtension(extension, value);
        }
        
        @Override
        public <Type> Builder clearExtension(
                final GeneratedExtension<TripDescriptor, ?> extension) {
            return super.clearExtension(extension);
        }
        
        @Override
        public Builder mergeFrom(final Message other) {
            if (other instanceof TripDescriptor) {
                return mergeFrom((TripDescriptor) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }
        
        public Builder mergeFrom(final TripDescriptor other) {
            if (other == getDefaultInstance()) {return this;}
            if (other.hasTripId()) {
                bitField0_ |= 0x00000001;
                tripId_ = other.tripId_;
                onChanged();
            }
            if (other.hasRouteId()) {
                bitField0_ |= 0x00000002;
                routeId_ = other.routeId_;
                onChanged();
            }
            if (other.hasStartTime()) {
                bitField0_ |= 0x00000004;
                startTime_ = other.startTime_;
                onChanged();
            }
            if (other.hasStartDate()) {
                bitField0_ |= 0x00000008;
                startDate_ = other.startDate_;
                onChanged();
            }
            if (other.hasScheduleRelationship()) {
                setScheduleRelationship(other.getScheduleRelationship());
            }
            mergeExtensionFields(other);
            mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }
        
        @Override
        public final boolean isInitialized() {
            return extensionsAreInitialized();
        }
        
        @Override
        public Builder mergeFrom(final CodedInputStream input,
                final ExtensionRegistryLite extensionRegistry) throws IOException {
            TripDescriptor parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (final InvalidProtocolBufferException e) {
                parsedMessage = (TripDescriptor) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }
        
        private int bitField0_;
        
        @Setter(AccessLevel.PRIVATE) private Object tripId_ = "";
        
        /**
         * <pre>
         * The trip_id from the GTFS feed that this selector refers to.
         * For non frequency expanded trips, this field is enough to uniquely identify
         * the trip. For frequency expanded, start_time and start_date might also be
         * necessary.
         * </pre>
         * <p>
         * <code>optional string trip_id = 1;</code>
         */
        @Override
        public boolean hasTripId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        
        /**
         * <pre>
         * The trip_id from the GTFS feed that this selector refers to.
         * For non frequency expanded trips, this field is enough to uniquely identify
         * the trip. For frequency expanded, start_time and start_date might also be
         * necessary.
         * </pre>
         * <p>
         * <code>optional string trip_id = 1;</code>
         */
        @Override
        public String getTripId() {
            return ProtoUtils.asString(tripId_, this::setTripId_);
        }
        
        /**
         * <pre>
         * The trip_id from the GTFS feed that this selector refers to.
         * For non frequency expanded trips, this field is enough to uniquely identify
         * the trip. For frequency expanded, start_time and start_date might also be
         * necessary.
         * </pre>
         * <p>
         * <code>optional string trip_id = 1;</code>
         */
        @Override
        public ByteString getTripIdBytes() {
            return ProtoUtils.asBytes(tripId_, this::setTripId_);
        }
        
        /**
         * <pre>
         * The trip_id from the GTFS feed that this selector refers to.
         * For non frequency expanded trips, this field is enough to uniquely identify
         * the trip. For frequency expanded, start_time and start_date might also be
         * necessary.
         * </pre>
         * <p>
         * <code>optional string trip_id = 1;</code>
         */
        public Builder setTripId(final String value) {
            Objects.requireNonNull(value);
            bitField0_ |= 0x00000001;
            tripId_ = value;
            onChanged();
            return this;
        }
        
        /**
         * <pre>
         * The trip_id from the GTFS feed that this selector refers to.
         * For non frequency expanded trips, this field is enough to uniquely identify
         * the trip. For frequency expanded, start_time and start_date might also be
         * necessary.
         * </pre>
         * <p>
         * <code>optional string trip_id = 1;</code>
         */
        public Builder clearTripId() {
            bitField0_ = (bitField0_ & ~0x00000001);
            tripId_ = getDefaultInstance().getTripId();
            onChanged();
            return this;
        }
        
        /**
         * <pre>
         * The trip_id from the GTFS feed that this selector refers to.
         * For non frequency expanded trips, this field is enough to uniquely identify
         * the trip. For frequency expanded, start_time and start_date might also be
         * necessary.
         * </pre>
         * <p>
         * <code>optional string trip_id = 1;</code>
         */
        public Builder setTripIdBytes(final ByteString value) {
            Objects.requireNonNull(value);
            bitField0_ |= 0x00000001;
            tripId_ = value;
            onChanged();
            return this;
        }
        
        @Setter(AccessLevel.PRIVATE) private Object routeId_ = "";
        
        /**
         * <pre>
         * The route_id from the GTFS that this selector refers to.
         * </pre>
         * <p>
         * <code>optional string route_id = 5;</code>
         */
        @Override
        public boolean hasRouteId() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        
        /**
         * <pre>
         * The route_id from the GTFS that this selector refers to.
         * </pre>
         * <p>
         * <code>optional string route_id = 5;</code>
         */
        @Override
        public String getRouteId() {
            return ProtoUtils.asString(routeId_, this::setRouteId_);
        }
        
        /**
         * <pre>
         * The route_id from the GTFS that this selector refers to.
         * </pre>
         * <p>
         * <code>optional string route_id = 5;</code>
         */
        @Override
        public ByteString getRouteIdBytes() {
            return ProtoUtils.asBytes(routeId_, this::setRouteId_);
        }
        
        /**
         * <pre>
         * The route_id from the GTFS that this selector refers to.
         * </pre>
         * <p>
         * <code>optional string route_id = 5;</code>
         */
        public Builder setRouteId(final String value) {
            Objects.requireNonNull(value);
            bitField0_ |= 0x00000002;
            routeId_ = value;
            onChanged();
            return this;
        }
        
        /**
         * <pre>
         * The route_id from the GTFS that this selector refers to.
         * </pre>
         * <p>
         * <code>optional string route_id = 5;</code>
         */
        public Builder clearRouteId() {
            bitField0_ = (bitField0_ & ~0x00000002);
            routeId_ = getDefaultInstance().getRouteId();
            onChanged();
            return this;
        }
        
        /**
         * <pre>
         * The route_id from the GTFS that this selector refers to.
         * </pre>
         * <p>
         * <code>optional string route_id = 5;</code>
         */
        public Builder setRouteIdBytes(final ByteString value) {
            Objects.requireNonNull(value);
            bitField0_ |= 0x00000002;
            routeId_ = value;
            onChanged();
            return this;
        }
        
        @Setter(AccessLevel.PRIVATE) private Object startTime_ = "";
        
        /**
         * <pre>
         * The scheduled start time of this trip instance.
         * This field should be given only if the trip is frequency-expanded in the
         * GTFS feed. The value must precisely correspond to start_time specified for
         * the route in the GTFS feed plus some multiple of headway_secs.
         * Format of the field is same as that of GTFS/frequencies.txt/start_time,
         * e.g., 11:15:35 or 25:15:35.
         * </pre>
         * <p>
         * <code>optional string start_time = 2;</code>
         */
        @Override
        public boolean hasStartTime() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        
        /**
         * <pre>
         * The scheduled start time of this trip instance.
         * This field should be given only if the trip is frequency-expanded in the
         * GTFS feed. The value must precisely correspond to start_time specified for
         * the route in the GTFS feed plus some multiple of headway_secs.
         * Format of the field is same as that of GTFS/frequencies.txt/start_time,
         * e.g., 11:15:35 or 25:15:35.
         * </pre>
         * <p>
         * <code>optional string start_time = 2;</code>
         */
        @Override
        public String getStartTime() {
            return ProtoUtils.asString(startTime_, this::setStartTime_);
        }
        
        /**
         * <pre>
         * The scheduled start time of this trip instance.
         * This field should be given only if the trip is frequency-expanded in the
         * GTFS feed. The value must precisely correspond to start_time specified for
         * the route in the GTFS feed plus some multiple of headway_secs.
         * Format of the field is same as that of GTFS/frequencies.txt/start_time,
         * e.g., 11:15:35 or 25:15:35.
         * </pre>
         * <p>
         * <code>optional string start_time = 2;</code>
         */
        @Override
        public ByteString getStartTimeBytes() {
            return ProtoUtils.asBytes(startTime_, this::setStartTime_);
        }
        
        /**
         * <pre>
         * The scheduled start time of this trip instance.
         * This field should be given only if the trip is frequency-expanded in the
         * GTFS feed. The value must precisely correspond to start_time specified for
         * the route in the GTFS feed plus some multiple of headway_secs.
         * Format of the field is same as that of GTFS/frequencies.txt/start_time,
         * e.g., 11:15:35 or 25:15:35.
         * </pre>
         * <p>
         * <code>optional string start_time = 2;</code>
         */
        public Builder setStartTime(final String value) {
            Objects.requireNonNull(value);
            bitField0_ |= 0x00000004;
            startTime_ = value;
            onChanged();
            return this;
        }
        
        /**
         * <pre>
         * The scheduled start time of this trip instance.
         * This field should be given only if the trip is frequency-expanded in the
         * GTFS feed. The value must precisely correspond to start_time specified for
         * the route in the GTFS feed plus some multiple of headway_secs.
         * Format of the field is same as that of GTFS/frequencies.txt/start_time,
         * e.g., 11:15:35 or 25:15:35.
         * </pre>
         * <p>
         * <code>optional string start_time = 2;</code>
         */
        public Builder clearStartTime() {
            bitField0_ = (bitField0_ & ~0x00000004);
            startTime_ = getDefaultInstance().getStartTime();
            onChanged();
            return this;
        }
        
        /**
         * <pre>
         * The scheduled start time of this trip instance.
         * This field should be given only if the trip is frequency-expanded in the
         * GTFS feed. The value must precisely correspond to start_time specified for
         * the route in the GTFS feed plus some multiple of headway_secs.
         * Format of the field is same as that of GTFS/frequencies.txt/start_time,
         * e.g., 11:15:35 or 25:15:35.
         * </pre>
         * <p>
         * <code>optional string start_time = 2;</code>
         */
        public Builder setStartTimeBytes(final ByteString value) {
            Objects.requireNonNull(value);
            bitField0_ |= 0x00000004;
            startTime_ = value;
            onChanged();
            return this;
        }
        
        @Setter(AccessLevel.PRIVATE) private Object startDate_ = "";
        
        /**
         * <pre>
         * The scheduled start date of this trip instance.
         * Must be provided to disambiguate trips that are so late as to collide with
         * a scheduled trip on a next day. For example, for a train that departs 8:00
         * and 20:00 every day, and is 12 hours late, there would be two distinct
         * trips on the same time.
         * This field can be provided but is not mandatory for schedules in which such
         * collisions are impossible - for example, a service running on hourly
         * schedule where a vehicle that is one hour late is not considered to be
         * related to schedule anymore.
         * In YYYYMMDD format.
         * </pre>
         * <p>
         * <code>optional string start_date = 3;</code>
         */
        @Override
        public boolean hasStartDate() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        
        /**
         * <pre>
         * The scheduled start date of this trip instance.
         * Must be provided to disambiguate trips that are so late as to collide with
         * a scheduled trip on a next day. For example, for a train that departs 8:00
         * and 20:00 every day, and is 12 hours late, there would be two distinct
         * trips on the same time.
         * This field can be provided but is not mandatory for schedules in which such
         * collisions are impossible - for example, a service running on hourly
         * schedule where a vehicle that is one hour late is not considered to be
         * related to schedule anymore.
         * In YYYYMMDD format.
         * </pre>
         * <p>
         * <code>optional string start_date = 3;</code>
         */
        @Override
        public String getStartDate() {
            return ProtoUtils.asString(startDate_, this::setStartDate_);
        }
        
        /**
         * <pre>
         * The scheduled start date of this trip instance.
         * Must be provided to disambiguate trips that are so late as to collide with
         * a scheduled trip on a next day. For example, for a train that departs 8:00
         * and 20:00 every day, and is 12 hours late, there would be two distinct
         * trips on the same time.
         * This field can be provided but is not mandatory for schedules in which such
         * collisions are impossible - for example, a service running on hourly
         * schedule where a vehicle that is one hour late is not considered to be
         * related to schedule anymore.
         * In YYYYMMDD format.
         * </pre>
         * <p>
         * <code>optional string start_date = 3;</code>
         */
        @Override
        public ByteString getStartDateBytes() {
            return ProtoUtils.asBytes(startDate_, this::setStartDate_);
        }
        
        /**
         * <pre>
         * The scheduled start date of this trip instance.
         * Must be provided to disambiguate trips that are so late as to collide with
         * a scheduled trip on a next day. For example, for a train that departs 8:00
         * and 20:00 every day, and is 12 hours late, there would be two distinct
         * trips on the same time.
         * This field can be provided but is not mandatory for schedules in which such
         * collisions are impossible - for example, a service running on hourly
         * schedule where a vehicle that is one hour late is not considered to be
         * related to schedule anymore.
         * In YYYYMMDD format.
         * </pre>
         * <p>
         * <code>optional string start_date = 3;</code>
         */
        public Builder setStartDate(final String value) {
            Objects.requireNonNull(value);
            bitField0_ |= 0x00000008;
            startDate_ = value;
            onChanged();
            return this;
        }
        
        /**
         * <pre>
         * The scheduled start date of this trip instance.
         * Must be provided to disambiguate trips that are so late as to collide with
         * a scheduled trip on a next day. For example, for a train that departs 8:00
         * and 20:00 every day, and is 12 hours late, there would be two distinct
         * trips on the same time.
         * This field can be provided but is not mandatory for schedules in which such
         * collisions are impossible - for example, a service running on hourly
         * schedule where a vehicle that is one hour late is not considered to be
         * related to schedule anymore.
         * In YYYYMMDD format.
         * </pre>
         * <p>
         * <code>optional string start_date = 3;</code>
         */
        public Builder clearStartDate() {
            bitField0_ = (bitField0_ & ~0x00000008);
            startDate_ = getDefaultInstance().getStartDate();
            onChanged();
            return this;
        }
        
        /**
         * <pre>
         * The scheduled start date of this trip instance.
         * Must be provided to disambiguate trips that are so late as to collide with
         * a scheduled trip on a next day. For example, for a train that departs 8:00
         * and 20:00 every day, and is 12 hours late, there would be two distinct
         * trips on the same time.
         * This field can be provided but is not mandatory for schedules in which such
         * collisions are impossible - for example, a service running on hourly
         * schedule where a vehicle that is one hour late is not considered to be
         * related to schedule anymore.
         * In YYYYMMDD format.
         * </pre>
         * <p>
         * <code>optional string start_date = 3;</code>
         */
        public Builder setStartDateBytes(final ByteString value) {
            Objects.requireNonNull(value);
            bitField0_ |= 0x00000008;
            startDate_ = value;
            onChanged();
            return this;
        }
        
        private int scheduleRelationship_ = 0;
        
        /**
         * <code>optional .transit_realtime.TripDescriptor.ScheduleRelationship
         * schedule_relationship
         * = 4;</code>
         */
        @Override
        public boolean hasScheduleRelationship() {
            return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        
        /**
         * <code>optional .transit_realtime.TripDescriptor.ScheduleRelationship
         * schedule_relationship = 4;</code>
         */
        @Override
        public ScheduleRelationship getScheduleRelationship() {
            final ScheduleRelationship result = ScheduleRelationship.valueOf(scheduleRelationship_);
            return result == null ? ScheduleRelationship.SCHEDULED : result;
        }
        
        /**
         * <code>optional .transit_realtime.TripDescriptor.ScheduleRelationship
         * schedule_relationship
         * = 4;</code>
         */
        public Builder setScheduleRelationship(final ScheduleRelationship value) {
            Objects.requireNonNull(value);
            bitField0_ |= 0x00000010;
            scheduleRelationship_ = value.getNumber();
            onChanged();
            return this;
        }
        
        /**
         * <code>optional .transit_realtime.TripDescriptor.ScheduleRelationship
         * schedule_relationship = 4;</code>
         */
        public Builder clearScheduleRelationship() {
            bitField0_ = (bitField0_ & ~0x00000010);
            scheduleRelationship_ = 0;
            onChanged();
            return this;
        }
        
        @Override
        public final Builder setUnknownFields(final UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }
        
        @Override
        public final Builder mergeUnknownFields(final UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }
        
        
        // @@protoc_insertion_point(builder_scope:transit_realtime.TripDescriptor)
    }
    
    // @@protoc_insertion_point(class_scope:transit_realtime.TripDescriptor)
    private static final TripDescriptor DEFAULT_INSTANCE;
    
    static {
        DEFAULT_INSTANCE = new TripDescriptor();
    }
    
    public static TripDescriptor getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }
    
    @Deprecated public static final Parser<TripDescriptor> PARSER = new AbstractParser<>() {
        
        @Override
        public TripDescriptor parsePartialFrom(final CodedInputStream input,
                final ExtensionRegistryLite extensionRegistry)
                throws InvalidProtocolBufferException {
            return new TripDescriptor(input, extensionRegistry);
        }
    };
    
    public static Parser<TripDescriptor> parser() {
        return PARSER;
    }
    
    @Override
    public Parser<TripDescriptor> getParserForType() {
        return PARSER;
    }
    
    @Override
    public TripDescriptor getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }
    
}