// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gtfs-realtime.proto

package sen.khyber.web.subway.client.proto;

/**
 * <pre>
 * Identification information for the vehicle performing the trip.
 * </pre>
 * <p>
 * Protobuf type {@code transit_realtime.VehicleDescriptor}
 */
public final class VehicleDescriptor extends
        com.google.protobuf.GeneratedMessageV3.ExtendableMessage<
                VehicleDescriptor> implements
        // @@protoc_insertion_point(message_implements:transit_realtime.VehicleDescriptor)
        VehicleDescriptorOrBuilder {
    
    private static final long serialVersionUID = 0L;
    
    // Use VehicleDescriptor.newBuilder() to construct.
    private VehicleDescriptor(
            final com.google.protobuf.GeneratedMessageV3.ExtendableBuilder<VehicleDescriptor, ?>
                    builder) {
        super(builder);
    }
    
    private VehicleDescriptor() {
        id_ = "";
        label_ = "";
        licensePlate_ = "";
    }
    
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return unknownFields;
    }
    
    private VehicleDescriptor(
            final com.google.protobuf.CodedInputStream input,
            final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        final int mutable_bitField0_ = 0;
        final com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                final int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        final com.google.protobuf.ByteString bs = input.readBytes();
                        bitField0_ |= 0x00000001;
                        id_ = bs;
                        break;
                    }
                    case 18: {
                        final com.google.protobuf.ByteString bs = input.readBytes();
                        bitField0_ |= 0x00000002;
                        label_ = bs;
                        break;
                    }
                    case 26: {
                        final com.google.protobuf.ByteString bs = input.readBytes();
                        bitField0_ |= 0x00000004;
                        licensePlate_ = bs;
                        break;
                    }
                }
            }
        } catch (final com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (final java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return GtfsRealtime.internal_static_transit_realtime_VehicleDescriptor_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return GtfsRealtime.internal_static_transit_realtime_VehicleDescriptor_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        VehicleDescriptor.class, VehicleDescriptor.Builder.class);
    }
    
    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    
    /**
     * <pre>
     * Internal system identification of the vehicle. Should be unique per
     * vehicle, and can be used for tracking the vehicle as it proceeds through
     * the system.
     * </pre>
     * <p>
     * <code>optional string id = 1;</code>
     */
    @Override
    public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    
    /**
     * <pre>
     * Internal system identification of the vehicle. Should be unique per
     * vehicle, and can be used for tracking the vehicle as it proceeds through
     * the system.
     * </pre>
     * <p>
     * <code>optional string id = 1;</code>
     */
    @Override
    public java.lang.String getId() {
        final java.lang.Object ref = id_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            final com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            final java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
                id_ = s;
            }
            return s;
        }
    }
    
    /**
     * <pre>
     * Internal system identification of the vehicle. Should be unique per
     * vehicle, and can be used for tracking the vehicle as it proceeds through
     * the system.
     * </pre>
     * <p>
     * <code>optional string id = 1;</code>
     */
    @Override
    public com.google.protobuf.ByteString
    getIdBytes() {
        final java.lang.Object ref = id_;
        if (ref instanceof java.lang.String) {
            final com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            id_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }
    
    public static final int LABEL_FIELD_NUMBER = 2;
    private volatile java.lang.Object label_;
    
    /**
     * <pre>
     * User visible label, i.e., something that must be shown to the passenger to
     * help identify the correct vehicle.
     * </pre>
     * <p>
     * <code>optional string label = 2;</code>
     */
    @Override
    public boolean hasLabel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    
    /**
     * <pre>
     * User visible label, i.e., something that must be shown to the passenger to
     * help identify the correct vehicle.
     * </pre>
     * <p>
     * <code>optional string label = 2;</code>
     */
    @Override
    public java.lang.String getLabel() {
        final java.lang.Object ref = label_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            final com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            final java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
                label_ = s;
            }
            return s;
        }
    }
    
    /**
     * <pre>
     * User visible label, i.e., something that must be shown to the passenger to
     * help identify the correct vehicle.
     * </pre>
     * <p>
     * <code>optional string label = 2;</code>
     */
    @Override
    public com.google.protobuf.ByteString
    getLabelBytes() {
        final java.lang.Object ref = label_;
        if (ref instanceof java.lang.String) {
            final com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            label_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }
    
    public static final int LICENSE_PLATE_FIELD_NUMBER = 3;
    private volatile java.lang.Object licensePlate_;
    
    /**
     * <pre>
     * The license plate of the vehicle.
     * </pre>
     * <p>
     * <code>optional string license_plate = 3;</code>
     */
    @Override
    public boolean hasLicensePlate() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    
    /**
     * <pre>
     * The license plate of the vehicle.
     * </pre>
     * <p>
     * <code>optional string license_plate = 3;</code>
     */
    @Override
    public java.lang.String getLicensePlate() {
        final java.lang.Object ref = licensePlate_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            final com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            final java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
                licensePlate_ = s;
            }
            return s;
        }
    }
    
    /**
     * <pre>
     * The license plate of the vehicle.
     * </pre>
     * <p>
     * <code>optional string license_plate = 3;</code>
     */
    @Override
    public com.google.protobuf.ByteString
    getLicensePlateBytes() {
        final java.lang.Object ref = licensePlate_;
        if (ref instanceof java.lang.String) {
            final com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            licensePlate_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }
    
    private byte memoizedIsInitialized = -1;
    
    @Override
    public final boolean isInitialized() {
        final byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) {return true;}
        if (isInitialized == 0) {return false;}
        
        if (!extensionsAreInitialized()) {
            memoizedIsInitialized = 0;
            return false;
        }
        memoizedIsInitialized = 1;
        return true;
    }
    
    @Override
    public void writeTo(final com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        final com.google.protobuf.GeneratedMessageV3
                .ExtendableMessage<VehicleDescriptor>.ExtensionWriter
                extensionWriter = newExtensionWriter();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, label_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, licensePlate_);
        }
        extensionWriter.writeUntil(2000, output);
        unknownFields.writeTo(output);
    }
    
    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) {return size;}
        
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, label_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, licensePlate_);
        }
        size += extensionsSerializedSize();
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }
    
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof VehicleDescriptor)) {
            return super.equals(obj);
        }
        final VehicleDescriptor other = (VehicleDescriptor) obj;
        
        boolean result = true;
        result = result && (hasId() == other.hasId());
        if (hasId()) {
            result = result && getId()
                    .equals(other.getId());
        }
        result = result && (hasLabel() == other.hasLabel());
        if (hasLabel()) {
            result = result && getLabel()
                    .equals(other.getLabel());
        }
        result = result && (hasLicensePlate() == other.hasLicensePlate());
        if (hasLicensePlate()) {
            result = result && getLicensePlate()
                    .equals(other.getLicensePlate());
        }
        result = result && unknownFields.equals(other.unknownFields);
        result = result &&
                getExtensionFields().equals(other.getExtensionFields());
        return result;
    }
    
    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasId()) {
            hash = (37 * hash) + ID_FIELD_NUMBER;
            hash = (53 * hash) + getId().hashCode();
        }
        if (hasLabel()) {
            hash = (37 * hash) + LABEL_FIELD_NUMBER;
            hash = (53 * hash) + getLabel().hashCode();
        }
        if (hasLicensePlate()) {
            hash = (37 * hash) + LICENSE_PLATE_FIELD_NUMBER;
            hash = (53 * hash) + getLicensePlate().hashCode();
        }
        hash = hashFields(hash, getExtensionFields());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }
    
    public static VehicleDescriptor parseFrom(
            final java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    
    public static VehicleDescriptor parseFrom(
            final java.nio.ByteBuffer data,
            final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    
    public static VehicleDescriptor parseFrom(
            final com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    
    public static VehicleDescriptor parseFrom(
            final com.google.protobuf.ByteString data,
            final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    
    public static VehicleDescriptor parseFrom(final byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    
    public static VehicleDescriptor parseFrom(
            final byte[] data,
            final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    
    public static VehicleDescriptor parseFrom(final java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }
    
    public static VehicleDescriptor parseFrom(
            final java.io.InputStream input,
            final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }
    
    public static VehicleDescriptor parseDelimitedFrom(final java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }
    
    public static VehicleDescriptor parseDelimitedFrom(
            final java.io.InputStream input,
            final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    
    public static VehicleDescriptor parseFrom(
            final com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }
    
    public static VehicleDescriptor parseFrom(
            final com.google.protobuf.CodedInputStream input,
            final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }
    
    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    
    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }
    
    public static Builder newBuilder(final VehicleDescriptor prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    
    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }
    
    @java.lang.Override
    protected Builder newBuilderForType(
            final com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        final Builder builder = new Builder(parent);
        return builder;
    }
    
    /**
     * <pre>
     * Identification information for the vehicle performing the trip.
     * </pre>
     * <p>
     * Protobuf type {@code transit_realtime.VehicleDescriptor}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.ExtendableBuilder<
                    VehicleDescriptor, Builder> implements
            // @@protoc_insertion_point(builder_implements:transit_realtime.VehicleDescriptor)
            VehicleDescriptorOrBuilder {
        
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return GtfsRealtime.internal_static_transit_realtime_VehicleDescriptor_descriptor;
        }
        
        @Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return GtfsRealtime
                    .internal_static_transit_realtime_VehicleDescriptor_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            VehicleDescriptor.class, VehicleDescriptor.Builder.class);
        }
        
        // Construct using sen.khyber.subway.client.proto.VehicleDescriptor.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }
        
        private Builder(
                final com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }
        
        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }
        
        @Override
        public Builder clear() {
            super.clear();
            id_ = "";
            bitField0_ = (bitField0_ & ~0x00000001);
            label_ = "";
            bitField0_ = (bitField0_ & ~0x00000002);
            licensePlate_ = "";
            bitField0_ = (bitField0_ & ~0x00000004);
            return this;
        }
        
        @Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return GtfsRealtime.internal_static_transit_realtime_VehicleDescriptor_descriptor;
        }
        
        @Override
        public VehicleDescriptor getDefaultInstanceForType() {
            return VehicleDescriptor.getDefaultInstance();
        }
        
        @Override
        public VehicleDescriptor build() {
            final VehicleDescriptor result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }
        
        @Override
        public VehicleDescriptor buildPartial() {
            final VehicleDescriptor result = new VehicleDescriptor(this);
            final int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                to_bitField0_ |= 0x00000001;
            }
            result.id_ = id_;
            if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                to_bitField0_ |= 0x00000002;
            }
            result.label_ = label_;
            if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                to_bitField0_ |= 0x00000004;
            }
            result.licensePlate_ = licensePlate_;
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
        }
        
        @Override
        public Builder clone() {
            return (Builder) super.clone();
        }
        
        @Override
        public Builder setField(
                final com.google.protobuf.Descriptors.FieldDescriptor field,
                final java.lang.Object value) {
            return (Builder) super.setField(field, value);
        }
        
        @Override
        public Builder clearField(
                final com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }
        
        @Override
        public Builder clearOneof(
                final com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }
        
        @Override
        public Builder setRepeatedField(
                final com.google.protobuf.Descriptors.FieldDescriptor field,
                final int index, final java.lang.Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }
        
        @Override
        public Builder addRepeatedField(
                final com.google.protobuf.Descriptors.FieldDescriptor field,
                final java.lang.Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }
        
        @Override
        public <Type> Builder setExtension(
                final com.google.protobuf.GeneratedMessage.GeneratedExtension<
                        VehicleDescriptor, Type> extension,
                final Type value) {
            return (Builder) super.setExtension(extension, value);
        }
        
        @Override
        public <Type> Builder setExtension(
                final com.google.protobuf.GeneratedMessage.GeneratedExtension<
                        VehicleDescriptor, java.util.List<Type>> extension,
                final int index, final Type value) {
            return (Builder) super.setExtension(extension, index, value);
        }
        
        @Override
        public <Type> Builder addExtension(
                final com.google.protobuf.GeneratedMessage.GeneratedExtension<
                        VehicleDescriptor, java.util.List<Type>> extension,
                final Type value) {
            return (Builder) super.addExtension(extension, value);
        }
        
        @Override
        public <Type> Builder clearExtension(
                final com.google.protobuf.GeneratedMessage.GeneratedExtension<
                        VehicleDescriptor, ?> extension) {
            return (Builder) super.clearExtension(extension);
        }
        
        @Override
        public Builder mergeFrom(final com.google.protobuf.Message other) {
            if (other instanceof VehicleDescriptor) {
                return mergeFrom((VehicleDescriptor) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }
        
        public Builder mergeFrom(final VehicleDescriptor other) {
            if (other == VehicleDescriptor.getDefaultInstance()) {return this;}
            if (other.hasId()) {
                bitField0_ |= 0x00000001;
                id_ = other.id_;
                onChanged();
            }
            if (other.hasLabel()) {
                bitField0_ |= 0x00000002;
                label_ = other.label_;
                onChanged();
            }
            if (other.hasLicensePlate()) {
                bitField0_ |= 0x00000004;
                licensePlate_ = other.licensePlate_;
                onChanged();
            }
            mergeExtensionFields(other);
            mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }
        
        @Override
        public final boolean isInitialized() {
            if (!extensionsAreInitialized()) {
                return false;
            }
            return true;
        }
        
        @Override
        public Builder mergeFrom(
                final com.google.protobuf.CodedInputStream input,
                final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            VehicleDescriptor parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (final com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (VehicleDescriptor) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }
        
        private int bitField0_;
        
        private java.lang.Object id_ = "";
        
        /**
         * <pre>
         * Internal system identification of the vehicle. Should be unique per
         * vehicle, and can be used for tracking the vehicle as it proceeds through
         * the system.
         * </pre>
         * <p>
         * <code>optional string id = 1;</code>
         */
        @Override
        public boolean hasId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        
        /**
         * <pre>
         * Internal system identification of the vehicle. Should be unique per
         * vehicle, and can be used for tracking the vehicle as it proceeds through
         * the system.
         * </pre>
         * <p>
         * <code>optional string id = 1;</code>
         */
        @Override
        public java.lang.String getId() {
            final java.lang.Object ref = id_;
            if (!(ref instanceof java.lang.String)) {
                final com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                final java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    id_ = s;
                }
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }
        
        /**
         * <pre>
         * Internal system identification of the vehicle. Should be unique per
         * vehicle, and can be used for tracking the vehicle as it proceeds through
         * the system.
         * </pre>
         * <p>
         * <code>optional string id = 1;</code>
         */
        @Override
        public com.google.protobuf.ByteString
        getIdBytes() {
            final java.lang.Object ref = id_;
            if (ref instanceof String) {
                final com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                id_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }
        
        /**
         * <pre>
         * Internal system identification of the vehicle. Should be unique per
         * vehicle, and can be used for tracking the vehicle as it proceeds through
         * the system.
         * </pre>
         * <p>
         * <code>optional string id = 1;</code>
         */
        public Builder setId(
                final java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000001;
            id_ = value;
            onChanged();
            return this;
        }
        
        /**
         * <pre>
         * Internal system identification of the vehicle. Should be unique per
         * vehicle, and can be used for tracking the vehicle as it proceeds through
         * the system.
         * </pre>
         * <p>
         * <code>optional string id = 1;</code>
         */
        public Builder clearId() {
            bitField0_ = (bitField0_ & ~0x00000001);
            id_ = getDefaultInstance().getId();
            onChanged();
            return this;
        }
        
        /**
         * <pre>
         * Internal system identification of the vehicle. Should be unique per
         * vehicle, and can be used for tracking the vehicle as it proceeds through
         * the system.
         * </pre>
         * <p>
         * <code>optional string id = 1;</code>
         */
        public Builder setIdBytes(
                final com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000001;
            id_ = value;
            onChanged();
            return this;
        }
        
        private java.lang.Object label_ = "";
        
        /**
         * <pre>
         * User visible label, i.e., something that must be shown to the passenger to
         * help identify the correct vehicle.
         * </pre>
         * <p>
         * <code>optional string label = 2;</code>
         */
        @Override
        public boolean hasLabel() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        
        /**
         * <pre>
         * User visible label, i.e., something that must be shown to the passenger to
         * help identify the correct vehicle.
         * </pre>
         * <p>
         * <code>optional string label = 2;</code>
         */
        @Override
        public java.lang.String getLabel() {
            final java.lang.Object ref = label_;
            if (!(ref instanceof java.lang.String)) {
                final com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                final java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    label_ = s;
                }
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }
        
        /**
         * <pre>
         * User visible label, i.e., something that must be shown to the passenger to
         * help identify the correct vehicle.
         * </pre>
         * <p>
         * <code>optional string label = 2;</code>
         */
        @Override
        public com.google.protobuf.ByteString
        getLabelBytes() {
            final java.lang.Object ref = label_;
            if (ref instanceof String) {
                final com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                label_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }
        
        /**
         * <pre>
         * User visible label, i.e., something that must be shown to the passenger to
         * help identify the correct vehicle.
         * </pre>
         * <p>
         * <code>optional string label = 2;</code>
         */
        public Builder setLabel(
                final java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000002;
            label_ = value;
            onChanged();
            return this;
        }
        
        /**
         * <pre>
         * User visible label, i.e., something that must be shown to the passenger to
         * help identify the correct vehicle.
         * </pre>
         * <p>
         * <code>optional string label = 2;</code>
         */
        public Builder clearLabel() {
            bitField0_ = (bitField0_ & ~0x00000002);
            label_ = getDefaultInstance().getLabel();
            onChanged();
            return this;
        }
        
        /**
         * <pre>
         * User visible label, i.e., something that must be shown to the passenger to
         * help identify the correct vehicle.
         * </pre>
         * <p>
         * <code>optional string label = 2;</code>
         */
        public Builder setLabelBytes(
                final com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000002;
            label_ = value;
            onChanged();
            return this;
        }
        
        private java.lang.Object licensePlate_ = "";
        
        /**
         * <pre>
         * The license plate of the vehicle.
         * </pre>
         * <p>
         * <code>optional string license_plate = 3;</code>
         */
        @Override
        public boolean hasLicensePlate() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        
        /**
         * <pre>
         * The license plate of the vehicle.
         * </pre>
         * <p>
         * <code>optional string license_plate = 3;</code>
         */
        @Override
        public java.lang.String getLicensePlate() {
            final java.lang.Object ref = licensePlate_;
            if (!(ref instanceof java.lang.String)) {
                final com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                final java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    licensePlate_ = s;
                }
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }
        
        /**
         * <pre>
         * The license plate of the vehicle.
         * </pre>
         * <p>
         * <code>optional string license_plate = 3;</code>
         */
        @Override
        public com.google.protobuf.ByteString
        getLicensePlateBytes() {
            final java.lang.Object ref = licensePlate_;
            if (ref instanceof String) {
                final com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                licensePlate_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }
        
        /**
         * <pre>
         * The license plate of the vehicle.
         * </pre>
         * <p>
         * <code>optional string license_plate = 3;</code>
         */
        public Builder setLicensePlate(
                final java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000004;
            licensePlate_ = value;
            onChanged();
            return this;
        }
        
        /**
         * <pre>
         * The license plate of the vehicle.
         * </pre>
         * <p>
         * <code>optional string license_plate = 3;</code>
         */
        public Builder clearLicensePlate() {
            bitField0_ = (bitField0_ & ~0x00000004);
            licensePlate_ = getDefaultInstance().getLicensePlate();
            onChanged();
            return this;
        }
        
        /**
         * <pre>
         * The license plate of the vehicle.
         * </pre>
         * <p>
         * <code>optional string license_plate = 3;</code>
         */
        public Builder setLicensePlateBytes(
                final com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000004;
            licensePlate_ = value;
            onChanged();
            return this;
        }
        
        @Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }
        
        @Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }
        
        
        // @@protoc_insertion_point(builder_scope:transit_realtime.VehicleDescriptor)
    }
    
    // @@protoc_insertion_point(class_scope:transit_realtime.VehicleDescriptor)
    private static final VehicleDescriptor DEFAULT_INSTANCE;
    
    static {
        DEFAULT_INSTANCE = new VehicleDescriptor();
    }
    
    public static VehicleDescriptor getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }
    
    @java.lang.Deprecated public static final com.google.protobuf.Parser<VehicleDescriptor>
            PARSER = new com.google.protobuf.AbstractParser<>() {
        
        @Override
        public VehicleDescriptor parsePartialFrom(
                final com.google.protobuf.CodedInputStream input,
                final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new VehicleDescriptor(input, extensionRegistry);
        }
    };
    
    public static com.google.protobuf.Parser<VehicleDescriptor> parser() {
        return PARSER;
    }
    
    @java.lang.Override
    public com.google.protobuf.Parser<VehicleDescriptor> getParserForType() {
        return PARSER;
    }
    
    @Override
    public VehicleDescriptor getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }
    
}

